#+TITLE: O regime de reconhecimento em matéria matrimonial no Regulamento Bruxelas II /ter/
#+AUTHOR: João Gomes de Almeida
#+LANGUAGE: pt-PT

* Introdução
* Reconhecimento de decisões em matéria matrimonial
** Conceito de decisão

O conceito de decisão é a pedra de toque do regime de reconhecimento de decisões em matéria matrimonial e encontra-se definido como "uma decisão proferida por um tribunal de um Estado-Membro, incluindo qualquer acórdão, sentença ou despacho judicial que decreta o divórcio, a separação ou a anulação do casamento". Tata-se de um conceito /amplo/ que inclui quaisquer decisões que decretam o divórcio, a separação judicial ou a anulação do casamento, independentemente da sua designação no Estado-Membro de origem.

O regime de reconhecimento encontra-se limitado pelo âmbito de aplicação em razão da matéria do Regulamento Bruxelas II /ter/[fn:1]. Tendo presente que, relativamente às ações matrimoniais, o Regulamento visa unicamente a dissolução ou enfraquecimento do vínculo matrimonial[fn:2], é esse efeito que é objeto do regime de reconhecimento de decisões estrangeiras. As consequências que decorrem da dissolução do casamento, nomeadamente os efeitos patrimoniais, não podem ser objeto do regime de reconhecimento previsto no Regulamento Bruxelas II /ter/[Cf., neste sentido e em sede dos instrumentos precedentes, @almeida2017, p. 482; *Incluir LLP 2019 e MTS 2022*; e, na jurisprudência portuguesa, o Acórdão do Tribunal da Relação de Coimbra de 15 de março de 2008, proc. 225-C/1998.C1.].

A decisão tem de ser proferida por /um tribunal/ de /um Estado-Membro/. O Regulamento Bruxelas II /ter/ mantêm um conceito /amplo/ de tribunal, que abrange autoridade /não jurisdicionais/ como autoridades administrativas ou, como sucede nalguns Estados-Membros, os notários. Decisivo é que essas autoridades /não jurisdicionais/ tenham, no respetivo Estado-Membro, competência em matéria de ações matrimoniais ou em matéria relativa à responsabilidade parental. O conceito de Estado-Membro não é expressamente  definido, mas pode ser deduzido do âmbito de aplicação em razão do território e não inclui a Dinamarca. Às decisões proferidas por tribunais de Estados terceiros não é aplicável o regime de reconhecimento previsto no Regulamento Bruxelas II /ter/.

Salienta-se que a situação não carece de ser /transnacional/ à data em que é proferida a decisão, para esta beneficiar do regime de reconhecimento. Mesmo uma decisão proferida no âmbito de uma situação puramente interna pode beneficiar do regime de reconhecimento  do Regulamento Bruxelas II /ter/, caso, no futuro, venha a ser necessário o reconhecimento dessa decisão noutro Estado-Membro. Veja-se o seguinte exemplo: A. e B., são franceses, com residência habitual em França, e casados entre si. É proferida decisão de divórcio por um tribunal francês, na sequência de ação instaurada em setembro de 2022. Posteriormente, B. muda a sua residência habitual para Portugal e, em setembro de 2026, pretende casar com C. O reconhecimento (automático) da decisão francesa de divórcio é regido pelo Regulamento Bruxelas II /ter/, pois, no momento do reconhecimento, a situação já possui um elemento de estraneidade.

Não é igualmente necessário que a competência internacional do tribunal do Estado-Membro de origem tenha sido estabelecida de acordo com as normas atributivas de competência internacional do Regulamento Bruxelas II /ter/ (ou do Regulamento Bruxelas II /bis/ que o precedeu). As decisões que decretam o divórcio, separação judicial ou a anulação do casamento proferidas por tribunais cuja competência internacional foi estabelecida ao abrigo das competências residuais consagradas no artigo 6.º do Regulamento Bruxelas II /bis/ beneficiam do regime de reconhecimento de decisões estrangeiras. Tal pode deduzir-se da proibição de controlo de competência do tribunal de origem, pois mesmo nos casos em que a competência internacional do tribunal se funde numa competência exorbitante de fonte interna, tal não é fundamento de não reconhecimento dessa decisão.

Por fim, só beneficiam do regime de reconhecimento do Regulamento Bruxelas II /ter/ as decisões, proferidas em ações intentadas a partir de 1 de agosto de 2022[fn:5], /que decretam o divórcio, a separação judicial ou a anulação do casamento/[A inserção sistemática do artigo 15.º, na secção II do Capítulo II, relativa à responsabilidade parental, e o seu conteúdo mais focado na criança apontam no sentido de que o Regulamento Bruxelas II /ter/ dispõe apenas sobre medidas provisórias e cautelares em matéria de responsabilidade parental. Tal não sucedia em sede do Regulamento Bruxelas II /bis/, que adotava uma formulação mais neutra e estava inserido na seção III do Capítulo II, relativa às disposições comuns. Estes elementos e as precisões agora efetuadas no conceito de decisão (artigo 2.º, n.º 1, segundo e terceiro parágrafos) apontam no sentido de que eventuais medidas provisórias e cautelares decretadas em ações matrimoniais /não/ beneficam do regime de reconhecimento do Regulamento. Sobre a questão no Regulamento Bruxelas II /bis/, cf. @almeida2017, p. 499 e ss. e referêcnias aí indicadas.]. Em sede do Regulamento Bruxelas II /bis/ uma das questões mais debatidas era a de saber se o regime de reconhecimento de decisões estrangeiras abrangia qualquer decisão proferida por um tribunal num Estado-Membro relativa ao divórcio, separação judicial ou anulação do casamento ou se, pelo contrário, abrangia apenas as decisões proferidas por um tribunal num Estado-Membro que decretam o divórcio, a separação judicial ou a anulação do casamento. A nova redação[fn:3] aponta de forma mais clara no sentido (já sufragado pela maioria da doutrina no âmbito do Regulamento Bruxelas II /bis/) de que apenas as decisões que decretam o divórcio, a separação ou a anulação do casamento beneficiam do regime de reconhecimento do Regulamento Bruxelas II /ter/[fn:4].

Pode questionar-se se estas decisões só beneficiam do regime de reconhecimento após o trânsito em julgado. Em favor deste restrição depõe o artigo 30.º, n.º 2, do Regulamento Bruxelas II /ter/ que exige o trânsito em julgado da decisão em matéria matrimonial para efeitos de atualização dos registos do estado civil. Esta exigência compreende-se à luz da fé pública destes registos, mas não é transponível para a generalidade dos casos em que possa ser necessário o reconhecimento da decisão estrangeira. Por outro lado, e a nosso ver mais decisivo, o artigo 33.º, alínea /a)/, do Regulamento Bruxelas II /ter/ concede ao tribunal do Estado-Membro requerido a possibilidade[fn:6] de suspender a instância se a decisão estrangeira cujo reconhecimento é pretendido foi objeto de recurso ordinário no Estado-Membro de origem[O artigo 72.º do Regulamento Bruxelas II /ter/ esclarece que qualquer tipo de recurso na Irlanda e no Chipre deve ser considerado, para efeitos de reconhecimento, como sendo um recurso ordinário, permitindo assim o recurso à faculdade de suspensão da instância. Esta solução justifica-se por nesses Estados-Membros não existir a distinção entre recursos ordinários e extraordinários (cf. @magnus2012, p. 292). O conceito de recurso ordinário foi interpretado autonomamente pelo TJ, em sede da Convenção de Bruxelas, no sentido de abranger "qualquer via de recurso que faça parte do curso normal de um processo e que, enquanto tal, constitua uma fase processual com a qual qualquer das partes deva razoavelmente contar" (Acórdão de 22 de novembro de 1997, /Industrial Diamond Supplies/, 43/77, EU:C:1977:188, considerando n.º 37).]. Ora se as decisões que decretam o divórcio, a separação judicial ou a anulação do casamento suscetíveis de recurso ordinário não beneficiassem do regime de reconhecimento de decisões estrangeiras consagrado no Regulamento Bruxelas II /ter/, o preceito acima referido seria inútil.

** Princípio do reconhecimento automático
*** Considerações gerais

As decisões que decretam o divórcio, a separação judicial ou a anulação do casamento, proferidas por um tribunal de um Estado-Membro, são reconhecidas nos restantes automaticamente, isto é, sem quaisquer formalidades (artigo 33.º, n.º 1, do Regulamento Bruxelas II /ter/). O princípio do reconhecimento automático encontrava-se consagrado, em termos substancialmente idênticos, nos instrumentos que o antecederam[fn:7] e fundamenta-se no princípio da confiança mútua[fn:8].

Atendendo ao âmbito de aplicação material, o reconhecimento automático destas decisões abrange apenas a dissolução ou enfraquecimento do vínculo matrimonial.

O princípio do reconhecimento automático produz também um efeito negativo: impede o reconhecimento de decisões posteriores incompatíveis proferidas por tribunais de outros Estados-Membros que não o Estado-Membro requerido[Cf., no mesmo sentido, @meeusen2007, p. 147 e ss.; e @rauscher2015, 262.].

Todavia não é possível afirmar que através da adoção do princípio do reconhecimento automático as decisões proferidas por tribunais de outros Estados-Membros são equivalentes às decisões proferidas por tribunais do Estado-Membro requerido. Isto porque o princípio do reconhecimento automático é adotado condicionalmente: as decisões proferidas por tribunais do Estado-Membro de origem são reconhecidas até que se verifique um dos fundamentos de não reconhecimento da decisão[Cf., neste sentido, @magnus2012, p. 258; e @corneloup2013, pp. 369-370.]

*** Reconhecimento a título incidental

Por força da consagração do princípio do reconhecimento automático, o qual prescinde de qualquer procedimento prévio para o reconhecimento de decisões que decretem o divórcio proferidas por tribunais de outros Estados-Membros, a situação mais normal é que a questão do reconhecimento da decisão estrangeira surja, perante os tribunais, a título incidental, invocada no decurso de um determinado processo, seja como questão prévia[fn:9], seja como exceção[fn:10]. Esta invocação a título incidental é permitida pelo artigo 30.º, n.º 5, do Regulamento Bruxelas II /ter/, que estabelece: "Se o reconhecimento de uma decisão for invocado a título incidental perante um tribunal de um Estado-Membro, este é competente para o apreciar."

Pode questionar-se se o conceito de tribunal neste preceito é mais restrito do que o definido no artigo 2.º, limitando-se apenas aos tribunais /stricto sensu/. Consideramos que não. O Direito interno dos vários Estados-Membros pode estabelecer processos em que seja necessário invocar o reconhecimento a título incidental perante autoridades que apenas podem ser consideradas tribunais segundo o conceito /amplo/ adotado no artigo 2.º do Regulamento. É, pensa-se, o que sucede no Direito português quando processo de inventário decorra perante cartório notarial.

Suscita igualmente dúvidas como deve ser tramitado este reconhecimento a título incidental. Duas posições surgiram, no âmbito do Regulamento Bruxelas II /bis/: /(i)/ a tramitação é a estabelecida no Regulamento para a concessão de declaração de executoriedade, por força da aplicação analógica da remissão expressa prevista para ação de reconhecimento ou não reconhecimento a título principal[Cf., em sede de Regulamento Bruxelas I, cujas normas relevantes são substancialmente idênticas às do Regulamento Bruxelas II /bis/, @magnus2012a, p. 554-555.]; ou /(ii)/ é subsidiariamente aplicável a tramitação prevista no Direito interno do Estado-Membro requerido[Cf.  @baratta2008, p. 193;  @corneloup2013, p. 379; e *incluir LLP 2019 e MTS 2022*.]. Aderimos a esta última posição, pois o reconhecimento a título incidental foi consagrado por razões de simplicidade[@borras1998, p. 50, ponto 66; e @rauscher2015, p. 264.], dificilmente compatíveis com a posição que advoga uma identidade de tramitação com o pedido de decisão que determine não existirem os fundamentos de recusa do reconhecimento.

Pergunta-se a decisão se a decisão de reconhecimento ou não reconhecimento da decisão estrangeira, quando proferida a título incidental, constitui ou não caso julgado fora do processo respetivo. Subscreve-se o entendimento de que a questão deve ser resolvida de acordo com as normas de Direito vigentes no Estado-Membro requerido *Citar LLP 2019 e MTS 2022*. Considera-se que as normas do Regulamento Bruxelas II /ter/ não dão resposta a esta questão, pelo que, por força do princípio da subsidiariedade, a resposta deve procurar-se no restante Direito vigente no Estado-Membro requerido. Quando Portugal seja o Estado-Membro requerido as decisões de reconhecimento ou de não reconhecimento proferidas a título incidental não constituem, em regra, caso julgado fora do processo respetivo[fn:11].

Salienta-se, por fim, que se tiver sido apresentado um pedido de decisão que determine não haver fundamentos para recusar o reconhecimento a que se referem os artigos 38.º e 39.º (cf. artigo 30.º, n.º 3), ou um pedido de decisão que determine a recusa do reconhecimento com base num desses fundamentos (cf. artigo 40.º, n.º 1), o tribunal perante o qual o reconhecimento foi incidentalmente invocado pode suspender, total ou parcialmente, a instância[Cf. artigo 33.º, alínea /b)/, do Regulamento Bruxelas II /ter/. Trata-se de uma solução nova. Advogou-se, em sede do Regulamento Bruxelas /bis/, que o princípio da subsidiariedade apontava no sentido de que a questão deveria ser resolvida segundo o Direito vigente no Estado-Membro requerido (@almeida2017, p. 510).].

*** Valor da decisão como título de registo

O n.º 2 do artigo 30.º do Regulamento Bruxelas II /ter/ estende o princípio do reconhecimento automático à atualização dos registos do estado civil de um Estado-Membro com base numa decisão de divórcio, separação judicial ou anulação do casamento proferida noutro Estado-Membro. Trata-se de uma consagração importante pois, em muito casos, a atualização dos registos do estado civil é um dos efeitos mais pretendidos pelos interessados no reconhecimento da decisão estrangeira que decretou o divórcio, separação judicial ou anulação do casamento[Cf. @borras1998, p. 49, ponto 63; @corneloup2013, p. 371; e @rauscher2015, p. 265.].

O regime delineado por este preceito apenas é aplicável às decisões de divórcio, separação ou anulação do casamento, proferidas noutro Estado-Membro e das quais já não caiba recurso, segundo a legislação desse Estado-Membro. Esta solução justifica-se à luz da fé pública dos registos do estado civil. Mal se compreenderia que uma decisão que se encontra ou pode ainda ser impugnada pudesse justificar uma alteração dos registos do estado civil, pela situação de incerteza que tal acarretaria[Cf., neste sentido, @helms2001, p. 260; @schack2002, p. 51; @corneloup2013, p. 370; e @rauscher2015, p. 266.].

Apesar de o preceito não distinguir entre recursos ordinários e extraordinários, entende-se que a intenção legislativa é a de exigir o trânsito em julgado da decisão estrangeira, o mesmo é dizer, exigir que a mesma não fosse já suscetível de recurso ordinário[O preceito mantém-se substancialmente inalterado desde a Convenção de Bruxelas II. No relatório explicativo desta Convenção (@borras1998, pp. 49-50, ponto 63) afirma-se que "Deve observar-se que é necessário tratar-se de uma decisão final, ou seja, não suscetível de recurso ordinário segundo a lei do Estado de origem".].

*** Pedido de declaração judicial de que não existem fundamentos de recusa do reconhecimento ou pedido de recusa de reconhecimento

Sem prejuízo da adoção do princípio do reconhecimento automático e da possibilidade de invocar o reconhecimento a título incidental, o artigo 30.º, n.º 3, do Regulamento Bruxelas II /bis/ estabelece que qualquer parte interessada pode, em conformidade com os procedimentos previstos nos artigos 59.º a 62.º, bem como, se for caso disso, na secção 5 do presente capítulo e no capítulo VI, requerer que seja adotada uma decisão que determine /não/ existirem os fundamentos de recusa do reconhecimento a que se referem os artigos 38.º e 39.º[fn:13].

Esta nova formulação parece ser mais restrita do que a prevista no artigo 21.º, n.º 3, do Regulamento Bruxelas II /bis/ onde se estabelece que qualquer parte interessada pode requerer, nos termos dos procedimentos previstos na secção 2 do presente capítulo, /o reconhecimento ou o não-reconhecimento/ da decisão. Porém, a diferença é apenas de técnica legislativa, uma vez que o artigo 40.º, n.º 1, do Regulamento Bruxelas II /ter/ prevê que os processos previstos nos artigos 59.º a 62.º, bem como, se for caso disso, na secção 5 do presente capítulo e no capítulo VI, são aplicáveis em conformidade aos pedidos de recusa de reconhecimento. Em suma, o Regulamento Bruxelas II /ter/, com esta alteração, adota a técnica legislativa do Regulamento Bruxelas I /bis/[fn:12].

O conceito de parte interessada deve ser interpretado em sentido amplo,  não se reconduzindo exclusivamente aos ex-cônjuges. Para que um terceiro seja considerado uma parte interessada e tenha legitimidade para intentar a ação de reconhecimento ou de não reconhecimento da decisão estrangeira parece necessário que do reconhecimento ou não reconhecimento da decisão resulte uma afetação da sua esfera jurídica[Cf., neste sentido, @corneloup2013, p. 375; e @rauscher2015, p. 269.]. O conceito de parte interessada pode também incluir autoridades públicas[Cf., neste sentido, @borras1998, p. 50, ponto 65; @helms2001, p. 261; @magnus2012, p. 260; @corneloup2013, p. 375; @pinheiro2019b, p. *XX*; e *MTS 2022*], como o Ministério Público ou as autoridades públicas responsáveis pelo registo civil, em proteção de um interesse público[fn:14].



** Limites ao reconhecimento
*** Proibição do controlo de competência do tribunal de origem

O Regulamento Bruxelas II /ter/ consagra, no artigo 68.º, a proibição do controlo de competência do tribunal de origem. O tribunal do Estado-Membro requerido não pode verificar a competência do tribunal do Estado-Membro de origem; tal significa que o desrespeito pelas normas atributivas de competência internacional consagradas no Regulamento Bruxelas II bis e até a utilização de normas atributivas de competência internacional exorbitantes não constitui fundamento para a recusa de reconhecimento de uma decisão, proferida por um tribunal de um Estado-Membro, que decrete o divórcio, a separação judicial ou a anulação do casamento.

O principal fundamento apresentado para a consagração da proibição do controlo de competência do Estado-Membro de origem é o princípio da confiança mútua[fn:15],o qual é reforçado pela unificação, em larga medida, das normas atributivas de competência internacional. Esta uniformização facilita o abandono do controlo da competência do tribunal de origem, uma vez que os tribunais dos Estados-Membros determinam se são ou não competentes para um divórcio transnacional através da aplicação das mesmas normas de competência internacional. Apesar de a unificação não ser exaustiva[fn:16], considera-se os objetivos do Regulamento e o carácter verdadeiramente residual da remissão para as restantes normas vigentes no Direito de cada Estado-Membro permitem justificar esta solução de proibição do controlo de competência do tribunal de origem[Cf., em sede de Regulamento Bruxelas II /bis/ e com maiores detalhes, @almeida2017, p. 524 e ss.].

A proibição de controlo de competência do tribunal de origem pode também ser justificada como contraponto ao regime previsto no artigo 18.º do Regulamento Bruxelas II /ter/, que estabelece a obrigação de o tribunal de origem controlar oficiosamente a sua própria competência. A opção do legislador da União Europeia parece ter sido a de que apenas os tribunais do Estado-Membro onde é colocado o litígio transnacional podem aferir da competência internacional para julgar o mesmo. A proibição do controlo da competência do tribunal de origem pode ser entendida e justificada como a concretização desta opção em sede de reconhecimento de decisões estrangeiras[fn:17].

Não obstante, foram consagradas (contadas) exceções ao princípio da proibição do controlo de competência do tribunal de origem. Assim, resulta da definição do conceito de decisão (artigo 2.º, n.º 1) que só beneficiam do regime de reconhecimento do Regulamento as medidas provisórias e cautelares proferidas por um tribunal competente para o mérito da causa ou no contexto de uma decisão de regresso da criança; os tribunais do Estado-Membro requerido terão de aferir a competência do tribunal do Estado-Membro para determinar se as medidas provisórias e cautelares decretadas beneficiam ou não do regime de reconhecimento. Em matéria de reconhecimento de atos autênticos e acordos em matéria matrimonial consagrou-se, como veremos /infra/, a competência indireta como pressuposto do regime de reconhecimento (artigo 64.º). Por fim, em sede de relações com outros atos, estabelece-se que as decisões em matéria matrimonial proferidas por tribunais de Estados-Membros ao abrigo da Convenção de 6 de fevereiro de 1931 entre a Dinamarca, a Finlândia, a Islândia, a Noruega e a Suécia relativa às disposições de Direito Internacional Privado em matéria de casamento, adoção e guarda de menores e o respetivo protocolo final só beneficiam do regime de reconhecimento do Regulamento se o tribunal que proferiu a decisão tivesse competência internacional para julgar a ação matrimonial nos termos das regras do Regulamento Bruxelas II /ter/ (artigo 94.º, n.º 5)[fn:18].

*** Proibição de controlo do mérito da decisão objeto de reconhecimento
*** Fundamentos de recusa
**** Considerações gerais
**** Ordem pública internacional
**** Garantia do direito de defesa
**** Incompatibilidade de decisões
* Reconhecimento de atos autênticos e acordos em matéria matrimonial
* Conclusões

* Artigos a comentar :no export:
- 30.º a 33.º
- 36.º a 37.º
- 38.º e 40.º
- 59.º a 62.º
- 64.º a 68.º
- 69.º a 75.º

| RBII /ter/ | RB II /bis/     | Observações  |
|------------+-----------------+--------------|
| 30.º/1 e 2 | 21.º /1 e 2     | feito        |
| 30.º/3 e 4 | 21.º/3          |              |
| 30.º/5     | 21.º/4          | feito        |
| 31.º/1     | 37.º/1 e 45.º/1 |              |
| 31.º/2 e 3 | 45.º/2          |              |
| 32.º       | 38.º            |              |
| 33.º/a)    | 27.º/1          | feito        |
| 33.º/b)    | -               | feito        |
| 36.º       | 39.º            |              |
| 37.º       | 43.º            |              |
| 38.º       | 22.º            |              |
| 40.º       | -               | n.º 1 feito; |
| 59.º       | -               |              |
| 60.º       | -               |              |
| 61.º       | -               |              |
| 62.º       | -               |              |
| 64.º       | -               |              |
| 65.º       | 46.º            |              |
| 66.º       | -               |              |
| 67.º       | -               |              |
| 68.º       | -               |              |
| 69.º       | 24.º            | feito        |
| 70.º       | 25.º            |              |
| 71.º       | 26.º            |              |
| 72.º       | -               |              |
| 73.º       | 49.º            |              |
| 74.º/1     | 50.º            |              |
| 74.º/2     | -               |              |
| 75.º       | 51.º            |              |

* Footnotes
[fn:18] Sobre este preceito cf. o nosso artigo mencionada na nota 1.

[fn:17] A fundamentação da proibição do controlo da competência do tribunal de origem com base no princípio da confiança mútua, unificação (quase integral) das normas de competência internacional e no controlo da competência apenas pelos tribunais do Estado-Membro do foro parece ter sido perfilhada pelo TJ, em sede de Regulamento Bruxelas II /bis/, no Acórdão de 15 de julho de 2010, /Purrucker/, C-256/09, EU:C:2010:437, considerandos n.ºs 72 a 75. Apesar de o Acórdão ter sido proferido em matéria de responsabilidade parental, não existem particularidades que impeçam a sua transposição para as ações matrimoniais.

[fn:16] Cf. artigo 6.º do Regulamento Bruxelas II /ter/.

[fn:15] Cf. considerandos n.ºs 54 e 55 do Regulamento Bruxelas II /ter/.

[fn:14] Por exemplo, nos casos em que a autoridade pública considere verificado um dos fundamentos de não reconhecimento da decisão estrangeira.

[fn:13] Doravante designada abreviadamente, por razões de facilidade de leitura, de ação de reconhecimento.

[fn:12] Cf. artigos 36.º, n.º 2, e 45.º, n.º 4, do Regulamento Bruxelas II /bis/.

[fn:11] Artigo 91.º do Código de Processo Civil (CPC).

[fn:10] Imagine-se, por exemplo, que A., depois de obter decisão de divórcio num outro Estado-Membro que dissolveu o seu casamento com B., casa em Portugal com C. D. (pai de C.) intenta ação de anulação do casamento em Portugal, com fundamento em casamento anterior não dissolvido.

[fn:9] Pense-se, por exemplo, na situação em que um ex-cônjuge (em virtude de um decisão de divórcio proferida num outro Estado-Membro) se apresenta num processo de inventário a correr termos em Portugal, alegando ser herdeiro legitimário do autor da sucessão (o anterior cônjuge).

[fn:8] Cf. considerando n.º 54 do Regulamento Bruxelas II /ter/.

[fn:7] Cf. artigo 14.º, n.º 1, da Convenção de Bruxelas II, artigo 14.º, n.º 1, do Regulamento Bruxelas II e artigo 21.º, n.º 1, do Regulamento Bruxelas II /bis/.

[fn:6] Esta possibilidade de suspensão da instância surge apenas quando for requerido o não reconhecimento da decisão estrangeira ou quando o reconhecimento da decisão for invocado a título incidental.

[fn:5] Cf. artigo 100.º do Regulamento Bruxelas II /ter/.

[fn:4] Cf., neste sentido, o último período do considerando n.º 9 do Regulamento Bruxelas II /ter/.

[fn:3] As versões inglesa ("including a decree, order or judgment, /granting/ divorce, legal separation, or annulment of a marriage,"), francesa ("y compris un arrêt, un jugement ou une ordonnance, /accordant/ le divorce, la séparation de corps ou l’annulation d’un mariage"), espanhola ("en particular un fallo, una orden o una resolución que conceda el divorcio, la separación legal, la nulidad matrimonial"), italiana ("inclusi un decreto, un’ordinanza o una sentenza, /che sancisca/ il divorzio, la separazione personale dei coniugi, l’annullamento del matrimonio") e alemã ("einschließlich einer Verfügung, eines Beschlusses oder eines Urteils, mit der die Ehescheidung, die Trennung ohne Auflösung des Ehebandes oder die Ungültigerklärung einer Ehe /ausgesprochen wird/") apontam no mesmo sentido. Itálicos aditados.

[fn:2] Cf. considerando n.º 9 do Regulamento Bruxelas II /ter/.

[fn:1] Sobre este cf. o nosso outro artigo nesta revista "Âmbito de aplicação, definições e relações com outros atos do Regulamento Bruxelas II /ter/".
