#+TITLE: Reconhecimento de decisões, atos autênticos e acordos em matéria matrimonial no Regulamento Bruxelas II /ter/
#+AUTHOR: João Gomes de Almeida
#+LANGUAGE: pt-PT

*Sumário:* O Regulamento Bruxelas II /ter/ reformula e substitui o Regulamento Bruxelas II /bis/ e, a partir de 1 de agosto de 2022, as suas normas serão aplicáveis. O presente artigo visa analisar as normas uniformes de reconhecimento de decisões, atos autênticos e acordos em matéria matrimonial establecidas por este Regulamento.

*Summary:* Brussels II /ter/ Regulation recasts and replaces Brussels II /bis/. The new rules apply from 1 August 2022. This article aims to provide a first look into the uniform rules on the recognition of decisions, authentic instruments and agreements in matrimonial matters established by this Regulation.

*Palavras-chave:* Regulamento Bruxelas II /ter/; direito do reconhecimento; matéria matrimonial; reconhecimento de decisões; reconhecimento de atos autênticos e acordos.

*Keywords:* Brussels II /ter/ Regulation; recogntion; matrimonial matters; recognition of decisions; recognition of authentic instruments and agreements.

* I. Introdução

O presente texto visa analisar o regime de reconhecimento em matéria material do Regulamento Bruxelas II /ter/[fn:74]. Este Regulamento reformula e substitui o Regulamento Bruxelas II /bis/[fn:75] e os seus regimes de reconhecimento serão aplicáveis às ações judiciais intentadas, aos atos autênticos formalmente exarados e aos acordos registados a partir de 1 de agosto de 2022.

Exclui-se a matéria da execução, em virtude da natureza da decisão de divórcio, separação judicial ou anulação do casamento. Trata-se de decisões cujo efeito (a dissolução ou enfraquecimento do vínculo matrimonial) se produz automaticamente. Como tal, não têm um conteúdo suscetível de execução, uma vez que não é necessária uma conduta, por ação ou omissão, do réu para que a decisão produza os seus efeitos[fn:64].

Efetua-se, primeiramente, uma análise do regime de reconhecimento de decisões em matéria matrimonial, seguido do novo regime de reconhecimento de atos autênticos e acordos e das conclusões.

* II. Reconhecimento de decisões em matéria matrimonial
** A) Conceito de decisão

O conceito de decisão é a pedra de toque do regime de reconhecimento de decisões em matéria matrimonial e encontra-se definido como "uma decisão proferida por um tribunal de um Estado-Membro, incluindo qualquer acórdão, sentença ou despacho judicial que decreta o divórcio, a separação ou a anulação do casamento". Tata-se de um conceito /amplo/ que inclui quaisquer decisões que decretam o divórcio, a separação judicial ou a anulação do casamento, independentemente da sua designação no Estado-Membro de origem.

O regime de reconhecimento encontra-se limitado pelo âmbito de aplicação em razão da matéria do Regulamento Bruxelas II /ter/[fn:1]. Tendo presente que, relativamente às ações matrimoniais, o Regulamento visa unicamente a dissolução ou enfraquecimento do vínculo matrimonial[fn:2], é esse efeito que é objeto do regime de reconhecimento de decisões estrangeiras. As consequências que decorrem da dissolução do casamento, nomeadamente os efeitos patrimoniais, não podem ser objeto do regime de reconhecimento previsto no Regulamento Bruxelas II /ter/[Cf., neste sentido e em sede dos instrumentos precedentes, @almeida2017, p. 482; @pinheiro2019b, p. 152; e @mendes2022a, p. 365 e, na jurisprudência portuguesa, o Acórdão do Tribunal da Relação de Coimbra de 15 de março de 2008, proc. 225-C/1998.C1.].

A decisão tem de ser proferida por /um tribunal/ de /um Estado-Membro/. O Regulamento Bruxelas II /ter/ mantêm um conceito /amplo/ de tribunal, que abrange autoridade /não jurisdicionais/ como autoridades administrativas ou, como sucede nalguns Estados-Membros, os notários. Decisivo é que essas autoridades /não jurisdicionais/ tenham, no respetivo Estado-Membro, competência em matéria de ações matrimoniais ou em matéria relativa à responsabilidade parental. O conceito de Estado-Membro não é expressamente  definido, mas pode ser deduzido do âmbito de aplicação em razão do território e não inclui a Dinamarca. Às decisões proferidas por tribunais de Estados terceiros não é aplicável o regime de reconhecimento previsto no Regulamento Bruxelas II /ter/.

Salienta-se que a situação não carece de ser /transnacional/ à data em que é proferida a decisão, para esta beneficiar do regime de reconhecimento. Mesmo uma decisão proferida no âmbito de uma situação puramente interna pode beneficiar do regime de reconhecimento  do Regulamento Bruxelas II /ter/, caso, no futuro, venha a ser necessário o reconhecimento dessa decisão noutro Estado-Membro. Veja-se o seguinte exemplo: A. e B., são franceses, com residência habitual em França, e casados entre si. É proferida decisão de divórcio por um tribunal francês, na sequência de ação instaurada em setembro de 2022. Posteriormente, B. muda a sua residência habitual para Portugal e, em setembro de 2026, pretende casar com C. O reconhecimento (automático) da decisão francesa de divórcio é regido pelo Regulamento Bruxelas II /ter/, pois, no momento do reconhecimento, a situação já possui um elemento de estraneidade.

Não é igualmente necessário que a competência internacional do tribunal do Estado-Membro de origem tenha sido estabelecida de acordo com as normas atributivas de competência internacional do Regulamento Bruxelas II /ter/ (ou do Regulamento Bruxelas II /bis/ que o precedeu). As decisões que decretam o divórcio, separação judicial ou a anulação do casamento proferidas por tribunais cuja competência internacional foi estabelecida ao abrigo das competências residuais consagradas no artigo 6.º do Regulamento Bruxelas II /bis/ beneficiam do regime de reconhecimento de decisões estrangeiras. Tal pode deduzir-se da proibição de controlo de competência do tribunal de origem, pois mesmo nos casos em que a competência internacional do tribunal se funde numa competência exorbitante de fonte interna, tal não é fundamento de não reconhecimento dessa decisão.

Por fim, só beneficiam do regime de reconhecimento do Regulamento Bruxelas II /ter/ as decisões, proferidas em ações intentadas a partir de 1 de agosto de 2022[fn:5], /que decretam o divórcio, a separação judicial ou a anulação do casamento/[A inserção sistemática do artigo 15.º, na secção II do Capítulo II, relativa à responsabilidade parental, e o seu conteúdo mais focado na criança apontam no sentido de que o Regulamento Bruxelas II /ter/ dispõe apenas sobre medidas provisórias e cautelares em matéria de responsabilidade parental. Tal não sucedia em sede do Regulamento Bruxelas II /bis/, que adotava uma formulação mais neutra e estava inserido na seção III do Capítulo II, relativa às disposições comuns. Estes elementos e as precisões agora efetuadas no conceito de decisão (artigo 2.º, n.º 1, segundo e terceiro parágrafos) apontam no sentido de que eventuais medidas provisórias e cautelares decretadas em ações matrimoniais /não/ beneficam do regime de reconhecimento do Regulamento. Sobre a questão no Regulamento Bruxelas II /bis/, cf. @almeida2017, p. 499 e ss. e referências aí indicadas.]. Em sede do Regulamento Bruxelas II /bis/ uma das questões mais debatidas era a de saber se o regime de reconhecimento de decisões estrangeiras abrangia qualquer decisão proferida por um tribunal num Estado-Membro relativa ao divórcio, separação judicial ou anulação do casamento ou se, pelo contrário, abrangia apenas as decisões proferidas por um tribunal num Estado-Membro que decretam o divórcio, a separação judicial ou a anulação do casamento. A nova redação[fn:3] aponta de forma mais clara no sentido (já sufragado pela maioria da doutrina no âmbito do Regulamento Bruxelas II /bis/) de que apenas as decisões que decretam o divórcio, a separação ou a anulação do casamento beneficiam do regime de reconhecimento do Regulamento Bruxelas II /ter/[fn:4].

Pode questionar-se se estas decisões só beneficiam do regime de reconhecimento após o trânsito em julgado. Em favor deste restrição depõe o artigo 30.º, n.º 2, do Regulamento Bruxelas II /ter/ que exige o trânsito em julgado da decisão em matéria matrimonial para efeitos de atualização dos registos do estado civil. Esta exigência compreende-se à luz da fé pública destes registos, mas não é transponível para a generalidade dos casos em que possa ser necessário o reconhecimento da decisão estrangeira. Por outro lado, e a nosso ver mais decisivo, o artigo 33.º, alínea /a)/, do Regulamento Bruxelas II /ter/ concede ao tribunal do Estado-Membro requerido a possibilidade[fn:6] de suspender a instância se a decisão estrangeira cujo reconhecimento é pretendido foi objeto de recurso ordinário no Estado-Membro de origem[O artigo 72.º do Regulamento Bruxelas II /ter/ esclarece que qualquer tipo de recurso na Irlanda e no Chipre deve ser considerado, para efeitos de reconhecimento, como sendo um recurso ordinário, permitindo assim o recurso à faculdade de suspensão da instância. Esta solução justifica-se por nesses Estados-Membros não existir a distinção entre recursos ordinários e extraordinários (cf. @magnus2012, p. 292). O conceito de recurso ordinário foi interpretado autonomamente pelo TJ, em sede da Convenção de Bruxelas de 1968 relativa à Competência Jurisdicional e à Execução de Decisões em matéria civil e comercial, publicada no JO L 299, de 31 de dezembro de 1972 (doravante Convenção de Bruxelas), no sentido de abranger "qualquer via de recurso que faça parte do curso normal de um processo e que, enquanto tal, constitua uma fase processual com a qual qualquer das partes deva razoavelmente contar" (Acórdão de 22 de novembro de 1997, /Industrial Diamond Supplies/, 43/77, EU:C:1977:188, considerando n.º 37).]. Ora se as decisões que decretam o divórcio, a separação judicial ou a anulação do casamento suscetíveis de recurso ordinário não beneficiassem do regime de reconhecimento de decisões estrangeiras consagrado no Regulamento Bruxelas II /ter/, o preceito acima referido seria inútil.

** B) Princípio do reconhecimento automático
*** 1. Considerações gerais

As decisões que decretam o divórcio, a separação judicial ou a anulação do casamento, proferidas por um tribunal de um Estado-Membro, são reconhecidas nos restantes automaticamente, isto é, sem quaisquer formalidades (artigo 33.º, n.º 1, do Regulamento Bruxelas II /ter/). O princípio do reconhecimento automático encontrava-se consagrado, em termos substancialmente idênticos, nos instrumentos que o antecederam[fn:7] e fundamenta-se no princípio da confiança mútua[fn:8].

Atendendo ao âmbito de aplicação material, o reconhecimento automático destas decisões abrange apenas a dissolução ou enfraquecimento do vínculo matrimonial.

O princípio do reconhecimento automático produz também um efeito negativo: impede o reconhecimento de decisões posteriores incompatíveis proferidas por tribunais de outros Estados-Membros que não o Estado-Membro requerido[Cf., no mesmo sentido, @meeusen2007, p. 147 e ss.; e @rauscher2015, 262.].

Todavia não é possível afirmar que através da adoção do princípio do reconhecimento automático as decisões proferidas por tribunais de outros Estados-Membros são equivalentes às decisões proferidas por tribunais do Estado-Membro requerido. Isto porque o princípio do reconhecimento automático é adotado condicionalmente: as decisões proferidas por tribunais do Estado-Membro de origem são reconhecidas até que se verifique um dos fundamentos de não reconhecimento da decisão[Cf., neste sentido, @magnus2012, p. 258; e @corneloup2013, pp. 369-370.]

*** 2. Reconhecimento a título incidental

Por força da consagração do princípio do reconhecimento automático, o qual prescinde de qualquer procedimento prévio para o reconhecimento de decisões que decretem o divórcio proferidas por tribunais de outros Estados-Membros, a situação mais normal é que a questão do reconhecimento da decisão estrangeira surja, perante os tribunais, a título incidental, invocada no decurso de um determinado processo, seja como questão prévia[fn:9], seja como exceção[fn:10]. Esta invocação a título incidental é permitida pelo artigo 30.º, n.º 5, do Regulamento Bruxelas II /ter/, que estabelece: "Se o reconhecimento de uma decisão for invocado a título incidental perante um tribunal de um Estado-Membro, este é competente para o apreciar."

Pode questionar-se se o conceito de tribunal neste preceito é mais restrito do que o definido no artigo 2.º, limitando-se apenas aos tribunais /stricto sensu/. Consideramos que não. O Direito interno dos vários Estados-Membros pode estabelecer processos em que seja necessário invocar o reconhecimento a título incidental perante autoridades que apenas podem ser consideradas tribunais segundo o conceito /amplo/ adotado no artigo 2.º do Regulamento. É, pensa-se, o que sucede no Direito português quando processo de inventário decorra perante cartório notarial.

Suscita igualmente dúvidas como deve ser tramitado este reconhecimento a título incidental. Duas posições surgiram, no âmbito do Regulamento Bruxelas II /bis/: /(i)/ a tramitação é a estabelecida no Regulamento para a concessão de declaração de executoriedade, por força da aplicação analógica da remissão expressa prevista para ação de reconhecimento ou não reconhecimento a título principal[Cf., em sede do Regulamento (CE) n.º 44/2001 do Conselho, de 22 de Dezembro de 2000, relativo à competência judiciária, ao reconhecimento e à execução de decisões em matéria civil e comercial, publicado no JO L 12, de 16 de janeiro de 2001 (doravante Regulamento Bruxelas I), cujas normas relevantes são substancialmente idênticas às do Regulamento Bruxelas II /bis/, @magnus2012a, p. 554-555.]; ou /(ii)/ é subsidiariamente aplicável a tramitação prevista no Direito interno do Estado-Membro requerido[Cf.  @baratta2008, p. 193;  @corneloup2013, p. 379; e @pinheiro2019b, p. 159.]. Aderimos a esta última posição, pois o reconhecimento a título incidental foi consagrado por razões de simplicidade[@borras1998, p. 50, ponto 66; e @rauscher2015, p. 264.], dificilmente compatíveis com a posição que advoga uma identidade de tramitação com o pedido de decisão que determine não existirem os fundamentos de recusa do reconhecimento.

Pergunta-se a decisão se a decisão de reconhecimento ou não reconhecimento da decisão estrangeira, quando proferida a título incidental, constitui ou não caso julgado fora do processo respetivo. Subscreve-se o entendimento de que a questão deve ser resolvida de acordo com as normas de Direito vigentes no Estado-Membro requerido[cf. @pinheiro2019b, pp. 159 e 87.]. Considera-se que as normas do Regulamento Bruxelas II /ter/ não dão resposta a esta questão, pelo que, por força do princípio da subsidiariedade, a resposta deve procurar-se no restante Direito vigente no Estado-Membro requerido. Quando Portugal seja o Estado-Membro requerido as decisões de reconhecimento ou de não reconhecimento proferidas a título incidental não constituem, em regra, caso julgado fora do processo respetivo[fn:11].

Salienta-se, por fim, que se tiver sido apresentado um pedido de decisão que determine não haver fundamentos para recusar o reconhecimento a que se referem os artigos 38.º e 39.º (cf. artigo 30.º, n.º 3), ou um pedido de decisão que determine a recusa do reconhecimento com base num desses fundamentos (cf. artigo 40.º, n.º 1), o tribunal perante o qual o reconhecimento foi incidentalmente invocado pode suspender, total ou parcialmente, a instância[Cf. artigo 33.º, alínea /b)/, do Regulamento Bruxelas II /ter/. Trata-se de uma solução nova. Advogou-se, em sede do Regulamento Bruxelas /bis/, que o princípio da subsidiariedade apontava no sentido de que a questão deveria ser resolvida segundo o Direito vigente no Estado-Membro requerido (cf. @almeida2017, p. 510).].

*** 3. Valor da decisão como título de registo

O n.º 2 do artigo 30.º do Regulamento Bruxelas II /ter/ estende o princípio do reconhecimento automático à atualização dos registos do estado civil de um Estado-Membro com base numa decisão de divórcio, separação judicial ou anulação do casamento proferida noutro Estado-Membro. Trata-se de uma consagração importante pois, em muito casos, a atualização dos registos do estado civil é um dos efeitos mais pretendidos pelos interessados no reconhecimento da decisão estrangeira que decretou o divórcio, separação judicial ou anulação do casamento[Cf. @borras1998, p. 49, ponto 63; @corneloup2013, p. 371; e @rauscher2015, p. 265.].

O regime delineado por este preceito apenas é aplicável às decisões de divórcio, separação ou anulação do casamento, proferidas noutro Estado-Membro e das quais já não caiba recurso, segundo a legislação desse Estado-Membro. Esta solução justifica-se à luz da fé pública dos registos do estado civil. Mal se compreenderia que uma decisão que se encontra ou pode ainda ser impugnada pudesse justificar uma alteração dos registos do estado civil, pela situação de incerteza que tal acarretaria[Cf., neste sentido, @helms2001, p. 260; @schack2002, p. 51; @corneloup2013, p. 370; e @rauscher2015, p. 266.].

Apesar de o preceito não distinguir entre recursos ordinários e extraordinários, entende-se que a intenção legislativa é a de exigir o trânsito em julgado da decisão estrangeira, o mesmo é dizer, exigir que a mesma não fosse já suscetível de recurso ordinário[O preceito mantém-se substancialmente inalterado desde a Convenção de Bruxelas II. No relatório explicativo desta Convenção (@borras1998, pp. 49-50, ponto 63) afirma-se que "Deve observar-se que é necessário tratar-se de uma decisão final, ou seja, não suscetível de recurso ordinário segundo a lei do Estado de origem".].

*** 4. Pedido de declaração judicial de que não existem fundamentos de recusa do reconhecimento ou pedido de recusa de reconhecimento

Sem prejuízo da adoção do princípio do reconhecimento automático e da possibilidade de invocar o reconhecimento a título incidental, o artigo 30.º, n.º 3, do Regulamento Bruxelas II /bis/ estabelece que qualquer parte interessada pode, em conformidade com os procedimentos previstos nos artigos 59.º a 62.º, bem como, se for caso disso, na secção 5 do presente capítulo e no capítulo VI, requerer que seja adotada uma decisão que determine /não/ existirem os fundamentos de recusa do reconhecimento a que se referem os artigos 38.º e 39.º[Doravante designada abreviadamente, por razões de facilidade de leitura, de ação de reconhecimento. Verdadeiramente, não há uma ação de reconhecimento, pois o reconhecimento é automático, faltando assim o requisito do interesse em agir. Porém, pode haver interesse, nos casos em que se verifique uma situação de incerteza, em intentar ação de mera apreciação negativa que declare não se verificar nenhum dos fundamentos de recusa do reconhecimento de decisões em matéria matrimonial, previstos no artigo 38.º do Regulamento Bruxelas II /ter/. Cf., neste sentido, @mendes2022a, p. 336.].

Esta nova formulação parece ser mais restrita do que a prevista no artigo 21.º, n.º 3, do Regulamento Bruxelas II /bis/ onde se estabelece que qualquer parte interessada pode requerer, nos termos dos procedimentos previstos na secção 2 do presente capítulo, /o reconhecimento ou o não-reconhecimento/ da decisão. Porém, a diferença é apenas de técnica legislativa, uma vez que o artigo 40.º, n.º 1, do Regulamento Bruxelas II /ter/ prevê que os processos previstos nos artigos 59.º a 62.º, bem como, se for caso disso, na secção 5 do presente capítulo e no capítulo VI, são aplicáveis em conformidade aos pedidos de recusa de reconhecimento. Em suma, o Regulamento Bruxelas II /ter/, com esta alteração, aproxima-se da técnica legislativa do Regulamento Bruxelas I /bis/[Regulamento (UE) n.º 1215/2012 do Parlamento Europeu e do Conselho, de 12 de dezembro de 2012, relativo à competência judiciária, ao reconhecimento e à execução de decisões em matéria civil e comercial, publicado no JO L 351, de 20 de dezembro de 2012. Cf., em sentido similar, @forcadamiranda2020, pp. 287-288.] [fn:12].

O conceito de parte interessada deve ser interpretado em sentido amplo,  não se reconduzindo exclusivamente aos ex-cônjuges. Para que um terceiro seja considerado uma parte interessada e tenha legitimidade para intentar a ação de reconhecimento ou de não reconhecimento da decisão estrangeira parece necessário que do reconhecimento ou não reconhecimento da decisão resulte uma afetação da sua esfera jurídica[Cf., neste sentido, @corneloup2013, p. 375; e @rauscher2015, p. 269.]. O conceito de parte interessada pode também incluir autoridades públicas[Cf., neste sentido, @borras1998, p. 50, ponto 65; @helms2001, p. 261; @magnus2012, p. 260; @corneloup2013, p. 375; @pinheiro2019b, p. 159; e @mendes2022a, p. 364.], como o Ministério Público ou as autoridades públicas responsáveis pelo registo civil, em proteção de um interesse público[fn:14]. Apesar disso, assinala-se que, segundo o considerando n.º 54 do Regulamento Bruxelas II /ter/, cabe ao direito do Estado-Membro requerido determinar quem pode ser considerado parte interessada e se os fundamentos de recusa de reconhecimento carecem ou não de alegação pelas partes[fn:40].

Cada Estado-Membro comunica quais são os tribunais competentes para apreciar as ações de reconhecimento ou não reconhecimento[fn:48], sendo a competência em razão do território determinada segundo o Direito processual vigente em cada Estado-Membro[fn:49]. A tramitação destas ações é regida pelo Direito processual vigente no Estado-Membro requerido, em tudo o que não esteja regulado no Regulamento Bruxelas II /ter/. De seguida, aborda-se, muito sumariamente, os elementos da tramitação regulados pelo Regulamento Bruxelas II /ter/.

O pedido deve ser acompanhado dos documentos indicados, respetivamente, nos artigos 36.º (ação de reconhecimento)[fn:50] e 59.º (ação de não reconhecimento) do Regulamento Bruxelas II /ter/. A principal diferença parece ser a de que, na ação de não reconhecimento, é suficiente a apresentação de uma mera cópia da decisão, não sendo necessário que esta cumpra os requisitos de autenticidade da lei do Estado-Membro de origem[Solução semelhante à adotada no artigo 47.º do Regulamento Bruxelas I /bis/ que não deixa de suscitar dúvidas, pois a decisão a reconhecer é o objeto do ação. Cf., neste sentido, @magnus2016a, p. 956.].

Caso o requerente tenha beneficiado, no processo que correu termos no Estado-Membro de origem, de assistência judiciária ou de isenção de preparos e custas, o Regulamento concede-lhe, no contexto das ações de reconhecimento e de não reconhecimento, a assistência judiciária mais favorável ou a isenção mais ampla prevista na lei do Estado-Membro requerido[fn:51]. Visando a redução de obstáculos de cariz económico, estabelece-se que não pode ser exigida qualquer caução ou depósito, seja qual for a sua designação, ao requerente das ações de reconhecimento ou de não reconhecimento, com fundamento na sua qualidade de estrangeiro ou na falta de residência habitual no Estado-Membro requerido[fn:52]. Não pode igualmente exigir-se que o requerente tenha um endereço postal no Estado-Membro requerido e apenas se pode exigir um representante autorizado se tal representante for obrigatório ao abrigo do direito do Estado-Membro requerido independentemente da nacionalidade das partes[fn:53].

O tribunal deve decidir sem demora[fn:54]. A decisão que profira é passível de um ou dois recursos, consoante as comunicações efetuadas por cada um dos Estados-Membros[fn:55].

*** 5. Documentos a apresentar

Sempre que uma parte interessada pretenda invocar num processo judicial, a titulo principal ou incidental, uma decisão em matéria matrimonial proferida noutro Estado-Membro, cabe-lhe a ela fazer prova da existência dessa decisão. O mesmo sucede quando se pretenda atualizar os registos do estado civil de um Estado-Membro com base numa decisão de divórcio, separação ou anulação do casamento[Cf., neste sentido, @magnus2012, p. 329.]. O Regulamento Bruxelas II /ter/ define, de forma autónoma, quais são os documentos necessários para fazer prova da decisão no artigo 31.º.

O primeiro documento a apresentar é uma cópia da decisão, que satisfaça os requisitos de autenticidade necessários[fn:41]. Não se exige a apresentação do original da decisão, bastando a apresentação de um cópia, desde que a mesma cumpra os requisitos de autenticidade. Este documento é necessário para o tribunal do Estado-Membro requerido apreciar os fundamentos de recusa do reconhecimento[Cf. @magnus2016a, p. 825.]. O Regulamento /não/ define quais são os requisitos de autenticidade da decisão. Os requisitos de autenticidade são definidos pelo Direito do Estado-Membro de origem[Cf., @borras1998, p. 57, ponto 103; @magnus2012, p. 330; @corneloup2013, p. 430; @forcadamiranda2020, p. 294; no âmbito do Regulamento Bruxelas I /bis/, @magnus2016a, p. 825; e @vouga2019, p. 83. Releva-se ainda que, atendendo ao artigo 90.º do Regulamento Bruxelas II /ter/, não será exigível a legalização ou outra formalidade análoga].

O segundo documento é a certidão, conforme o formulário que constitui o Anexo II do Regulamento Bruxelas I /ter/. É competente para emitir a certidão o tribunal do Estado-Membro de origem. O tribunal tem a obrigação de emitir a certidão, sempre que uma parte o requeira[fn:42].   A emissão da certidão não é suscetível de impugnação[fn:43], com exceção dos casos em que, devido a erro material ou omissão, exista discrepância entre a decisão e a certidão. Nestes casos, o tribunal do Estado-Membro de origem deve, oficiosamente ou a pedido de uma das partes, retificar a certidão[fn:44]. A certidão é redigida e emitida na língua da decisão. A diferença entre redação e emissão justifica-se pelo facto de o formulário ser uniforme e estar disponível nas várias línguas oficiais da União Europeia. Assim, por exemplo, se a parte o requerer, o tribunal português pode, para emitir a certidão, utilizar o formulário disponível em língua francesa; porém, essa utilização não o obriga a redigir os campos de texto livre do formulário em língua francesa, podendo fazê-lo nessa língua ou em português (língua da decisão).

O tribunal ou autoridade competente do Estado-Membro requerido pode, quando seja necessário, requerer uma tradução ou transliteração[fn:45] dos campos de texto livre da certidão e da decisão. O objetivo parece ser o reduzir custos e entraves à "circulação" da decisão. A tradução ou transliteração dos campos de texto livre da certidão só pode ser exigida "se necessário". Parece assim, que o tribunal do Estado-Membro requerido só pode exigir a tradução ou transliteração quando, após exame da certidão, subsistam dúvidas sobre o conteúdo dos campos de texto de livre[Cf., no mesmo sentido e em sede do Regulamento Bruxelas I /bis/, @magnus2016a, p. 828.]. Quanto à tradução ou transliteração da decisão, a expressão "/para além/ da tradução ou transliteração do conteúdo traduzível dos campos de texto livre da certidão, /se não puder dar seguimento ao processo sem essa tradução ou transliteração/"[fn:46] dá a entender um carácter /subsidiário/ e /excecional/: só é possível exigir a tradução ou transliteração da decisão quando a tradução ou transliteração da certidão não tenha permitido resolver as dúvidas. Dúvidas essas que, para serem relevantes, têm de impedir o seguimento do processo[Cf. @magnus2016a, pp. 828 e 856-857. Como sugestivamente referem, não basta uma sensação de desconforto com a língua estrangeira para se exigir a tradução ou transliteração.].

A não apresentação da cópia autenticada da decisão e ou da certidão é regulada no artigo 32.º do Regulamento Bruxelas II /ter/. A principal novidade é a possibilidade de o tribunal ou autoridade competente do Estado-Membro requerido dispensar a apresentação da cópia autenticada da decisão ou de a substituir por documentos equivalentes. Resulta do artigo 32.º do Regulamento Bruxelas II /ter/ que qualquer um dos documentos exigidos no artigo 31.º pode ser substituído ou dispensado pelo tribunal do Estado-Membro requerido. A solução, no que se refere à cópia autenticada da decisão, não parece isenta de críticas. Em caso de não apresentação de qualquer um dos documentos, o tribunal ou autoridade competente pode: /(i)/ fixar um prazo para a sua apresentação; /(ii)/ aceitar documentar equivalentes[É discutível o que se deve entender por "documentos equivalentes". @magnus2012, pp. 337-338, parece entender que se trata de documentos que não são ou não cumprem os requisitos previstos para a cópia autenticada da decisão ou certidão, mas permitem provar os mesmos factos. Este critério é de aplicação mais complexa à cópia autenticada da decisão. Será uma cópia simples da decisão um "documento equivalente"? E como poderão os factos estabelecidas pela decisão ser provados por outros documentos? Atendendo, pensa-se, a amplitude do conceito de "documentos equivalentes", o tribunal ou autoridade do Estado-Membro requerido tem também um amplo campo de descricionariedade para decidir se exige ou não a tradução ou transliteração destas documentos.]; ou /(iii)/ dispensar a sua apresentação, se se julgar suficientemente esclarecido. Se, depois de fixado prazo, os documentos exigidos continuarem sem ser apresentados e nenhuma das duas remanescentes soluções for viável, o tribunal ou autoridade competente do Estado-Membro requerido deve indeferir o pedido.

** C) Limites ao reconhecimento
*** 1. Proibição do controlo de competência do tribunal de origem

O Regulamento Bruxelas II /ter/ consagra, no artigo 68.º, a proibição do controlo de competência do tribunal de origem. O tribunal do Estado-Membro requerido não pode verificar a competência do tribunal do Estado-Membro de origem; tal significa que o desrespeito pelas normas atributivas de competência internacional e de litispendência[fn:21] consagradas no Regulamento Bruxelas II /ter/ e até a utilização de normas atributivas de competência internacional exorbitantes não constitui fundamento para a recusa de reconhecimento de uma decisão, proferida por um tribunal de um Estado-Membro, que decrete o divórcio, a separação judicial ou a anulação do casamento.

O principal fundamento apresentado para a consagração da proibição do controlo de competência do Estado-Membro de origem é o princípio da confiança mútua[fn:15],o qual é reforçado pela unificação, em larga medida, das normas atributivas de competência internacional. Esta uniformização facilita o abandono do controlo da competência do tribunal de origem, uma vez que os tribunais dos Estados-Membros determinam se são ou não competentes para um divórcio transnacional através da aplicação das mesmas normas de competência internacional. Apesar de a unificação não ser exaustiva[fn:16], considera-se os objetivos do Regulamento e o carácter verdadeiramente residual da remissão para as restantes normas vigentes no Direito de cada Estado-Membro permitem justificar esta solução de proibição do controlo de competência do tribunal de origem[Cf., em sede de Regulamento Bruxelas II /bis/ e com maiores detalhes, @almeida2017, p. 524 e ss.].

A proibição de controlo de competência do tribunal de origem pode também ser justificada como contraponto ao regime previsto no artigo 18.º do Regulamento Bruxelas II /ter/, que estabelece a obrigação de o tribunal de origem controlar oficiosamente a sua própria competência. A opção do legislador da União Europeia parece ter sido a de que apenas os tribunais do Estado-Membro onde é colocado o litígio transnacional podem aferir da competência internacional para julgar o mesmo. A proibição do controlo da competência do tribunal de origem pode ser entendida e justificada como a concretização desta opção em sede de reconhecimento de decisões estrangeiras[fn:17].

Não obstante, foram consagradas (contadas) exceções ao princípio da proibição do controlo de competência do tribunal de origem. Assim, resulta da definição do conceito de decisão (artigo 2.º, n.º 1) que só beneficiam do regime de reconhecimento do Regulamento as medidas provisórias e cautelares proferidas por um tribunal competente para o mérito da causa ou no contexto de uma decisão de regresso da criança; os tribunais do Estado-Membro requerido terão de aferir a competência do tribunal do Estado-Membro de origem para determinar se as medidas provisórias e cautelares por este decretadas beneficiam ou não do regime de reconhecimento. Em matéria de reconhecimento de atos autênticos e acordos em matéria matrimonial consagrou-se, como veremos /infra/, a competência indireta como pressuposto do regime de reconhecimento (artigo 64.º). Por fim, em sede de relações com outros atos, estabelece-se que as decisões em matéria matrimonial proferidas por tribunais de Estados-Membros ao abrigo da Convenção de 6 de fevereiro de 1931 entre a Dinamarca, a Finlândia, a Islândia, a Noruega e a Suécia relativa às disposições de Direito Internacional Privado em matéria de casamento, adoção e guarda de menores e o respetivo protocolo final só beneficiam do regime de reconhecimento do Regulamento se o tribunal que proferiu a decisão tivesse competência internacional para julgar a ação matrimonial nos termos das regras do Regulamento Bruxelas II /ter/ (artigo 94.º, n.º 5)[fn:18].

*** 2. Proibição de controlo do mérito da decisão objeto de reconhecimento

O Regulamento Bruxelas II /ter/ proíbe o controlo do mérito da decisão, proferida por um tribunal de um Estado-Membro, que decrete o divórcio, a separação judicial ou a anulação do casamento. O controlo do mérito por parte do tribunal do Estado-Membro de reconhecimento encontra-se vedado, seja na vertente fraca, em que se controla apenas a lei aplicada, seja na vertente forte, em que se controla também se a lei foi corretamente interpretada e aplicada[Sobre as vertentes do controlo de mérito, cf. @pinheiro2019b, p. 70.].

A proibição de revisão quanto ao mérito, na vertente forte, encontra-se claramente consagrada no artigo 71.º do Regulamento Bruxelas II /ter/[fn:19], onde se estabelece que "A decisão proferida noutro Estado-Membro não pode em caso algum ser revista quanto ao mérito".

A proibição de revisão quanto ao mérito, na vertente fraca, pode ser deduzida do artigo 70.º do Regulamento Bruxelas II /ter/, no qual se estabelece que "O reconhecimento de uma decisão em matéria matrimonial não pode ser recusado com o fundamento de a lei do Estado-Membro requerido não permitir o divórcio, a separação ou a anulação do casamento com base nos mesmos factos". Esta disposição[fn:20] parece ter uma dupla função: limita o recurso à reserva de ordem pública internacional como fundamento de recusa do reconhecimento e proíbe o controlo da lei aplicável. O preceito indubitavelmente constitui "um limite ao uso indiscriminado da ordem pública"[@borras1998, p. 53, ponto 76.]. Por outro lado, a menção a "lei do Estado-Membro requerido" visa abranger não só o direito material, como as normas de conflitos, daí resultando a proibição de controlar a lei aplicada[@borras1998, p. 53, ponto 76.].

A razão de ser da (manutenção da) consagração deste preceito parece encontrar-se na (ainda) grande divergência de conceções materiais quanto ao instituto do divórcio. Esta razão coloca o acento tónico na relação entre esta disposição e a ordem pública internacional. Não obstante, a proibição abrange também o controlo da lei que foi efetivamente aplicada na decisão proferida pelo tribunal do Estado-Membro de origem. Considera-se, por isso, que, no que se refere ao controlo da lei aplicável, o artigo 70.º tem uma função clarificadora face ao artigo 71.º, ambos do Regulamento Bruxelas II /ter/.

Os casos em que o tribunal do Estado-Membro de origem tenha aplicado erroneamente o seu Direito de Conflitos, tenha aplicado erroneamente o Direito material ou tenha apreciado erroneamente a matéria de facto, também são abrangidos pela proibição de revisão de mérito e, como tal, não constituem motivo para recusar o reconhecimento da decisão estrangeira[fn:22].

*** 3. Fundamentos de recusa
**** 3.1. Considerações gerais

Os fundamentos que permitem ao tribunal do Estado-Membro requerido recusar o reconhecimento de uma decisão, proferida por um tribunal de outro Estado-Membro, que decrete o divórcio encontram-se elencados no artigo 38.º do Regulamento Bruxelas II /ter/. Estes fundamentos são substancialmente idênticos aos previstos no Regulamento Bruxelas II /bis/, Regulamento Bruxelas II e na Convenção de Bruxelas II e bastante próximos dos consagrados no Regulamento Bruxelas I /bis/, Regulamento Bruxelas I e na Convenção de Bruxelas.

O elenco dos fundamentos de recusa tem natureza taxativa[O entendimento é maioritamente (senão unanimemente) sufragado pela doutrina. Veja-se, na doutrina portuguesa e sem qualquer pretensão de exaustividade, @ramos2016a, p. 224; e @pinheiro2019b, p. 166]. Tal infere-se da proibição de revisão de mérito, que veda o controlo da lei aplicável e da substância da decisão pelo tribunal do Estado-Membro requerido[Cf., neste sentido, @rauscher2015, p. 294.]; da menção expressa de que os fundamentos de recusa foram “reduzidos ao mínimo indispensável”[fn:23]; e da jurisprudência do TJ[fn:24].

É, no entanto, questionável se apenas os fundamentos elencados no artigo 22.º do Regulamento Bruxelas II bis permitem ao tribunal do Estado-Membro requerido recusar o reconhecimento de uma decisão que decrete o divórcio proferida por um tribunal de outro Estado-Membro. A doutrina tem entendido que outros motivos existem que fundamentam a recusa de reconhecimento. Em primeiro lugar, a decisão a reconhecer tem de ser uma decisão, nos termos da definição constante do artigo 2.º, n.º 1, do Regulamento Bruxelas II /ter/. Não deve igualmente ser reconhecida uma decisão que não se enquadre dentro do âmbito de aplicação em razão da matéria do Regulamento Bruxelas II /ter/[fn:25] [Cf. @pinheiro2019b, p. 166.]. Concorda-se com a solução, mas assinala-se que estes dois fundamentos são ainda deduzíveis do corpo do artigo 38.º do Regulamento Bruxelas II bis, na medida em que aí se faz referência a uma “decisão de divórcio, separação ou anulação do casamento”.

Quando o reconhecimento ou não reconhecimento da decisão que decrete o divórcio seja suscitado a título principal é igualmente sustentado que o tribunal deve verificar a legitimidade do requerente e indeferir o requerimento caso o requerente não seja uma parte interessada[Cf. @sousa2003, p. 232.]. Concorda-se com a solução. Entende-se, porém, que neste caso estamos perante um pressuposto processual e não perante um fundamento de recusa de reconhecimento da mesma natureza que os elencados no artigo 38.º do Regulamento Bruxelas II /ter/. A falta de legitimidade do requerente não é um fundamento inerente à decisão estrangeira cujo reconhecimento ou não reconhecimento se visa. É uma questão referente às partes. E como tal, se uma outra pessoa, com legitimidade, solicitar o reconhecimento ou não reconhecimento a título principal pode a decisão estrangeira ser reconhecida. Pelo contrário, verificada uma das alíneas do artigo 38.º, a decisão não é passível de reconhecimento, independentemente de quem sejam as partes.

Para além disso, a decisão proferida nos dois casos é, necessariamente, diferente. Se o requerente não é parte legítima, a decisão estrangeira não é reconhecida, sendo proferida uma decisão de absolvição do réu da instância. Se o tribunal do Estado-Membro requerido considerar que está preenchida alguma das alíneas do artigo 38.º do Regulamento Bruxelas II /ter/, será proferida uma decisão de não reconhecimento, isto é, uma decisão de mérito que, depois de transitada em julgado, tem força de caso julgado material.

Por estes motivos, considera-se que a legitimidade do requerente não é, verdadeiramente, um fundamento de recusa do reconhecimento, tal como não o é, por exemplo, a incompetência em razão da matéria ou da hierarquia do tribunal em que foi requerido esse reconhecimento[fn:26].

**** 3.2. Ordem pública internacional

Uma decisão que decrete o divórcio, proferida por um tribunal de outro Estado-Membro, pode não ser reconhecida “se o reconhecimento for manifestamente contrário à ordem pública do Estado-Membro requerido”[fn:27]. O advérbio "manifestamente" salienta o carácter excecional do recurso à ordem pública internacional. em sede do Regulamento Bruxelas II /bis/, assinala-se que, relativamente "ao reconhecimento de decisões em matéria matrimonial e de responsabilidade parental, o motivo de «ordem pública» foi raramente invocado para justificar o não reconhecimento"[@comissaoeuropeia2014, p. 11.].

A proibição de controlo da competência do tribunal de origem (cf. /supra/) aponta no mesmo sentido. A violação, pelo tribunal do Estado-Membro de origem, das regras de competência (incluindo a litispendência e ações dependentes) do Regulamento Bruxelas II /ter/ ou o recurso a normas de competência internacional exorbitantes não são reconduzíveis ao fundamento de recusa do reconhecimento assente na violação manifesta da ordem pública internacional do Estado-Membro requerido.

Discute-se se é possível recorrer ao fundamento da ordem pública internacional para não reconhecer uma decisão proferida por um tribunal de um Estado-Membro cuja competência foi provocada em fraude à lei[Cf. @gaudemet-tallon2001, p. 401; @magnus2012, p. 270; @corneloup2013, p. 404 e ss.; e @rauscher2015, p. 291.]. Considera-se que se incluem dentro do âmbito desta hipótese de competência do tribunal de origem fraudulentamente estabelecida as situações em que o cônjuge requerente ou ambos os cônjuges prestam informações erradas ao tribunal com o intuito de o convencer que está preenchido um dos elementos de conexão em que assentam os critérios alternativos de atribuição de competência consagrados no Regulamento Bruxelas II /ter/. Aceita-se que esta situação pode ser enquadrada neste fundamento de recusa desde que: /(i)/ não tenha sido apreciada pelo tribunal do Estado-Membro de origem; e /(ii)/ apenas nos casos em que não é mais possível reagir contra a atividade fraudulenta junto dos tribunais do Estado-Membro de origem[Cf., com mais detalhes, @almeida2017, pp. 540-542.].

O modo como se articula este fundamento de recusa com o artigo 70.º do Regulamento Bruxelas II /ter/ também suscita dúvidas. Se este último preceito for lido de forma literal, parece possível sustentar que o mesmo consagra uma impossibilidade de recorrer à ordem pública internacional quanto aos fundamentos do divórcio. O Estado-Membro requerido não poderia recusar o reconhecimento da decisão de divórcio proferida pelo tribunal do Estado-Membro de origem, com base em qualquer fundamento, considerando que esse fundamento de divórcio era contrário à sua ordem pública internacional[Cf., aparentemente neste sentido, @jantera-jareborg1999, pp. 23-24; @mceleavy2004, p. 638; e @corneloup2013, p. 389]. Este entendimento parece-nos demasiado amplo e, consequentemente, demasiado restritivo do campo de operação do fundamento de recusa assente na violação manifesta da ordem pública internacional do Estado-Membro requerido. Considera que a melhor posição é a que entende que a mera divergência quanto ao fundamento do divórcio não constitui, direta e imediatamente, um motivo para recusar o reconhecimento da decisão estrangeira. Para que se possa recusar o reconhecimento é necessário que essa divergência constitua "uma violação manifesta de uma regra de direito considerada essencial na ordem jurídica do Estado requerido ou de um direito considerado fundamental pela mesma"[fn:28] [Cf., com maiores detalhes, @almeida2017, pp. 542-546; e, neste sentido, @rauscher2015, p. 293; e @pinheiro2019b, p. 167.].

A ordem pública internacional relevante é a do Estado-Membro requerido. Como tal, o conteúdo da ordem pública internacional pode ser, e em princípio será, diferente consoante o Estado-Membro em que seja pedido o reconhecimento da decisão que decrete o divórcio, a separação judicial ou a anulação do casamento. A avaliação da conformidade desse pedido de reconhecimento com a ordem pública internacional do Estado-Membro requerido constitui tarefa que só pode ser efetuada no caso concreto[Em @almeida2017, pp. 546-550, procurou-se analisar alguns exemplos de situações em que o reconhecimento de decisões que decretam o divórcio pode suscitar problemas de conformidade com a ordem pública internacional portuguesa.].

**** 3.3. Garantia do direito de defesa

O fundamento de recusa previsto no artigo 38.º, alínea /b)/, do Regulamento Bruxelas II /ter/, visa garantir que ao cônjuge requerido é concedida a oportunidade de apresentar a sua defesa na ação de divórcio, separação judicial ou anulação do casamento. Este fudamento só é aplicável quando a decisão estrangeira que decrete o divórcio transnacional tenha sido proferida à revelia. Para ser considerado parte revel, o cônjuge requerido não pode ter apresentado qualquer defesa no processo que culminou com a decisão proferida no Estado-Membro de origem, devendo ser equiparados a esta situação os casos em que o cônjuge requerido intervém no processo apenas para declarar que não foi citado em tempo útil e de forma a poder deduzir a sua defesa[Cf., neste sentido, @corneloup2013, p. 389; @rauscher2015, p. 275.].

De igual modo, o reconhecimento da decisão estrangeira não pode ser recusado com base neste fundamento se, apesar de o cônjuge requerido ser revel, a citação tiver sido efetuada “em tempo útil e de forma a poder deduzir a defesa”[fn:29]. A regularidade da citação do cônjuge requerido revel não é uma garantia concedida ao requerido. A irregularidade da citação só é relevante para efeitos da recusa do reconhecimento quando a mesma afete o seu direito de defesa[Cf., neste sentido, @nishuilleabhain2010, p. 265; @magnus2012, p. 272; @corneloup2013, pp. 390-391; @rauscher2015, p. 276; @almeida2017, p. 553.].

A efetiva observância dos direitos de defesa do cônjuge requerido é prosseguida através de duas condições que devem ser aferidas pelo tribunal do Estado-Membro requerido. A citação do cônjuge requerido deve ser efetuada em tempo útil /e/ de modo a que este tenha a oportunidade de organizar e apresentar a sua defesa.

Relativamente à primeira condição pode questionar-se: /(i)/ a partir de que momento se deve começar a contar o tempo e /(ii)/ qual a duração relevante para uma citação ter sido efetuada em tempo útil. Em regra, o tribunal do Estado-Membro requerido deve considerar que a contagem do tempo se inicia na data em que o ato introdutório da instância ou ato equivalente lhe foi citado[fn:30]. A duração é aferida tendo em conta o momento inicial e o momento em que, segundo o Direito do Estado-Membro de origem, o cônjuge requerido deixa de poder apresentar a sua defesa no processo[fn:31]. Saber se esta duração temporal constitui ou não um citação em tempo útil é uma questão que tem de ser aferida, em concreto, pelo tribunal do Estado-Membro requerido, tendo em conta as circunstâncias do caso, e independentemente das regras vigentes no Estado-Membro requerido ou no Estado-Membro de origem[fn:32].

A condição “de forma a poder deduzir a sua defesa” pode ser entendida como um requisito de qualidade da citação. A citação do cônjuge requerido pode ser efetuada em tempo útil, mas de uma forma que impeça ou dificulte que o réu organize e apresente a sua defesa[fn:33].

Por fim, este fundamento de recusa de reconhecimento não é aplicável nos casos em que o cônjuge requerido tenha aceitado a decisão estrangeira de forma inequívoca. Esta exceção compreende-se à luz dos objetivos visados pelo preceito. Pretende-se garantir que o cônjuge requerido tem a oportunidade de organizar e apresentar a sua defesa no processo que culmina com a decisão de divórcio transnacional. Todavia, se o cônjuge requerido que viu o seu direito de defesa prejudicado aceita inequivocamente a decisão, deixa de ser necessário proteger o direito do cônjuge requerido a ter uma oportunidade de apresentar a sua defesa no processo, uma vez que é o próprio cônjuge requerido que manifesta, de forma inequívoca, a sua concordância com a decisão que foi proferida sem a sua intervenção.

Não constitui uma aceitação inequívoca da decisão por parte do cônjuge requerido, o mero facto de este não ter interposto recurso da decisão no tribunal do Estado-Membro de origem[Cf., neste sentido, @corneloup2013, p. 391; @rauscher2015, p. 277; @pinheiro2019b, p. 168; e @mendes2022a, p. 367.]. A aceitação inequívoca deve demonstrar que o cônjuge requerido aceitou a substância da decisão, isto é, o decretamento do divórcio, da separação judicial ou da anulação do casamento. Tal sucede, por exemplo, quando o cônjuge requerido contrai novo casamento[Cf. @borras1998, p. 51, ponto 70; @magnus2012, p. 273; @corneloup2013, p. 391; @pinheiro2019b, p. 168; e @mendes2022a, p. 367.], quando solicita ao ex-cônjuge uma pensão de alimentos[Cf. @corneloup2013, p. 391; @rauscher2015, p. 277; e @mendes2022a, p. 367.] ou quando efetua uma pedido de alteração do registo de estado civil[Cf. @magnus2012, p. 273.].

**** 3.4. Incompatibilidade com outra decisão, ato autêntico ou acordo registado

O último fundamento de recusa de reconhecimento de decisões proferidas por tribunais de outros Estados-Membros que decretem o divórcio, a separação judicial ou a anulação do casamento assenta na incompatibilidade com outra decisão, ato autêntico ou acordo registado. Apesar de o artigo 38.º se referir expressamente apenas às decisões, entende-se que, em matéria matrimonial, se tem de atender também aos casos de "desjudicialização", isto é, as situações em que, por exemplo, o divórcio se efetua perante de um notário, sem que este possa ser considerado um tribunal e, consequentemente, sem que haja uma decisão, tal como definida no artigo 2.º, n.º 1, do Regulamento Bruxelas II /ter/. Não o fazer conduziria a resultados absurdos: imagine-se que se pretende reconhecer em França uma decisão de separação judicial proferida em Portugal. Sucede, porém, que o divórcio já tinha sido decretado em França, perante um notário. Se dermos primazia ao elemento literal, a decisão de separação judicial portuguesa deve ser reconhecida em França, pois não há /decisão/ (mais sim um ato autêntico) com ela incompatível, apesar de o casamento já se encontrar dissolvido naquele País[fn:47]. De qualquer modo, e apenas por conveniência e facilidade de exposição e leitura, seguir-se-á tendo por referência a incompatibilidade de decisões.

A decisão estrangeira não será reconhecida no Estado-Membro requerido se for incompatível com uma outra decisão proferida num processo entre as mesmas partes por um tribunal do Estado-Membro requerido[fn:34] ou por um tribunal de outro Estado-Membro ou de um Estado terceiro[fn:35]. Quando a incompatibilidade seja com uma decisão proferida por um tribunal de outro Estado-Membro ou de um Estado terceiro, o reconhecimento só será recusado se, adicionalmente, a decisão proferida pelo tribunal de outro Estado-Membro ou de um Estado terceiro for anterior e reunir as condições para ser reconhecida no Estado-Membro requerido[fn:36].

Existem assim dois requisitos comuns (identidade de partes e incompatibilidade) e dois requisitos específicos (prioridade temporal e condições de reconhecimento), aplicáveis quando o confronto seja com uma decisão proferida por um tribunal de outro Estado-Membro ou de um Estado terceiro.

A exigência de identidade de partes, consagrada expressamente na letra do preceito, justifica-se tendo presente a necessidade de assegurar a possibilidade de intervenção das partes no processo que culminou numa decisão que pode impedir o reconhecimento de uma outra decisão obtida junto dos tribunais do Estado-Membro de origem[Cf., neste sentido, @nishuilleabhain2010, pp. 267-268.].

Há incompatibilidade entre as duas decisões quando as mesmas forem irreconciliáveis entre si, isto é, quando produzam efeitos jurídicos que se excluem reciprocamente[fn:37]. Esta análise deve ser efetuada do perspetiva do Estado-Membro requerido. Assim, por exemplo, uma decisão proferida por um tribunal do Estado-Membro requerido  que decrete a separação judicial não é incompatível com uma decisão proferida pelo Estado-Membro de origem que decrete o divórcio, uma vez que esta última decisão produz um efeito jurídico diferente – a dissolução do vínculo matrimonial –, que consome o efeito jurídico produzido pela decisão de separação judicial. Na situação inversa – divórcio decretado por um tribunal do Estado-Membro requerido e separação judicial decretada por decisão do Estado-Membro origem –, as decisões já são incompatíveis entre si, pois não é possível reconhecer uma decisão de separação judicial (a qual não extingue o vínculo matrimonial) quando no Estado-Membro requerido já se decretou o divórcio entre as mesmas partes.

Quando a decisão não tenha sido proferida por um tribunal do Estado-Membro requerido, esta só constitui fundamento de recusa se, adicionalmente, for anterior à decisão proferida no Estado-Membro de origem e estiver em condições de ser reconhecida no Estado-Membro requerido. Estes requisitos adicionais justificam-se porque, nestes casos, as decisões irreconciliáveis foram ambas proferidas por tribunais de outros Estados que não o Estado-Membro requerido.
As decisões proferidas noutro Estado-Membro  ou num Estado terceiro encontram-se assim sujeitas a um princípio de prioridade da decisão mais antiga. O segundo requisito adicional compreende-se uma vez que estamos perante uma decisão estrangeira, a qual, por si só, não produz efeitos no território do Estado-Membro requerido. É através do reconhecimento que é atribuído à decisão estrangeira o mesmo valor que tem uma decisão interna. A expressão “condições necessárias para o seu reconhecimento no Estado-Membro requerido” remete para o Direito do Reconhecimento vigente no Estado-Membro requerido, independentemente da sua fonte. Quando Portugal seja o Estado-Membro requerido relevam, primacialmente, o regime de reconhecimento de decisões estrangeiras da Convenção da Haia de 1970[fn:39] e o de fonte interna[fn:38].

Por fim, salienta-se que não é necessário que a decisão tenha sido já objeto de reconhecimento. O que é necessário é que a decisão proferida num Estado terceiro tenha condições de ser reconhecida no Estado-Membro requerido. Ou seja, compete ao tribunal do Estado-Membro requerido a quem foi solicitado o reconhecimento, a título principal ou incidental, da decisão proferida no Estado-Membro de origem verificar se existe alguma circunstância que impeça o reconhecimento da decisão proferida no Estado terceiro segundo a lei do foro. Caso não exista, a decisão proferida no Estado terceiro reúne as condições necessárias para o seu reconhecimento.

* III. Reconhecimento de atos autênticos e acordos em matéria matrimonial

Em matéria matrimonial, o reconhecimento de atos autênticos e acordos registados é a principal novidade do Regulamento Bruxelas II /ter/. Este novo regime de reconhecimento visa incluir no âmbito do Regulamento, respondendo assim a um fenómeno de "desjudicialização" do divórcio que ocorreu na União Europeia[@shuilleabhain2021, pp. 120-121, informa que é possível obter um divórcio extrajudicial em Bélgica, Espanha, Eslóvenia, Estónia, França, Grécia, Itália, Letónia, Portugal e Roménia;. Uma breve comparação dos direitos materiais destes Estados pode encontrar-se em @lazic2021, pp. 160 e ss..].

Alguns destes divórcios extrajudiciais eram enquadráveis no regime de reconhecimento de decisões do Regulamento Bruxelas II /bis/, pois a autoridade que neles intervinha era subsumível ao conceito de tribunal do Regulamento. A questão era, no entanto, controversa na doutrina[Cf. @almeida2017, pp. 47 e ss.]. As dúvidas mantiveram-se quando o Tribunal de Justiça considerou que o Regulamento Roma III[fn:56] e o Regulamento Bruxelas II /bis/ visavam apenas os divórcios decretados quer por um tribunal estatal quer por uma autoridade pública ou sob seu controlo[fn:57].

O Regulamento Bruxelas II /ter/ visa ultrapassar estas dúvidas, introduzindo um regime de reconhecimento aplicável aos divórcios extrajudiciais. Porém, ao não definir o conceito de "divórcio privado", subsistem dúvidas de enquadramento.  Alguns autores definem "divórcios privados" como aqueles em que não há uma intervenção /constitutiva/ de uma autoridade[Cf., neste sentido, @gonzalezbeilfuss2020, p. 312; @gonzalezbeilfuss2021a, p. 97; e @kramme2021, p. 101; @lazic2021, pp. 165-166, parecem preferir distinguir os divórcios privados pelo documento em que são vertidos ou registados.]. Pela nossa parte preferimos distinguir recorrendo ao conceito de autoridade. No âmbito de aplicação material do Regulamento Bruxelas II /ter/ incluem-se agora, adicionalmente, divórcios e separações judiciais em que há uma intervenção de uma autoridade (seja ela constitutiva ou não); os divórcios /puramente/ privados, isto é, os divórcios efetuados sem necessidade da presença de qualquer autoridade, continuam excluídos do âmbito de aplicação material do Regulamento. Não obstante, permanecem dúvidas de enquadramento de divórcios proferidos por autoridades não jurisdicionais: deve, por exemplo, o divórcio ou separação judicial decretada pelo conservador do registo civil português ser enquadrado no regime de reconhecimento de decisões (como era no Regulamento Bruxelas II /bis/) ou no novo regime de reconhecimento de atos autênticos e acordos registados[Cf., em sentido semelhante, @gonzalezbeilfuss2021a, p. 103, que adverte que distinguir entre decisões e atos autênticos não será fácil.]?

Este novo regime segue de perto o regime de reconhecimento das decisões, como se deduz da remissão para os artigos 30.º a 41.º, em tudo o que não for diversamente estabelecido nos artigo  64.º a 68.º[fn:63]. Não obstante introduz dois novos pressupostos de reconhecimento, a saber: /(i)/ o ato autêntico foi exarado ou o acordo foi registado num Estado cujos tribunais teriam competência internacional nos termos do capítulo II (artigos 3.º a 6.º do Regulamento Bruxelas II /ter/)[fn:58]; e /(ii)/ o ato autêntico e o acordo registado tem efeito jurídico vinculativo no Estado-Membro de origem[fn:59] [@lazic2021, p. 167, consideram que existe uma terceira condição: a comunicação, prevista no artigo 103.º do Regulamento, pelo respetivo Estado-Membro de que aquela autoridade pode decretar divórcios (ou separações judiciais); e, aparentemente no mesmo sentido, @gonzalezbeilfuss2021a, p. 101. Sem contestar que a comunicação dá um elevado grau de certeza, entende-se que mesmo que esta não seja feita, se poderá continuar a aplicar o regime de reconhecimento.].

O primeiro pressuposto redunda no controlo da competência da autoridade de origem. Não sendo órgãos jurisdicionais, podem estas autoridades considerar que não estão vinculadas às normas atributivas de competência internacional do Regulamento Bruxelas II /ter/. Deste modo, e ao abrigo do princípio da livre escolha de notário, poderia o notário francês decretar o divórcio de dois cônjuges nacionais portugueses, com residência habitual na Alemanha quando, segundo o Regulamento, os tribunais franceses seriam internacionalmente incompetentes. Para evitar, pensa-se, este /forum shopping/ da autoridade não jurisdicional, o Regulamento Bruxelas II /ter/ estabelece como pressuposto que os atos autênticos e os acordos registados em matéria de divórcio e separação judicial só beneficiam do regime de reconhecimento nos casos em que o tenham sido exarados ou registado num Estado-Membros cujos tribunais seriam internacionalmente competentes para decretar esse mesmo divórcio ou separação judicial. Concorda-se com esta solução pois entende-se, como se referiu /supra/, que a proibição do controlo da competência do tribunal ou autoridade de origem se justifica à luz do princípio da confiança mútua num contexto de uniformização das normas de competência internacional, especialmente atendendo que não é admitida a celebração de pactos de jurisdição[Cf., discordando da solução adotada, @shuilleabhain2021, p. 122.].

O segundo pressuposto é o de que o ato autêntico ou o acordo registado produz, no Estado-Membro de origem, o efeito jurídico de dissolução ou enfraquecimento do vínculo matrimonial.

Estes pressupostos são controlados pelo Estado-Membro de origem. Compete ao tribunal ou autoridade competente emitir uma certidão para o ato autêntico ou acordo, mas essa certidão só deve ser emitida depois de verificado que /(i)/ os tribunais do Estado-Membro de origem seriam internacionalmente competentes para decretar o divórcio ou separação judicial nos termos dos artigos 3.º a 6.º do Regulamento Bruxelas II /ter/; e /(ii)/ o ato autêntico ou acordo registado é apto a produzir o efeito jurídico de dissolução ou enfraquecimento do casamento, segundo o Direito do Estado-Membro de origem[fn:60]. A certidão é /conditio sine qua non/ para o reconhecimento automático[fn:61]. A certidão só pode ser impugnada (em virtude de erro material ou erro na verificação dos pressupostos) no Estado-Membro de origem[fn:62].

Por fim, os fundamentos de recusa são ligeiramente diferentes. Elimina-se, por razões óbvias, o fundamento de recusa assente na não citação ou notificação do ato introdutório da instância ou ato equivalente à parte revel. No mais, são idênticos, pelo que se remete para o que se disse /supra/.

* IV. Conclusão

Terminado este breve excurso sobre os regimes de reconhecimento do Regulamento Bruxelas II /ter/ em matéria matrimonial, é o momento de efetuar uma brevíssima apreciação. O Regulamento Bruxelas II /ter/ é, no essencial, uma instrumento de continuidade. O considerando 90 estabelece que deve ser assegurada a continuidade entre a Convenção de Bruxelas II, o Regulamento Bruxelas II, o Regulamento Bruxelas II /bis/ e o Regulamento Bruxelas II /ter/ "na medida em que as disposições se tenham mantido inalteradas". É o caso da maioria das normas de reconhecimento em matéria matrimonial, apesar de se terem efetuado algumas precisões de linguagem e adotado redações mais próximas das do Regulamento Bruxelas I /bis/. A grande inovação é o novo regime de reconhecimento de atos autênticos e acordos em matéria matrimonial. Este novo regime acolhe melhor, e de forma mais abrangente, o fenómeno de "desjudicialização" do divórcio (e da separação judicial) que tem ocorrido, nos últimos anos, em vários Estados-Membros. O regime gizado, que não deixa de ter pontos de contacto significativos com o regime de reconhecimento de decisões em matéria matrimonial, parece-nos ser um bom compromisso. Em particular concorda-se com a consagração do controlo da competência da autoridade de origem, uma vez que as autoridades que participam nestes divórcios e separações judiciais podem, nalguns casos, não estar vinculadas a aplicar as regras uniformes em matéria de competência internacional estabelecidas pelo Regulamento Bruxelas II /ter/.

* Footnotes

[fn:75] Regulamento (CE) n.º 2201/2003 do Conselho, de 27 de Novembro de 2003, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e que revoga o Regulamento (CE) n.º 1347/2000, publicado no JO L 338, de 23 de dezembro de 2003.

[fn:74] Regulamento (UE) 2019/1111 do Conselho, de 25 de junho de 2019, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e ao rapto internacional de crianças (reformulação), publicado no Jornal Oficial (JO) L 178, de 2 de julho de 2019.

[fn:64] A única exceção, prevista no artigo 73.º do Regulamento Bruxelas II /ter/, é a execução da decisão de custas relativas a ações matrimoniais.

[fn:63] Cf. artigo 65.º, segundo período, do Regulamento Bruxelas II /ter/.

[fn:62] Cf. artigo 67.º do Regulamento Bruxelas II /ter/, em particular o seu n.º 3.

[fn:61] Cf. artigo 66.º, n.º 5, do Regulamento Bruxelas II /ter/.

[fn:60] Cf. artigo 66.º, n.º 2, do Regulamento Bruxelas II /ter/.

[fn:59] Cf. artigo 65.º do Regulamento Bruxelas II /ter/.

[fn:58] Cf. artigo 64.º do Regulamento Bruxelas II /ter/.

[fn:57] Acórdão de 20 de dezembro de 2017, /Sahyouni/, C-372/16, EU:C:2017:988, considerandos n.ºs 39 e 40.

[fn:56] Regulamento (UE) n.º 1259/2010 do Conselho, de 20 de Dezembro de 2010, que cria uma cooperação reforçada no domínio da lei aplicável em matéria de divórcio e separação judicial, publicado no JO L 343, de 29 de dezembro de 2010.

[fn:55] Cf. artigso 61.º, 62.º e 103.º, n.º 1, alínea /e)/, do Regulamento Bruxelas II /ter/.

[fn:54] Cf. artigo 60.º do Regulamento Bruxelas II /ter/.

[fn:53] Cf. artigo 59.º, n.º 6, do Regulamento Bruxelas II /ter/.

[fn:52] Cf. artigo 75.º, aplicável por remissão dos artigos 30.º, n.º 3, e 40.º, n.º 1, todos do Regulamento Bruxelas II /ter/.

[fn:51] Cf. artigo 74.º, n.º 1, do Regulamento Bruxelas II /ter/. O n.º 2 deste artigo estende este benefício aos casos em que o requerente tenha beneficiado de um processo gratuito perante uma autoridade administrativa.

[fn:50] Sobre estes, cf. a secção seguinte.

[fn:49] Cf. artigos 30.º, n.º 4, e 40.º, n.º 2, do Regulamento Bruxelas II /ter/.

[fn:48] Cf. artigo 103.º, n.º 1, alínea /c)/, do Regulamento Bruxelas II /ter/.

[fn:47] Neste sentido aponta o artigo 68.º do Regulamento Bruxelas II /ter/ onde não se verifica correspondente omissão e, sobretudo, o considerando n.º 70 "Os atos autênticos e os acordos entre as partes em matéria de separação e divórcio que tenham efeito jurídico vinculativo num Estado-Membro são equiparados a «decisões» para efeitos de aplicação das normas em matéria de reconhecimento".

[fn:46] Itálicos aditados.

[fn:45] Recorre-se a uma transliteração quando os campos de texto livre da certidão e a decisão está redigida numa língua que usa um alfabeto diferente (v.g. transliteração de certidão redigida em grego para português). As regras de tradução e transliteração encontram-se previstas no artigo 91.º do Regulamento Bruxelas II /ter/.

[fn:44] Cf. artigo 37.º do Regulamento Bruxelas II /ter/.

[fn:43] Cf. artigo 36.º, n.º 3, do Regulamento Bruxelas II /ter/.

[fn:42] Cf. corpo do artigo 36.º, n.º 1, do Regulamento Bruxelas II /ter/. Em regra, mas não obrigatoriamente, será competente o tribunal que proferiu a decisão que se pretende reconhecer.

[fn:41] Cf. artigo 31.º, n.º 1, alínea /a)/, do Regulamento Bruxelas II /ter/. A redação adotada teve a sua origem na Convenção de Bruxelas e é hoje comum à generalidade dos instrumentos de Direito do Reconhecimento da União Europeia.

[fn:40] No caso português, e atendendo ao artigo 984.º do Código de Processo Civil, dir-se-á que o fundamento assente na violação manifesta da ordem pública internacional é de conhecimento oficioso e os restantes carecem de alegação pelas partes, exceto se, do exame do processo ou por conhecimento derivado do exercício das suas funções, o tribunal apure que se verifica um desses fundamentos de recusa.

[fn:39] Convenção da Haia de 1970 sobre o Reconhecimento dos Divórcios e Separações de Pessoas.

[fn:38] Artigo 978.º e ss. do Código de Processo Civil.

[fn:37] Cf., no contexto das normas da Convenção de Bruxelas, o Acórdão do TJ de 4 de fevereiro de 1988, /Horst Ludwig Martin Hoffmann contra Adelheid Krieg/, 145/86, EU:C:1988:61, considerando n.º 22.

[fn:36] Artigo 38.º, alínea /d)/, do Regulamento Bruxelas II /ter/.

[fn:35] O TJ esclareceu, em sede do Regulamento Bruxelas I, que este fundamento de recusa é inaplicável quando decisões incompatíveis sejam proferidas por tribunais do mesmo Estado-Membro (Acórdão de 26 de setembro de 2013, /Salzgitter Mannesmann Handel/, C-157/12, EU:C:2013:597, considerandos n.º 35 e ss. e parte decisória).

[fn:34] Artigo 38.º, alínea /c)/, do Regulamento Bruxelas II /ter/.

[fn:33] Um exemplo, poderá ser a citação do cônjuge requerido que reside habitualmente num Estado-Membro que não é o Estado-Membro de origem, sem que os documentos estejam redigidos ou sejam acompanhados de uma tradução numa das línguas permitidas pelo artigo 8.º do Regulamento (CE) n.º 1393/2007 do Parlamento Europeu e do Conselho, de 13 de novembro de 2007, relativo à citação e à notificação dos atos judiciais e extrajudiciais em matérias civil e comercial nos Estados-Membros (citação e notificação de atos), publicado no JO L 324, de 10 de dezembro de 2007, ou pelo artigo 12.º do Regulamento (UE) 2020/1784 do Parlamento Europeu e do Conselho de 25 de novembro de 2020 relativo à citação ou notificação de atos judiciais e extrajudiciais em matérias civil e comercial nos Estados-Membros (citação ou notificação de atos) (reformulação), publicado no JO L 405, de 2 de dezembro de 2020, aplicável a partir de 1 de julho de 2022.

[fn:32] Acórdão do TJ de 11 de junho de 1985, /Leon Emile Gaston Carlos Debaecker e Berthe Plouvier contra Cornelis Gerrit Bouwman/, 49/84, EU:C:1985:252, considerando n.º 27.

[fn:31] Acordão de 16 de junho de 1981, /Peter Klomps contra Karl Michel/, 166/80, EU:C:1981:137, considerando n.º 10.

[fn:30] Acordão de 16 de junho de 1981, /Peter Klomps contra Karl Michel/, 166/80, EU:C:1981:137, considerandos n.ºs 19 e 20. Assinala-se ainda que o tribunal do Estado-Membro requerido deve verificar, no caso concreto, se existem circunstâncias excecionais que justifiquem uma solução diversa. Para efetuar essa determinação, o tribunal do Estado-Membro requerido pode tomar em consideração todas as circunstâncias do caso, e em particular, o modo como foi efetuada a citação.

[fn:29] Artigo 38.º, alínea /b)/, do Regulamento Bruxelas II /ter/.

[fn:28] Acórdãos do TJ de 28 de março de 2000, /Krombach/, C-7/98, EU:C:2000:164, considerando n.º 37.

[fn:27] Artigo 38.º, alínea /a)/, do Regulamento Bruxelas II /ter/.

[fn:26] O Acórdão do Tribunal da Relação do Porto de 9 de fevereiro de 2009, proc. 0825474, é ilustrativo desta situação. O ex-cônjuge marido requereu junto do Tribunal da Relação do Porto o reconhecimento da decisão alemã que decretou o divórcio entre ele e a sua ex-mulher. O Tribunal da Relação do Porto considerou-se oficiosamente absolutamente incompetente em razão da hierarquia, pois a competência para o processo de declaração judicial de reconhecimento foi cometida aos tribunais de comarca e, em consequência, absolveu à ré da instância.

[fn:25] Exemplificando, o tribunal português não deve reconhecer, segundo o regime de reconhecimento do Regulamento Bruxelas II /ter/, uma decisão proferida noutro Estado-Membro que declara que A. é filha de B..

[fn:24] Cf. Acórdão de 16 de janeiro de 2019, /Liberato/, C‑386/17, EU:C:2019:24, considerandos n.º 46 e 55.

[fn:23] Cf. considerando n.º 55 do Regulamento Bruxelas II /ter/.

[fn:22] Cf., em sede da Convenção de Bruxelas, os Acórdãos do TJ de 28 de março de 2000, /Krombach/, C-7/98, EU:C:2000:164, considerando n.º 36 e de 11 de maio de 2000, /Renault/, C-38/98, EU:C:2000:225, considerando n.º 29. Em sede de Regulamento Bruxelas II /bis/, cf. Acórdão de 16 de janeiro de 2019, /Liberato/, C‑386/17, EU:C:2019:24, considerando n.º 54.

[fn:21] Cf. Acórdão do TJ de 16 de janeiro de 2019, /Liberato/, C‑386/17, EU:C:2019:24, considerando n.º 52 e parte decisória.

[fn:20] Correspondente ao artigo 25.º do Regulamento Bruxelas II /bis/.

[fn:19] Correspondente ao artigo 26.º do Regulamento Bruxelas II /bis/.

[fn:18] Sobre este preceito cf. o nosso artigo mencionada na nota 1.

[fn:17] A fundamentação da proibição do controlo da competência do tribunal de origem com base no princípio da confiança mútua, unificação (quase integral) das normas de competência internacional e no controlo da competência apenas pelos tribunais do Estado-Membro do foro parece ter sido perfilhada pelo TJ, em sede de Regulamento Bruxelas II /bis/, no Acórdão de 15 de julho de 2010, /Purrucker/, C-256/09, EU:C:2010:437, considerandos n.ºs 72 a 75. Apesar de o Acórdão ter sido proferido em matéria de responsabilidade parental, não existem particularidades que impeçam a sua transposição para as ações matrimoniais.

[fn:16] Cf. artigo 6.º do Regulamento Bruxelas II /ter/.

[fn:15] Cf. considerandos n.ºs 54 e 55 do Regulamento Bruxelas II /ter/.

[fn:14] Por exemplo, nos casos em que a autoridade pública considere verificado um dos fundamentos de não reconhecimento da decisão estrangeira.

[fn:12] Cf. artigos 36.º, n.º 2, e 45.º, n.º 4, do Regulamento Bruxelas I /bis/.

[fn:11] Artigo 91.º do Código de Processo Civil (CPC).

[fn:10] Imagine-se, por exemplo, que A., depois de obter decisão de divórcio num outro Estado-Membro que dissolveu o seu casamento com B., casa em Portugal com C. D. (pai de C.) intenta ação de anulação do casamento em Portugal, com fundamento em casamento anterior não dissolvido.

[fn:9] Pense-se, por exemplo, na situação em que um ex-cônjuge (em virtude de um decisão de divórcio proferida num outro Estado-Membro) se apresenta num processo de inventário a correr termos em Portugal, alegando ser herdeiro legitimário do autor da sucessão (o anterior cônjuge).

[fn:8] Cf. considerando n.º 54 do Regulamento Bruxelas II /ter/.

[fn:7] Cf. artigo 14.º, n.º 1, da Convenção relativa à competência, ao reconhecimento e à execução de decisões em matéria matrimonial, publicada no JO C 221, de 16 de julho de 1998 (doravante Convenção de Bruxelas II), artigo 14.º, n.º 1, do Regulamento (CE) n.º 1347/2000 do Conselho, de 29 de Maio de 2000, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e de regulação do poder paternal em relação a filhos comuns do casal, publicado no JO L 160, de 30 de junho de 2000 (doravante Regulamento Bruxelas II) e artigo 21.º, n.º 1, do Regulamento Bruxelas II /bis/.

[fn:6] Esta possibilidade de suspensão da instância surge apenas quando for requerido o não reconhecimento da decisão estrangeira ou quando o reconhecimento da decisão for invocado a título incidental.

[fn:5] Cf. artigo 100.º do Regulamento Bruxelas II /ter/.

[fn:4] Cf., neste sentido, o último período do considerando n.º 9 do Regulamento Bruxelas II /ter/.

[fn:3] As versões inglesa ("including a decree, order or judgment, /granting/ divorce, legal separation, or annulment of a marriage,"), francesa ("y compris un arrêt, un jugement ou une ordonnance, /accordant/ le divorce, la séparation de corps ou l’annulation d’un mariage"), espanhola ("en particular un fallo, una orden o una resolución que conceda el divorcio, la separación legal, la nulidad matrimonial"), italiana ("inclusi un decreto, un’ordinanza o una sentenza, /che sancisca/ il divorzio, la separazione personale dei coniugi, l’annullamento del matrimonio") e alemã ("einschließlich einer Verfügung, eines Beschlusses oder eines Urteils, mit der die Ehescheidung, die Trennung ohne Auflösung des Ehebandes oder die Ungültigerklärung einer Ehe /ausgesprochen wird/") apontam no mesmo sentido. Itálicos aditados.

[fn:2] Cf. considerando n.º 9 do Regulamento Bruxelas II /ter/.

[fn:1] Sobre este cf. o nosso outro artigo nesta revista "Âmbito de aplicação, definições e relações com outros atos do Regulamento Bruxelas II /ter/".
