#+TITLE: Âmbito de aplicação, definições e relações com outros atos do Regulamento Bruxelas II /ter/
#+AUTHOR: João Gomes de Almeida

* Introdução



* Âmbito de aplicação
** Em razão do espaço (ou a transnacionalidade da situação)

As normas do Regulamento Bruxelas II /ter/ só são aplicáveis quando a situação tenha um elemento de estraneidade. Esta entendimento - que não tinha uma consagração clara no Regulamento Bruxelas II /bis/[Sobre a questão neste Regulamento, cf. @almeida2017, pp. 71 e ss.] - pode encontrar-se hoje nos considerandos (2) a (4) do Regulamento Bruxelas II /ter/[fn:1] e é o único conforme à base habilitante do Regulamento Bruxelas II /ter/, o artigo 81.º, n.º 3, do Tratado sobre o Funcionamento da União Europeia[fn:2].

As normas do Regulamento Bruxelas II /ter/ não são, por isso, aplicáveis aos litígios emergentes de situações puramente internas, isto é, situações que só possuem pontos de contacto relevantes com um único Estado soberano.

O Regulamento Bruxelas II /ter/ é um regulamento /duplo/, no sentido em que estabelece regras de competência internacional e de reconhecimento e execução. Quanto a estas últimas, assinala-se que o elemento de estraneidade pode surgir /depois/ de proferida a decisão, exarado o ato autêntico ou celebrado o acordo. Veja-se o seguinte exemplo: A. e B., são franceses, com residência habitual em França, e casados entre si. É proferida decisão de divórcio por um tribunal francês. B. muda a sua residência habitual para Portugal e, em setembro de 2022, pretende casar com C. O reconhecimento (automático) da decisão francesa de divórcio é regido pelo Regulamento Bruxelas II /ter/, pois, no momento do reconhecimento, a situação já possui um elemento de estraneidade.

** Em razão do território

Através do âmbito de aplicação em razão do território pretende-se delimitar a aplicabilidade do Regulamento Bruxelas II /ter/. Muitas vezes abordado aquando da análise do âmbito de aplicação em razão do espaço[Cf., em sede de Regulamento Bruxelas II /bis/, @brito2005a, p. 134.], uma primeira aproximação decorre das normas do Tratado da União Europeia (TUE) e do TFUE.

Assim, e nos termos do artigo 288.º do TFUE, o Regulamento Bruxelas II /ter/ “[é] obrigatório em todos os seus elementos e diretamente aplicável em todos os Estados-Membros”. Há, porém, que ter em atenção o Protocolo (N.º 21) relativo à posição do Reino Unido e da Irlanda em relação ao espaço de liberdade, segurança e justiça e o Protocolo (N.º 22) relativo à posição da Dinamarca. Ambos os protocolos estabelecem que os instrumentos de direito derivado da União Europeia, aprovados em aplicação do Título V do Parte III do TFUE, não vinculam /ope iuris/ o Reino Unido, a Irlanda e a Dinamarca, tendo estes Estados-Membros o direito de optar pela participação, ou não, nestes instrumentos de direito derivado da União Europeia.

À semelhança do que tinha sucedido no processo de adoção do Regulamento Bruxelas II /bis/, também no Regulamento Bruxelas II /ter/ se verifica que o Reino Unido[fn:4] e a Irlanda “(...) notificaram a sua intenção de participar na adoção e na aplicação do presente regulamento”[fn:3], pelo que o mesmo lhes é aplicável. O mesmo não sucedeu com a Dinamarca, razão pela qual a mesma não fica vinculada nem sujeita à aplicação do Regulamento Bruxelas II /ter/[fn:5].

Desta primeira aproximação resulta que o Regulamento Bruxelas é obrigatório e diretamente aplicável em todos os Estados-Membros, com exceção da Dinamarca. Aprofundando a análise, é possível inferir do artigo 52.º do TUE e do artigo 355.º do TFUE que o Regulamento Bruxelas II /ter/ não será aplicável na totalidade do territórios dos Estados-Membros a ele vinculados. O Regulamento Bruxelas II /ter/ não é aplicável aos países e territórios não europeus que mantêm relações especiais com a França e os Países Baixos[fn:6], nem aos Estados independentes do Principado do Mónaco, Principado de Andorra, São Marino e Vaticano[Cf. @magnus2012, pp. 22-27.] [fn:7].

** Em razão do tempo

O Regulamento Bruxelas II /ter/ distingue, no seu artigo 105.º, entre a data de entrada em vigor (n.º 1) e a data de aplicação das suas normas (n.º 2). O Regulamento entrou em vigor no dia 22 de julho de 2019 e as suas normas são aplicáveis a partir de 1 de agosto de 2022, com exceção dos artigos 92.º, 93.º e 103.º, que são aplicáveis a partir de 22 de julho de 2019[fn:10].

O Tribunal de Justiça da União Europeia[fn:8] teve oportunidade de analisar esta distinção, em sede do Regulamento Roma II, no Acórdão de 17 de novembro de 2011, proc. C-412/10, /Deo Antoine Homawoo contra GMF Assurances SA/, EU:C:2011:747. No entender do TJ “(...) é legítimo que o legislador distinga a data de entrada em vigor da data de aplicação do texto por ele adoptado, atrasando a segunda relativamente à primeira. Uma vez o ato entrado em vigor e, portanto, integrado na ordem jurídica da União, tal procedimento pode permitir, designadamente, que os Estados-Membros ou as instituições da União dêem cumprimento, com fundamento nesse acto, às obrigações prévias que lhes incumbem e que se revelam indispensáveis à sua plena aplicação ulterior a todos os sujeitos de direito que abrange”[fn:9].

O âmbito de aplicação em razão do tempo é próximo, mas não se confunde com a data de aplicação das normas do Regulamento. Como se depreende do artigo 100.º, n.º 1, o âmbito de aplicação em razão do tempo do Regulamento Bruxelas II /ter/ estará preenchido quando determinado ato jurídico relevante ocorre a partir de 1 de agosto de 2022. Assim, o âmbito de aplicação em razão do tempo estará preenchido quando a ação seja instaurada[Sobre a determinação do momento em que o processo foi instaurado cf., neste número da Revista, o artigo da Professora Doutora Elsa Dias Oliveira e, em sede de Regulamento Bruxelas II /bis/, @almeida2017, pp. 215 e ss.], o ato autêntico seja exarado ou o acordo seja registado a partir de 1 de agosto de 2022. Assim, e por exemplo, se, no dia 10 de outubro de 2022, é pedido em Portugal o reconhecimento de uma decisão espanhola em matéria de responsabilidade parental proferida no dia 1 de setembro de 2022, na sequência de processo instaurado em 20 de julho de 2022, não serão aplicáveis as regras de reconhecimento do Regulamento Bruxelas II /ter/, mas sim as do Bruxelas II /bis/, como resulta do artigo 100.º, n.º 2, do Regulamento Bruxelas II /ter/.

O âmbito de aplicação em razão do tempo deve, assim, ser também articulado com a norma revogatória prevista no artigo 104.º do Regulamento Bruxelas II /ter/[fn:13]. Apesar de o Regulamento Bruxelas II /ter/ revogar o Regulamento Bruxelas II /bis/ com efeitos a partir de 1 de agosto de 2022[fn:11], as normas deste último Regulamento continuam a aplicar-se sempre que a ação tenha sido instaurada, o ato autêntico exarado e o acordo registado antes de 1 de agosto de 2022[fn:12].

Por fim, o artigo 104.º, n.º 2, é uma norma de cariz eminentemente prático que ordena o aplicador e o interprete entenderem quaisquer remissões efetuadas para normas do Regulamento Bruxelas II /bis/ como remissões para as normas correspondentes do Regulamento Bruxelas II /ter/, determinadas de acordo com a tabela de correspondência /oficial/ constante do anexo X deste útlimo Regulamento. Assinala-se que as remissões podem constar de instrumentos normativos de Direito da União Europeia ou de fonte interna[Cf., neste sentido e sede de Regulamento Bruxelas II /bis/, @magnus2012, p. 470.]. Atendendo ao período de aplicabilidade das normas do Regulamento Bruxelas II /bis/ (de 1 de março de 2005 a 31 de julho de 2022), é expectável que haja um número significativo de remissões[fn:14].

** Em razão da matéria

Comentar o art. 1.º

* Definições

Comentar artigo 2.º

* Relações com outros atos

O Capítulo VIII (arts. 94.º a 99.º) do Regulamento Bruxelas II /ter/ regula as relações deste com outros instrumentos de fonte supraestadual. Na análise que se segue, adota-se a perspetiva do ordenamento jurídico português, dando maior enfoque às normas deste Capítulo que são (mais) relevantes para os intérprete e aplicadores do direito que atuam no ordenamento jurídico português. Assinala-se ainda que as normas do Capítulo VIII são, em termos substantivos e no geral, próximas das normas correspondentes nos instrumentos que o antecederam (Regulamento Bruxelas II /bis/, Regulamento Bruxelas II[fn:15] e Convenção de Bruxelas II[fn:16]).

No artigo 94.º, n.º 1, do Regulamento Bruxelas II /ter/ encontramos a norma geral: o Regulamento Bruxelas II /ter/ prevalece sobre e substitui as convenções (bilaterais e multilaterais) existentes entre Estados-Membros com âmbito de aplicação em razão da matéria (pelo menos parcialmente) coincidente. A génese desta norma encontra-se no artigo 38.º da Convenção de Bruxelas II e a sua redação é praticamente idêntica à do artigo 59.º, n.º 1, do Regulamento Bruxelas II /bis/[fn:17]. A norma assenta em três distinções, a saber: uma de cariz material, uma de cariz temporal e outra de cariz subjetivo.

A primeira distinção, de cariz material, delimita a aplicabilidade do preceito às convenções “relativas a matérias reguladas pelo presente regulamento”. Esta distinção é de fácil compreensão, uma vez que apenas havendo coincidência no âmbito de aplicação material dos dois instrumentos se coloca um problema de sobreposição de fontes normativas.

A segunda distinção, assente num critério temporal, delimita a aplicação da norma às “(...) convenções existentes à data da entrada em vigor do Regulamento (CE) n.º 2201/2003 (...)”, ou seja, 1 de março de 2005. Este critério temporal é compreensível pois considera-se que os Estados-Membros, a partir da data de entrada em vigor do Regulamento Bruxelas II /bis/, deixaram de ter competência para concluírem convenções internacionais com Estados que incidam sobre o âmbito de aplicação material do Regulamento, nos termos do n.º 2 do artigo 3.º do TFUE e da construção jurisprudencial do TJ[fn:18].

A terceira e última distinção assenta num critério subjetivo e delimita a aplicabilidade do preceito às convenções “celebradas entre dois ou mais Estados-Membros”. As normas das convenções são substituídas pelas normas do Regulamento Bruxelas II /ter/ quando /apenas/ Estados-Membros da União Europeia (vinculados ao Regulamento) sejam Estados Contratantes das convenções.

Os restantes números do artigo 94.º referem-se ao compromisso político gizado com os países nórdicos. O Regulamento Bruxelas II /bis/ concedeu à Finlândia e à Suécia a possibilidade de declarar que a Convenção de 6 de fevereiro de 1931 entre a Dinamarca, a Finlândia, a Islândia, a Noruega e a Suécia relativa às disposições de Direito Internacional Privado em matéria de casamento, adoção e guarda de menores e o respetivo protocolo final prevalecia sobre o Regulamento Bruxelas II /bis/, no todo ou em parte, nas relações entre esses Estados. A Finlândia e a Suécia fizeram tal declaração[fn:19]. Esse compromisso é mantido no Regulamento Bruxelas II /ter/.

O artigo 94.º, n.º 5, do Regulamento Bruxelas II /ter/ tem particular interesse para os intérpretes e órgãos de aplicação do Direito portugueses. Aí se estabelece que as decisões proferidas pelos tribunais da Finlândia e da Suécia /beneficiam/ do regime de reconhecimento e execução previsto no Regulamento Bruxelas II /ter/ desde que a decisão tenha sido proferida "(...) ao abrigo de um critério de competência que corresponda a um dos previstos no capítulo II". Introduz-se, assim, um controlo da competência do tribunal de origem, em regra proíbido[fn:20]. Não é obrigatório que o tribunal indique expressamente, na decisão a reconhecer, o critério de competência em que se fundou[Cf., neste sentido, @magnus2012, p. 426 e, por analogia, o Acórdão do TJ de 15 de julho de 2010, /Bianca Purrucker contra Guillermo Vallés Pérez/, C-256/09, EU:C:2010:437]. Nem nos parece que seja necessário que o concreto critério de competência utilizado para proferir a decisão corresponda a um dos consagrados no Regulamento Bruxelas II /ter/, bastando que seja possível verificar - da análise da decisão - que um dos critérios consagrados no Regulamento Bruxelas II /ter/ se encontra preenchido[fn:21].

O artigo 95.º regula as relações entre o Regulamento Bruxelas II /ter/ e quatro convenções multilaterais, duas em matéria matrimonial[fn:22] e duas em matéria de responsabilidade parental[fn:23]. O Estado Português vinculou-se internacionalmente a três destas convenções, não sendo Estado Contratante da Convenção do Luxemburgo, de 8 de setembro de 1967, sobre o reconhecimento das decisões relativas ao vínculo conjugal.

O artigo 95.º estabelece que nas relações entre dois (ou mais) Estados-Membros da União Europeia que sejam igualmente Estados Contratantes de uma destas convenções multilaterais prevalecem as regras do Regulamento Bruxelas II /ter/. Ou seja: as regras destas convenções multilaterais só são aplicáveis nas relações entre Estados-Membros da União Europeia e Estados terceiros que sejam Estados Contratantes de uma destas quatro convenções[Cf., neste sentido, @corneloup2013, p. 462.] [fn:24]. Esta solução não suscita dificuldades de maior pois as convenções preveem que outros instrumentos possam prevalecer sobre elas[Cf., neste sentido, @magnus2012, p. 428; e, referindo-se apenas à Convenção da Haia, de 1 de junho de 1970, sobre o reconhecimento dos divórcios e separações de pessoas e à Convenção do Luxemburgo, de 8 de setembro de 1967, sobre o reconhecimento das decisões relativas ao vínculo conjugal, @corneloup2018, pp. 465-466] [fn:25].

O artigo 96.º

Comentar artigos 94.º a 99.º

| Reg. BIIter | Reg. BIIbis          |       |
|-------------+----------------------+-------|
| 94.º        | 59.º                 | feito |
| 95.º        | 60.º/a), b), c) e d) | feito |
| 96.º        | 60.º/e)              |       |
| 97.º/1      | 61.º                 |       |
| 97.º/2      | sem correspondência  |       |
| 98.º        | 62.º                 |       |
| 99.º        | 63.º                 |       |


* Conclusão

* Footnotes

[fn:25] Cf. o artigo 13.º da  Convenção do Luxemburgo, de 8 de setembro de 1967, sobre o reconhecimento das decisões relativas ao vínculo conjugal, o artigo 18.º da Convenção da Haia, de 1 de junho de 1970, sobre o reconhecimento dos divórcios e separações de pessoas e os artigos 19.º e 20 da Convenção Europeia, de 20 de maio de 1980, sobre o reconhecimento e a execução das decisões relativas à custódia de menores e sobre o restabelecimento da custódia de menores. A questão poderia revestir maior complexidade no que se refere à Convenção da Haia, de 5 de outubro de 1961, relativa à competência das autoridades e à lei aplicável em matéria de proteção de menores, atendendo a que o seu artigo 18.º apenas salvaguarda outras convenções /anteriores/. Porém, atualmente, todos os Estados Contratantes desta Convenção são igualmente Estados Contratantes da Convenção da Haia de 1996 relativa à Competência, à Lei Aplicável, ao Reconhecimento, à Execução e à Cooperação em Matéria de Responsabilidade Parental e Medidas de Protecção das Crianças pelo que, nos termos do artigo 51.º desta Convenção, a Convenção da Haia de 1961 não tem hoje aplicação.

[fn:24] Veja-se, como exemplo, a Convenção da Haia, de 1 de junho de 1970, sobre o reconhecimento dos divórcios e separações de pessoas. Dos vinte Estados contratantes, doze são Estados-Membros da União Europeia. Assim, em Portugal, as regras desta Convenção só devem ser aplicadas pelos órgãos aplicadores do direito portugueses quando a decisão estrangeira a reconhecer tenha sido proferida num de 8 Estados Contratantes, a saber, Albânia, Austrália, China (mas apenas as decisões proferidas na região administrativa especial de Hong Kong), Dinamarca, Egito, Moldávia, Noruega, e Suíça.

[fn:23] A Convenção da Haia, de 5 de outubro de 1961, relativa à competência das autoridades e à lei aplicável em matéria de proteção de menores e a Convenção Europeia, de 20 de maio de 1980, sobre o reconhecimento e a execução das decisões relativas à custódia de menores e sobre o restabelecimento da custódia de menores.

[fn:22] A Convenção do Luxemburgo, de 8 de setembro de 1967, sobre o reconhecimento das decisões relativas ao vínculo conjugal e a Convenção da Haia, de 1 de junho de 1970, sobre o reconhecimento dos divórcios e separações de pessoas.

[fn:21] A questão não é muito relevante pois os critérios atributivos de competência internacional previstos na Convenção são bastante similares aos previsto no Regulamento Bruxelas II /ter/.

[fn:20] Cf. artigo 69.º do Regulamento Bruxelas II /ter/.

[fn:19] As declarações foram publicadas como Anexo IV do Regulamento Bruxelas II /bis/.

[fn:18] Cf. o Acórdão do TJ de 31 de março de 1971, proc. 22/70, /Comissão das Comunidades Europeias contra Conselho das Comunidades Europeias (AETR)/, EU:C:1971:32, considerandos n.ºs 17 e 18, o Parecer do TJ de 7 de fevereiro de 2006, Parecer 1/03, EU:C:2006:81, considerando n.º 116, e o Parecer do TJ de 14 de outubro de 2014, Parecer 1/13, EU:C:2014:2303, no qual este Tribunal voltou a afirmar, desta feita em sede do Regulamento Bruxelas II bis, que a “competência da União para celebrar acordos internacionais pode resultar não só de uma atribuição expressa conferida pelos Tratados mas também, implicitamente, de outras disposições dos Tratados e de atos adotados, no âmbito dessas disposições, pelas instituições da União. Em particular, sempre que o Direito da União confira às referidas instituições competências a nível interno, com vista a realizar um determinado objetivo, a União é investida da competência para assumir os compromissos internacionais necessários à realização desse objetivo, mesmo na falta de uma disposição expressa nesse sentido (parecer 1/03, EU:C:2006:81, n.º 114 e jurisprudência referida). Esta última hipótese está, de resto, prevista no artigo 216.º, n.º 1, TFUE” (cf. considerando n.º 67), tendo emitido parecer no sentido de que a “aceitação da adesão de um Estado terceiro à Convenção sobre os Aspetos Civis do Rapto Internacional de Crianças, celebrada em Haia, em 25 de outubro de 1980, é da competência exclusiva da União Europeia” (cf. conclusão do Parecer).

[fn:17] A única diferença de redação diz respeito ao modo como é fixado o momento relevante para apurar se uma determinada convenção é ou não existente. Ambos os Regulamentos fixam como momento relevante a data de entrada em vigor do Regulamento Bruxelas II /bis/ (1 de março de 2005). No artigo 59.º, n.º 1, do Regulamento Bruxelas II /bis/ é utilizada a expressão "(...) as convenções existentes à data da sua entrada em vigor (...)", enquanto que no Regulamento Bruxelas II /ter/ é usada a expressão "(...) as convenções existentes à data da entrada em vigor do Regulamento (CE) n.º 2201/2003 (...)".

[fn:16] Convenção relativa à competência, ao reconhecimento e à execução de decisões em matéria matrimonial, publicada no JO C 221/1, de 16 de julho de 1998.

[fn:15] Regulamento (CE) n.º 1347/2000 do Conselho de 29 de Maio de 2000
relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e de regulação do poder paternal em relação a filhos comuns do casal, publicado no JO L 160/19, de 30 de junho de 2000.

[fn:14] Sem qualquer pretensão de exaustividade, e limitando-nos aos instrumentos normativos de Direito da União Europeia, encontram-se remissões para as normas do Regulamento Bruxelas II /bis/: /(i)/ no artigo 20.º, n.º 1, da Directiva 2011/99/UE do Parlamento Europeu e do Conselho, de 13 de Dezembro de 2011, relativa à decisão europeia de protecção, publicada no Jornal Oficial da União Europeia (doravante JO) L 338, de 21 de dezembro de 2011, /(ii)/ no artigo 73.º, n.º 1, do Regulamento (CE) n.º 4/2009 do Conselho, de 18 de Dezembro de 2008, relativo à competência, à lei aplicável, ao reconhecimento e à execução das decisões e à cooperação em matéria de obrigações alimentares, publicado no JO L 7, de 10 de janeiro de 2009, /(iii)/ nos artigos 1.º, n.º 2, e 2.º, n.º 1, alínea /b)/, do Regulamento (CE) n.º 664/2009 do Conselho, de 7 de Julho de 2009, que estabelece um procedimento para a negociação e a celebração de acordos entre Estados-Membros e países terceiros relativamente à competência, ao reconhecimento e à execução de sentenças e decisões em matéria matrimonial, de responsabilidade parental e de obrigações de alimentos, bem como à lei aplicável em matéria de obrigações de alimentos, publicado no JO L 200, de 31 de julho de 2009, /(iv)/ no artigo 2.º do Regulamento (UE) n.º 1259/2010 do Conselho, de 20 de Dezembro de 2010, que cria uma cooperação reforçada no domínio da lei aplicável em matéria de divórcio e separação judicial, publicado no JO L 343 de 29 de dezembro de 2010, /(v)/ no artigo 2.º, n.º 3, do Regulamento (UE) n.º 606/2013 do Parlamento Europeu e do Conselho, de 12 de junho de 2013, relativo ao reconhecimento mútuo de medidas de proteção em matéria civil, publicado no JO L 181, de 29 de junho de 2013, e /(vi)/ no artigo 5.º do Regulamento (UE) 2016/1103 do Conselho, de 24 de junho de 2016, que implementa a cooperação reforçada no domínio da competência, da lei aplicável, do reconhecimento e da execução de decisões em matéria de regimes matrimoniais, publicado no JO L 183, de 8 de julho de 2016.

[fn:13] Norma substancialmente idêntica ao artigo 71.º do Regulamento Bruxelas II /bis/.

[fn:12] O que resulta do artigo 100.º, n.º 2, do Regulamento Bruxelas II /ter/ já analisado e é reforçado pela expressão "Sob reserva do artigo 100.o, n.o 2, do presente regulamento (...)" constante do início do artigo 104.º, n.º 1.

[fn:11] Cf. artigo 104.º, n.º 1, do Regulamento Bruxelas II /ter/.

[fn:10] A data de produção de efeitos destes três artigos coincide com a data de entrada em vigor. Tal justifica-se por razões diversas: os artigos 92.º e 93.º atribuem à Comissão Europeia o poder de adotar atos delegados no que respeita aos anexos do Regulamento, podendo haver interesse em que a Comissão Europeia possa exercer este poder ainda antes da data de aplicação do Regulamento; o artigo 103.º estabelece obrigações de informação aos Estados-Membros, relacionadas com a operacionalização do Regulamento, que deveriam ser comunicadas à Comissão Europeia até 23 de abril de 2021.

[fn:9] Cf. considerando n.º 24. O Advogado-Geral Paolo Mengozzi, nas suas conclusões apresentadas em 6 de setembro de 2011, neste processo, conclui no mesmo sentido, ao afirmar que “[o] legislador distingue a data de entrada em vigor da de aplicação nos regulamentos subsequentes no mesmo domínio, com prazos mais ou menos longos entre estas duas datas, que permitem que os Estados-Membros adoptem eventuais modificações do seu direito nacional antes de transmitirem à Comissão as informações requeridas especificadas no instrumento em questão. Estas informações são depois colocadas à disposição do público, geralmente através de publicação no /Jornal Oficial da União Europeia/” (cf. considerando n.º 22; itálicos no original).

[fn:8] Doravante TJ.

[fn:7] A relevância desta análise mais profunda pode ilustrar-se com o Acórdão do Tribunal da Relação de Lisboa de 10 de maio de 2011, proc. 1105/10.5TYRLSB-1. Foi intentada junto deste Tribunal ação de revisão de sentença estrangeira, pedindo que fosse revista e confirmada a sentença proferida em 11 de março de 2010 pelo Tribunal Real de Guernsey, transitada em julgada, que decretou a dissolução do casamento civil celebrado em 19/5/2006 entre  requerente e requerida. A ação foi intentada de acordo com o Direito de Reconhecimento de fonte interna. O Tribunal da Relação de Lisboa considerou-se hierarquicamente incompetente e absolveu a requerida da instância. Fundamentou esta decisão no facto de a decisão cujo reconhecimento se pedia ter sido proferida por um tribunal de um Estado-Membro após a data de entrada em vigor do Regulamento Bruxelas II /bis/, razão pela qual se aplicaria o regime de reconhecimento consagrado neste Regulamento. De acordo com esse regime, os tribunais competentes para os processos de reconhecimento autónomos são os tribunais de 1.ª instância e não os tribunais da relação, verificando-se assim, no entender do Tribunal da Relação de Lisboa uma incompetência em razão da hierarquia. Sucede porém que, por força do artigo 355.º, n.º 5, alínea /c)/, do TFUE, o Regulamento Bruxelas II /bis/ não é aplicável nas Ilhas Anglo-Normandas e a decisão cujo reconhecimento se pedia foi proferida por um tribunal de uma dessas Ilhas (Guernsey). Como tal, não era aplicável o regime de reconhecimento do Regulamento Bruxelas II /bis/, mas sim o regime da Convenção da Haia de 1970 sobre o Reconhecimento dos Divórcios e Separações de Pessoas.

[fn:6] Enunciados no Anexo II ao TFUE.

[fn:5] Cf. considerando (96).

[fn:4] Recorda-se, porém, que o Reino Unido, por via do /brexit/, deixou de ser Estado-Membro da União Europeia no dia 1 de janeiro de 2021. Como tal, o Regulamento Bruxelas II /ter/ não será aplicável ao Reino Unido.

[fn:3] Cf. considerando (95).

[fn:2] Estabelece o artigo 81.º, n.º 3, do Tratado sobre o Funcionamento da União Europeia (doravante TFUE) que: "Em derrogação do n.º 2, as medidas relativas ao direito da família /que tenham incidência transfronteiriça/ são estabelecidas pelo Conselho, deliberando de acordo com um processo legislativo especial. O Conselho delibera por unanimidade, após consulta ao Parlamento Europeu." (itálicos aditados).

[fn:1] Considerando (2): "O presente regulamento estabelece normas de competência uniformes em matéria de divórcio, separação ou anulação do casamento, bem como regras para dirimir litígios em matéria de responsabilidade parental /que impliquem um elemento internacional/. (...)"; considerando (3): "(...) A fim de alcançar esse objetivo, deverão ser reforçados os direitos das pessoas, em especial das crianças, no âmbito dos processos judiciais, de modo a facilitar a cooperação entre as autoridades judiciais e administrativas, assim como a execução das decisões judiciais em matéria de direito da família /que tenham implicações transfronteiriças/. (...)"; e considerando (4): "Para o efeito, a União deve adotar, nomeadamente, medidas no domínio da cooperação judiciária em matéria civil /com implicações transfronteiriças/ em especial quando tal for necessário para o bom funcionamento do mercado interno." (itálicos aditados).
