#+TITLE: O regime de reconhecimento em matéria matrimonial no Regulamento Bruxelas II /ter/
#+AUTHOR: João Gomes de Almeida
#+LANGUAGE: pt-PT

* Introdução
* Reconhecimento de decisões em matéria matrimonial
** Conceito de decisão

O conceito de decisão é a pedra de toque do regime de reconhecimento de decisões em matéria matrimonial e encontra-se definido como "uma decisão proferida por um tribunal de um Estado-Membro, incluindo qualquer acórdão, sentença ou despacho judicial que decreta o divórcio, a separação ou a anulação do casamento". Tata-se de um conceito /amplo/ que inclui quaisquer decisões que decretam o divórcio, a separação judicial ou a anulação do casamento, independentemente da sua designação no Estado-Membro de origem.

O regime de reconhecimento encontra-se limitado pelo âmbito de aplicação em razão da matéria do Regulamento Bruxelas II /ter/[fn:1]. Tendo presente que, relativamente às ações matrimoniais, o Regulamento visa unicamente a dissolução ou enfraquecimento do vínculo matrimonial[fn:2], é esse efeito que é objeto do regime de reconhecimento de decisões estrangeiras. As consequências que decorrem da dissolução do casamento, nomeadamente os efeitos patrimoniais, não podem ser objeto do regime de reconhecimento previsto no Regulamento Bruxelas II /ter/[Cf., neste sentido e em sede dos instrumentos precedentes, @almeida2017, p. 482; *Incluir LLP 2019 e MTS 2022*; e, na jurisprudência portuguesa, o Acórdão do Tribunal da Relação de Coimbra de 15 de março de 2008, proc. 225-C/1998.C1.].

A decisão tem de ser proferida por /um tribunal/ de /um Estado-Membro/. O Regulamento Bruxelas II /ter/ mantêm um conceito /amplo/ de tribunal, que abrange autoridade /não jurisdicionais/ como autoridades administrativas ou, como sucede nalguns Estados-Membros, os notários. Decisivo é que essas autoridades /não jurisdicionais/ tenham, no respetivo Estado-Membro, competência em matéria de ações matrimoniais ou em matéria relativa à responsabilidade parental. O conceito de Estado-Membro não é expressamente  definido, mas pode ser deduzido do âmbito de aplicação em razão do território e não inclui a Dinamarca. Às decisões proferidas por tribunais de Estados terceiros não é aplicável o regime de reconhecimento previsto no Regulamento Bruxelas II /ter/.

Salienta-se que a situação não carece de ser /transnacional/ à data em que é proferida a decisão, para esta beneficiar do regime de reconhecimento. Mesmo uma decisão proferida no âmbito de uma situação puramente interna pode beneficiar do regime de reconhecimento  do Regulamento Bruxelas II /ter/, caso, no futuro, venha a ser necessário o reconhecimento dessa decisão noutro Estado-Membro. Veja-se o seguinte exemplo: A. e B., são franceses, com residência habitual em França, e casados entre si. É proferida decisão de divórcio por um tribunal francês, na sequência de ação instaurada em setembro de 2022. Posteriormente, B. muda a sua residência habitual para Portugal e, em setembro de 2026, pretende casar com C. O reconhecimento (automático) da decisão francesa de divórcio é regido pelo Regulamento Bruxelas II /ter/, pois, no momento do reconhecimento, a situação já possui um elemento de estraneidade.

Não é igualmente necessário que a competência internacional do tribunal do Estado-Membro de origem tenha sido estabelecida de acordo com as normas atributivas de competência internacional do Regulamento Bruxelas II /ter/ (ou do Regulamento Bruxelas II /bis/ que o precedeu). As decisões que decretam o divórcio, separação judicial ou a anulação do casamento proferidas por tribunais cuja competência internacional foi estabelecida ao abrigo das competências residuais consagradas no artigo 6.º do Regulamento Bruxelas II /bis/ beneficiam do regime de reconhecimento de decisões estrangeiras. Tal pode deduzir-se da proibição de controlo de competência do tribunal de origem, pois mesmo nos casos em que a competência internacional do tribunal se funde numa competência exorbitante de fonte interna, tal não é fundamento de não reconhecimento dessa decisão.

Só beneficiam do regime de reconhecimento do Regulamento Bruxelas II /ter/ as decisões /que decretam o divórcio, a separação judicial ou a anulação do casamento/. Em sede do Regulamento Bruxelas II /bis/ uma das questões mais debatidas era a de saber se o regime de reconhecimento de decisões estrangeiras abrangia qualquer decisão proferida por um tribunal num Estado-Membro relativa ao divórcio, separação judicial ou anulação do casamento ou se, pelo contrário, abrangia apenas as decisões proferidas por um tribunal num Estado-Membro que decretam o divórcio, a separação judicial ou a anulação do casamento. A nova redação[fn:3] aponta de forma mais clara no sentido (já sufragado pela maioria da doutrina no âmbito do Regulamento Bruxelas II /bis/) de que apenas as decisões que decretam o divórcio, a separação ou a anulação do casamento beneficiam do regime de reconhecimento do Regulamento Bruxelas II /ter/[fn:4].

** Princípio do reconhecimento automático
** Limites ao reconhecimento
*** Proibição do controlo de competência do tribunal de origem
*** Proibição de controlo do mérito da decisão objeto de reconhecimento
*** Fundamentos de recusa
**** Considerações gerais
**** Ordem pública internacional
**** Garantia do direito de defesa
**** Incompatibilidade de decisões
* Reconhecimento de atos autênticos e acordos em material matrimonial
* Conclusões

* Artigos a comentar :no export:
- 30.º a 33.º
- 36.º a 37.º
- 38.º e 40.º
- 59.º a 62.º
- 64.º a 68.º
- 69.º a 75.º

| RBII /ter/ | RB II /bis/     | Observações |
|------------+-----------------+-------------|
| 30.º/1 e 2 | 21.º /1 e 2     |             |
| 30.º/3 e 4 | 21.º/3          |             |
| 30.º/5     | 21.º/4          |             |
| 31.º/1     | 37.º/1 e 45.º/1 |             |
| 31.º/2 e 3 | 45.º/2          |             |
| 32.º       | 38.º            |             |
| 33.º/a)    | 27.º/1          |             |
| 33.º/b)    | -               |             |
| 36.º       | 39.º            |             |
| 37.º       | 43.º            |             |
| 38.º       | 22.º            |             |
| 40.º       | -               |             |
| 59.º       | -               |             |
| 60.º       | -               |             |
| 61.º       | -               |             |
| 62.º       | -               |             |
| 64.º       | -               |             |
| 65.º       | 46.º            |             |
| 66.º       | -               |             |
| 67.º       | -               |             |
| 68.º       | -               |             |
| 69.º       | 24.º            |             |
| 70.º       | 25.º            |             |
| 71.º       | 26.º            |             |
| 72.º       | -               |             |
| 73.º       | 49.º            |             |
| 74.º/1     | 50.º            |             |
| 74.º/2     | -               |             |
| 75.º       | 51.º            |             |

* Footnotes

[fn:4] Cf., neste sentido, o último período do considerando n.º 9 do Regulamento Bruxelas II /ter/.

[fn:3] As versões inglesa ("including a decree, order or judgment, /granting/ divorce, legal separation, or annulment of a marriage,"), francesa ("y compris un arrêt, un jugement ou une ordonnance, /accordant/ le divorce, la séparation de corps ou l’annulation d’un mariage"), espanhola ("en particular un fallo, una orden o una resolución que conceda el divorcio, la separación legal, la nulidad matrimonial"), italiana ("inclusi un decreto, un’ordinanza o una sentenza, /che sancisca/ il divorzio, la separazione personale dei coniugi, l’annullamento del matrimonio") e alemã ("einschließlich einer Verfügung, eines Beschlusses oder eines Urteils, mit der die Ehescheidung, die Trennung ohne Auflösung des Ehebandes oder die Ungültigerklärung einer Ehe /ausgesprochen wird/") apontam no mesmo sentido. Itálicos aditados.

[fn:2] Cf. considerando n.º 9 do Regulamento Bruxelas II /ter/.

[fn:1] Sobre este cf. o nosso outro artigo nesta revista "Âmbito de aplicação, definições e relações com outros atos do Regulamento Bruxelas II /ter/".
