#+TITLE: Âmbito de aplicação, definições e relações com outros atos do Regulamento Bruxelas II /ter/
#+AUTHOR: João Gomes de Almeida

* I. Introdução
A generalidade das normas do Regulamento Bruxelas II /ter/[fn:74] serão aplicáveis a partir do dia 1 de agosto de 2022. Este Regulamento reformula e substitui o Regulamento Bruxelas II /bis/[fn:75], porventura o regulamento mais relevante em matéria de Direito Internacional Privado da família. Neste artigo, efetua-se um primeiro olhar sobre o âmbito de aplicação (II.), as definições (III.) e as relações deste Regulamento com outros atos supraestaduais (IV.).

* II. Âmbito de aplicação
** A) Em razão do espaço (ou a transnacionalidade da situação)

As normas do Regulamento Bruxelas II /ter/ só são aplicáveis quando a situação tenha um elemento de estraneidade. Este entendimento - que não tinha uma consagração clara no Regulamento Bruxelas II /bis/[Sobre a questão neste Regulamento, cf. @almeida2017, pp. 71 e ss.] - pode encontrar-se hoje nos considerandos 2 a 4 do Regulamento Bruxelas II /ter/[fn:1] e é o único conforme à base habilitante do Regulamento Bruxelas II /ter/[fn:2].

As normas do Regulamento Bruxelas II /ter/ não são, por isso, aplicáveis aos litígios emergentes de situações puramente internas, isto é, situações que só possuem pontos de contacto relevantes com um único Estado soberano.

O Regulamento Bruxelas II /ter/ é um regulamento /duplo/, no sentido em que estabelece regras de competência internacional e de reconhecimento e execução. Quanto a estas últimas, assinala-se que o elemento de estraneidade pode surgir /depois/ de proferida a decisão, exarado o ato autêntico ou celebrado o acordo. Veja-se o seguinte exemplo: A. e B., são franceses, com residência habitual em França, e casados entre si. É proferida decisão de divórcio por um tribunal francês, na sequência de ação instaurada em setembro de 2022. Posteriormente, B. muda a sua residência habitual para Portugal e, em setembro de 2026, pretende casar com C. O reconhecimento (automático) da decisão francesa de divórcio é regido pelo Regulamento Bruxelas II /ter/, pois, no momento do reconhecimento, a situação já possui um elemento de estraneidade.

** B) Em razão do território

Através do âmbito de aplicação em razão do território pretende-se delimitar a aplicabilidade do Regulamento Bruxelas II /ter/. Muitas vezes abordado aquando da análise do âmbito de aplicação em razão do espaço[Cf., em sede de Regulamento Bruxelas II /bis/, @brito2005a, p. 134.], uma primeira aproximação decorre das normas do Tratado da União Europeia (TUE) e do TFUE.

Assim, e nos termos do artigo 288.º do TFUE, o Regulamento Bruxelas II /ter/ “[é] obrigatório em todos os seus elementos e diretamente aplicável em todos os Estados-Membros”. Há, porém, que ter em atenção o Protocolo (N.º 21) relativo à posição do Reino Unido e da Irlanda em relação ao espaço de liberdade, segurança e justiça e o Protocolo (N.º 22) relativo à posição da Dinamarca. Ambos os protocolos estabelecem que os instrumentos de direito derivado da União Europeia, aprovados em aplicação do Título V do Parte III do TFUE, não vinculam /ope iuris/ o Reino Unido, a Irlanda e a Dinamarca, tendo estes Estados-Membros o direito de optar pela participação, ou não, nestes instrumentos de direito derivado da União Europeia.

À semelhança do que tinha sucedido no processo de adoção do Regulamento Bruxelas II /bis/, também no Regulamento Bruxelas II /ter/ se verifica que o Reino Unido e a Irlanda “(...) notificaram a sua intenção de participar na adoção e na aplicação do presente regulamento”[fn:3], pelo que o mesmo lhes é aplicável[fn:4]. O mesmo não sucedeu com a Dinamarca, razão pela qual a mesma não fica vinculada nem sujeita à aplicação do Regulamento Bruxelas II /ter/[fn:5].

Desta primeira aproximação resulta que o Regulamento Bruxelas II /ter/ é obrigatório e diretamente aplicável em todos os Estados-Membros, com exceção da Dinamarca. Aprofundando a análise, é possível inferir do artigo 52.º do TUE e do artigo 355.º do TFUE que o Regulamento Bruxelas II /ter/ não é aplicável na totalidade do territórios dos Estados-Membros a ele vinculados. O Regulamento Bruxelas II /ter/ não é aplicável aos países e territórios não europeus que mantêm relações especiais com a França e os Países Baixos[fn:6], nem aos Estados independentes do Principado do Mónaco, Principado de Andorra, São Marino e Vaticano[Cf. @magnus2012, pp. 22-27.] [fn:7].

** C) Em razão do tempo

O Regulamento Bruxelas II /ter/ distingue, no seu artigo 105.º, entre a data de entrada em vigor (n.º 1) e a data de aplicação das suas normas (n.º 2). O Regulamento entrou em vigor no dia 22 de julho de 2019 e as suas normas são aplicáveis a partir de 1 de agosto de 2022, com exceção dos artigos 92.º, 93.º e 103.º, que são aplicáveis a partir de 22 de julho de 2019[fn:10].

O Tribunal de Justiça da União Europeia[fn:8] teve oportunidade de analisar esta distinção, em sede do Regulamento Roma II, no Acórdão de 17 de novembro de 2011, proc. C-412/10, /Deo Antoine Homawoo contra GMF Assurances SA/, EU:C:2011:747. No entender do TJ “(...) é legítimo que o legislador distinga a data de entrada em vigor da data de aplicação do texto por ele adoptado, atrasando a segunda relativamente à primeira. Uma vez o ato entrado em vigor e, portanto, integrado na ordem jurídica da União, tal procedimento pode permitir, designadamente, que os Estados-Membros ou as instituições da União dêem cumprimento, com fundamento nesse acto, às obrigações prévias que lhes incumbem e que se revelam indispensáveis à sua plena aplicação ulterior a todos os sujeitos de direito que abrange”[fn:9].

O âmbito de aplicação em razão do tempo é próximo, mas não se confunde com a data de aplicação das normas do Regulamento. Como se depreende do artigo 100.º, n.º 1, o âmbito de aplicação em razão do tempo do Regulamento Bruxelas II /ter/ estará preenchido quando determinado ato jurídico relevante ocorre a partir de 1 de agosto de 2022. Assim, o âmbito de aplicação em razão do tempo estará preenchido quando a ação seja instaurada[Sobre a determinação do momento em que o processo foi instaurado cf., neste número da Revista, o artigo da Professora Doutora Elsa Dias Oliveira e, em sede de Regulamento Bruxelas II /bis/, @almeida2017, pp. 215 e ss.], o ato autêntico seja exarado ou o acordo seja registado a partir de 1 de agosto de 2022. Assim, e por exemplo, se, no dia 10 de outubro de 2022, é pedido em Portugal o reconhecimento de uma decisão espanhola em matéria de responsabilidade parental proferida no dia 1 de setembro de 2022, na sequência de processo instaurado em 20 de julho de 2022, não serão aplicáveis as regras de reconhecimento do Regulamento Bruxelas II /ter/, mas sim as do Regulamento Bruxelas II /bis/, como resulta do artigo 100.º, n.º 2, do Regulamento Bruxelas II /ter/.

O âmbito de aplicação em razão do tempo deve, assim, ser também articulado com a norma revogatória prevista no artigo 104.º do Regulamento Bruxelas II /ter/[fn:13]. Apesar de o Regulamento Bruxelas II /ter/ revogar o Regulamento Bruxelas II /bis/ com efeitos a partir de 1 de agosto de 2022[fn:11], as normas deste último Regulamento continuam a aplicar-se sempre que a ação tenha sido instaurada, o ato autêntico exarado e o acordo registado antes de 1 de agosto de 2022[fn:12].

Por fim, o artigo 104.º, n.º 2, é uma norma de cariz eminentemente prático que ordena ao aplicador e ao intérprete entenderem quaisquer remissões efetuadas para normas do Regulamento Bruxelas II /bis/ como remissões para as normas correspondentes do Regulamento Bruxelas II /ter/, determinadas de acordo com a tabela de correspondência /oficial/ constante do anexo X deste último Regulamento. Assinala-se que as remissões podem constar de instrumentos normativos de Direito da União Europeia ou de fonte interna[Cf., neste sentido e sede de Regulamento Bruxelas II /bis/, @magnus2012, p. 470.]. Atendendo ao período de aplicabilidade das normas do Regulamento Bruxelas II /bis/ (de 1 de março de 2005 a 31 de julho de 2022), é expectável que haja um número significativo de remissões[fn:14].

** D) Em razão da matéria

O artigo 1.º do Regulamento Bruxelas II /ter/ segue uma metodologia comum no Direito Internacional Privado da União Europeia: começa por efetuar uma delimitação /positiva/ das matérias a que se pretende aplicar (n.ºs 1 e 2); efetua, depois, uma delimitação /negativa/, enunciando matérias excluídas do seu âmbito de aplicação (n.º 3); por fim, dedica um novo número (n.º 3) à matéria do rapto internacional de crianças.

O Regulamento Bruxelas II /ter/ abrange, em matéria civil, as ações matrimoniais (divórcio, separação e anulação do casamento) e a responsabilidade parental. O conceito de matéria civil /não/ se encontra definido, embora se encontrem algumas pistas interpretativas e uma remissão para a jurisprudência do TJ nos considerandos n.ºs 4 e 5. A questão é  relevante em sede de responsabilidade parental, uma vez que a expressão "matéria civil" pode abranger medidas que, segundo o Direito de fonte interna do Estado-Membro, sejam de Direito público[fn:64]. É igualmente relevante em sede de ações matrimoniais pois permite excluir do âmbito de aplicação as ações matrimoniais proferidas em processo de natureza meramente religiosa[Cf., neste sentido, @borras1998, p. 35, ponto 20, no qual se pode ler que "a menção do termo «cíveis» pretende delimitar claramente o objeto próprio da convenção. Com efeito, a menção não deve ser entendida unicamente em relação com os processos de carácter administrativo a que se refere o n.º 2 do mesmo artigo, mas sim que serve para excluir os processos de natureza meramente religiosa".].

Em matéria de ações matrimoniais assinala-se que o conceito de casamento também não se encontra definido, existindo sensíveis diferenças no modo como o Direito interno dos vários Estados-Membros define este conceito. Numa primeira aproximação, a utilização do conceito "casamento" permite concluir que o Regulamento Bruxelas II /ter/ não abrange relações de facto ou parcerias registadas[Sobre a exclusão destas últimas cf., com mais detalhes, @almeida2017, pp. 47 e ss..]. Apesar de não se encontrar definido, sustenta-se que deve ser feita uma interpretação autónoma do mesmo[Posição já por nós defendida no âmbito do Regulamento Bruxelas II /bis/ em  @almeida2017, pp. 40 e ss..]. Entende-se que o conceito de casamento perfilhado no Regulamento Bruxelas II /ter/ /abrange/ os casamentos de pessoas do mesmo sexo. O argumento literal que depunha em sentido contrário no Regulamento Bruxelas II /bis/ foi eliminado: nos formulários utiliza-se agora a expressão "cônjuge", neutra em termos de género[fn:66], quando antes se utilizavam as expressões "esposo" e "esposa"[fn:67]. E, na União Europeia, é atualmente difícil afirmar que não existe uma forte tendência no sentido de alargar o conceito de casamento às uniões entre pessoas do mesmo sexo.

Assinala-se que, acompanhando um processo de "desjudicialização" do divórcio na União Europeia, o Regulamento Bruxelas II /ter/ admite o reconhecimento de atos autênticos e acordos em matéria de divórcio e separação judicial[fn:68]. O âmbito de aplicação material do Regulamento Bruxelas II /ter/ abrange assim divórcios /privados/, definidos por alguma doutrina como aqueles em que não há uma intervenção /constitutiva/ de uma autoridade[Cf., neste sentido, @gonzalezbeilfuss2020, p. 312.]. Pela nossa parte preferimos distinguir recorrendo ao conceito de autoridade. No âmbito de aplicação material do Regulamento Bruxelas II /ter/ incluem-se agora, adicionalmente, divórcios e separações judiciais em que há uma intervenção de uma autoridade (seja ela constitutiva ou não); os divórcios /puramente/ privados, isto é, os divórcios efetuados sem necessidade da presença de qualquer autoridade, continuam excluídos do âmbito de aplicação material do Regulamento.

O conceito de responsabilidade parental encontra-se definido no artigo 2.º, n.º 2 do Regulamento Bruxelas II /ter/. Este conceito abrange a responsabilidade pela criança, pelos seus bens e a representação legal da criança, abrangendo a generalidade das medidas de proteção da criança[Cf. @pinheiro2019c, pp. 275-276; e @fialho2019, p. 17.] [fn:72]. O Regulamento Bruxelas II /ter/ visa, por isso, abranger todas as decisões em matéria de responsabilidade parental, incluindo as medidas de proteção das crianças[fn:70]. Por este motivo, a enunciação de matérias que consta do artigo 1.º, n.º 2, do Regulamento Bruxelas II /ter/ não é taxativa e tem carácter indicativo[fn:71].

As matérias expressamente excluídas do âmbito de aplicação do Regulamento Bruxelas II /ter/ são enunciadas no artigo 1.º, n.º 4. Este preceito deve ser interpretado de forma /estrita/, mas não se crê que o mesmo seja taxativo. As matérias aí enunciadas relacionam-se com a responsabilidade parental ou são exclusões de cariz geral. O Regulamento, em matéria de ações matrimoniais, é apenas aplicável à dissolução ou enfraquecimento do vínculo matrimonial[Cf. considerando n.º 9 e @almeida2017, pp. 74-75.]. Em matéria de responsabilidade parental, estão excluídas as matérias da filiação, adoção, nomes e apelidos da criança, emancipação e as medidas tomadas na sequência de infrações penais cometidas por crianças.

O Direito da Competência Internacional e o Direito do Reconhecimento das remanescentes matérias elencadas (alimentos, /trusts/ e sucessões) estão, atualmente e em larga medida, unificados no seio da União Europeia. Em matéria de obrigações alimentares vigora, em todos os Estados-Membros da União Europeia, o Regulamento sobre obrigações alimentares. Quanto ao /trust/, vigora em todos os Estados-Membros da União Europeia, o Regulamento Bruxelas I /bis/. E sobre a matéria de sucessões por morte vigora em todos os Estados-Membros da União Europeia, com exceção da Dinamarca e da Irlanda, o Regulamento sobre sucessões.

Por fim, o Regulamento Bruxelas II /ter/ introduz um novo n.º 3, relativo ao rapto internacional de crianças. A necessidade deste novo número parece-nos discutível, muito embora se possa considerar que ele tem um intuito clarificador e pedagógico agora que a matéria do rapto internacional de crianças foi autonomizada no capítulo III, tornando-se assim mais claro que as decisões proferidas nesta sede não constituem decisões de mérito sobre responsabilidade parental. A inclusão no artigo 1.º permite, desde logo, afastar qualquer discussão (que nunca existiu) sobre a recondução da matéria do rapto internacional de crianças ao âmbito de aplicação material do Regulamento Bruxelas II /ter/. Para além disso, reiteram-se alguns elementos que não dizem propriamente respeito ao âmbito de aplicação em razão da matéria: as normas do Regulamento Bruxelas II /ter/ sobre rapto internacional de crianças aplicam-se /em complemento/ das da Convenção da Haia de 1980[fn:76] quando esteja em causa uma deslocação ou retenção ilícitas que afetem mais de um Estado-Membro; as regras de reconhecimento do Regulamento aplicam-se quando o Estado de origem e o Estado requerido sejam Estados-Membros da União Europeia[fn:73].

* III. Definições

O Regulamento Bruxelas II /ter/ estabelece regras uniformes de Direito da Competência Internacional e de Direito do Reconhecimento. Constitui jurisprudência assente do Tribunal de Justiça da União Europeia que os conceitos usados nos regulamentos e em outros diplomas da União Europeia devem ser objeto de interpretação autónoma relativamente ao Direito dos Estados-Membros, de maneira a assegurar a harmonia jurídica internacional e a segurança jurídica. Em especial, o Tribunal de Justiça tem vincado que a interpretação dos atos da União Europeia deve ter em conta o contexto da disposição e o objetivo prosseguido pela regulamentação em causa[fn:37] [Na doutrina portuguesa, cf., em geral, @pinheiro2014, pp. 460-461; em sede do Regulamento Roma II, @oliveira2011, pp. 213 e ss.; e @almeida2017, pp. 34-35 e 114-119.]. A esta luz, as definições constantes do artigo 2.º têm particular relevância pois promovem uma interpretação e aplicação /uniforme/ das regras do Regulamento Bruxelas II /ter/ nos vários Estados-Membros.

O conceito de decisão, previsto no artigo 2.º, n.º 1, do Regulamento Bruxelas II /ter/ é um conceito /amplo/, que abrange decisões, sentenças, acórdãos ou despachos judiciais proferidos por um tribunal de um Estado-Membro. O primeiro parágrafo do artigo 2.º, n.º 1, corresponde, com ajustes de redação, ao artigo 2.º, n.º 4, do Regulamento Bruxelas II /bis/. Destes ajustes destacamos a substituição da expressão "decisão de divórcio, separação ou anulação do casamento" pela expressão decisão "que decreta o divórcio, a separação ou a anulação do casamento". No contexto dos instrumentos precedentes, em particular o Regulamento Bruxelas II /bis/, discutiu-se se o conceito de decisão abrangia /todas/ as decisões de divórcio, separação ou anulação do casamento ou /apenas/ as decisões /positivas/, isto é, as que decretavam o divórcio, a separação ou a anulação do casamento[Cf. @almeida2017, pp. 484 e ss. e bibliografia aí citada.]. A nova redação[fn:38] aponta de forma mais clara no sentido (já sufragado pela maioria da doutrina no âmbito do Regulamento Bruxelas II /bis/) de que apenas as decisões que decretam o divórcio, a separação ou a anulação do casamento beneficiam do regime de reconhecimento do Regulamento Bruxelas II /ter/[fn:65]. A questão não se coloca em matéria de responsabilidade parental, beneficiando do regime de reconhecimento todas as decisões proferidas em matéria de responsabilidade de parental[fn:39]. O conceito de tribunal é definido e será abordado /infra/. O conceito de Estado-Membro /não é definido/ no Regulamento, mas resulta do /supra/ exposto quanto ao âmbito de aplicação em razão do território que ele deve ser interpretado como abrangendo todos os Estados-Membros da União Europeia com exceção da Dinamarca.

Os restantes parágrafos do artigo 2.º, n.º 1, do Regulamento Bruxelas II /ter/ são novos e procedem a algumas clarificações. A alínea /a)/ do segundo parágrafo esclarece que, apesar de não serem decisões de mérito relativas à responsabilidade parental, as decisões proferidas por tribunais de Estados-Membros que ordenem o regresso da criança nos termos da Convenção da Haia de 1980 /beneficiam igualmente/ do regime de reconhecimento previsto no Regulamento Bruxelas II /ter/. A alínea /b)/ do 2.º parágrafo clarifica que /também beneficiam/ do regime de reconhecimento do Regulamento Bruxelas II /ter/ as medidas provisórias e cautelares decretadas pelo tribunal do Estado-Membro competente para conhecer do mérito da causa ou pelo tribunal do Estado-Membro que profira uma decisão de regresso da criança nos termos da Convenção da Haia de 1980. Pelo contrário, /não beneficiam/ do regime de reconhecimento /nem/ as medidas provisórias e cautelares decretadas por um tribunal de um Estado-Membro que não é competente para conhecer do mérito da causa[fn:40] /nem/ as decretadas sem contraditório do requerido, salvo se a decisão que ordena a medida tiver sido notificada ao requerido antes da execução[Cf. terceiro parágrafo do artigo 2.º, n.º 1, do Regulamento Bruxelas II /ter/. Trata-se da solução já anteriormente consagrada no artigo 2.º, alínea /a)/ do Regulamento Bruxelas I /bis/. Sobre esta solução, cf., entre outros, @pinheiro2019b, p. 76; e @magnus2016a, pp. 97-99.].

O Regulamento Bruxelas II /ter/ mantêm um conceito /amplo/ de tribunal, que abrange autoridade /não jurisdicionais/ como autoridades administrativas ou, como sucede nalguns Estados-Membros, os notários. Decisivo é que essas autoridades /não jurisdicionais/ tenham, no respetivo Estado-Membro, competência em matéria de ações matrimoniais ou em matéria relativa à responsabilidade parental.

O conceito de ato autêntico não era definido no Regulamento Bruxelas II /bis/. A definição que agora consta no Regulamento Bruxelas II /ter/ é substancialmente idêntica à de outros Regulamentos[fn:41] e teve origem na jurisprudência do TJ[fn:42]. Novidade é a obrigação dos Estados-Membros comunicarem à Comissão Europeia quem são, nos respetivos Estados-Membros, as autoridades públicas ou outras autoridades habilitadas para o efeito.

Novo é igualmente o conceito de acordo. Este conceito releva apenas para efeitos do regime de reconhecimento e execução previsto no Regulamento Bruxelas II /ter/ e assenta em três elementos: /(i)/ versa sobre uma das matérias abrangidas pelo Regulamento Bruxelas II /ter/; /(ii)/ não é um ato autêntico; mas /(iii)/ é objeto de registo por uma das autoridades indicadas pelos Estados-Membros. O Regulamento distingue assim entre atos autênticos, acordos registados e acordos simples ou não registados: os dois primeiros beneficiam do regime de reconhecimento e execução do Regulamento Bruxelas II /ter/[fn:43]; os acordos simples ou não registados não.

Os conceitos de Estado-Membro de origem e Estado-Membro de execução[fn:44] são já conceitos comuns no Direito do Reconhecimento da União Europeia e visam sobretudo facilitar a leitura e compreensão das regras que compõem o regime de reconhecimento e execução do Regulamento. O Estado-Membro de origem é o Estado-Membro onde foi proferida a decisão, foi formalmente exarado ou registado o ato autêntico ou foi registado o acordo e o Estado-Membro de execução é o Estado-Membro onde se requer o reconhecimento e ou a execução da decisão, do ato autêntico ou do acordo registado[fn:45].

Introduz-se o conceito de criança, definida como qualquer pessoa singular com idade inferior a 18 anos. Mesmo os menores emancipados são considerados crianças. Pretende-se, desta forma, assegurar um paralelismo com a Convenção da Haia de 1996, relativa à Competência, à Lei Aplicável, ao Reconhecimento, à Execução e à Cooperação em matéria de Responsabilidade Parental e Medidas de Proteção das Crianças (Convenção da Haia de 1996) e evitar sobreposições com o âmbito de aplicação da Convenção da Haia de 2000, sobre a Proteção Internacional dos Adultos (Convenção da Haia de 2000), bem como lacunas de regulação. Assinala-se, igualmente, que, para efeitos de rapto internacional de crianças (Capítulo III do Regulamento Bruxelas II /ter/) o conceito de criança é o da Convenção da Haia de 1980, ou seja, são consideradas crianças as pessoas singulares com idade inferior a 16 anos[fn:46].

O conceito de responsabilidade parental é substancialmente idêntico ao adotado no Regulamento Bruxelas II /bis/[fn:47]. Trata-se de um conceito amplo[fn:48], inspirado na Convenção da Haia de 1996[Cf. artigo 1.º, n.º 2, da Convenção da Haia de 1996; no mesmo sentido @magnus2016a, p. 73]. O conceito de responsabilidade parental abrange a responsabilidade pela criança, pelos seus bens e a representação legal da criança, abrangendo a generalidade das medidas de proteção da criança[Cf. @pinheiro2019c, pp. 275-276; e @fialho2019, p. 17. A enunciação de matérias que consta do artigo 1.º, n.º 2, do Regulamento Bruxelas II /ter/ não é taxativa e tem carácter indicativo (ver Acórdãos do Tribunal de Justiça de 21 de outubro de 2015, /Gogova/, C-215/15, EU:C:2015:710, considerando n.º 27, de 26 de abril de 2012, /Health Service Executive/, C-92/12 PPU, EU:C:2012:255, considerando n.º 63 e de 27 de novembro de 2007, /C/, C-435/06, EU:C:2007:714, considerando n.º 30) e as exclusões previstas no artigo 1.º, n.º 3, devem ser objeto de interpretação estrita (Acórdãos /Gogova/, considerando n.º 30 e  /Health Service Executive/, considerando n.º 65)] [fn:50].

O Regulamento Bruxelas II /ter/ mantêm o conceito de titular da responsabilidade parental. O ajuste de redação, que explicita que pode ser titular, para além de qualquer pessoa, qualquer instituição ou qualquer outro organismo que exerça a responsabilidade parental em relação a uma criança não parece ser uma novidade /substantiva/, podendo, no entanto, ter o intuito pedagógico de clarificar que outras entidades para além das pessoas singulares podem ser titulares da responsabilidade parental.

A definição de direito de guarda mantém-se substancialmente inalterada. Esta definiççao é inspirada nas adotadas nas Convenções da Haia de 1980 e de 1996. O foco deste direito está na proteção da pessoa (e não do património) da criança[Cf. @perez-vera1980, pp. 451-452, ponto 84 e as versões espanhola ("los derechos y obligaciones relativos al cuidado de /la persona/ de un menor"), inglesa ("rights and duties relating to the care of /the person/ of a child"), italiana ("i diritti e doveri concernenti la cura /della persona/ di un minore") e francesa ("les droits et obligations portant sur les soins de /la personne/ d’un enfant") do Regulamento Bruxelas II /ter/.].

Também o conceito de direito de visita se mantém substancialmente inalterado, apesar de ligeiros ajustes de redação. Trata-se de um conceito autónomo, definido em termos amplos, pois abrange, exemplificativamente, o direito de levar uma criança, por um período limitado, para um lugar diferente do da sua residência habitual. Abrangendo este direito, abrange igualmente outros meios de contacto menos intensos com o menor, como a visita no lugar de residência habitual do menor e o contacto por telefone, videochamada ou correio eletrónico[Cf., em sentido semelhante,  @magnus2012, p. 85.]. Quanto a quem podem ser os titulares do direito de visita, o TJ esclareceu que este conceito "deve ser entendido no sentido de que se refere não só ao direito de visita dos progenitores em relação ao filho, mas igualmente ao de outras pessoas com as quais é importante que o menor mantenha relações pessoais, designadamente os seus avós, independentemente de se tratar ou não de titulares da responsabilidade parental."[fn:49]

O último conceito definido no artigo 2.º do Regulamento Bruxelas II /ter/ é o de deslocação ou retenção ilícitas. Este conceito mantém-se substancialmente inalterado e coincide com o adotado na Convenção da Haia de 1980, o que se compreende já que as regras do Regulamento Bruxelas II /ter/ visam complementar as da Convenção. A coincidência é agora mais perfeita com a transladação da definição de guarda conjunta para o considerando n.º 18. Este conceito assenta no preenchimento de duas condições /cumulativas/, a saber: a deslocação ou retenção /(i)/ tem de violar um direito de guarda concedido pelo direito do Estado-Membro[fn:52] no qual a criança tinha a sua residência habitual, o que obriga a identificar a residência habitual da criança antes da sua deslocação; e /(ii)/ que o direito de guarda esteja a ser efetivamente exercido ou devesse estar a sê-lo caso não tivesse ocorrido a deslocação ou retenção ilícitas. O TJ já esclareceu, por exemplo, que /não é/ uma deslocação ilícita a situação em que um dos progenitores, sem o acordo do outro, leva o filho do seu Estado de residência habitual para outro Estado-Membro em execução de uma decisão de transferência tomada pelo primeiro Estado-Membro e, em seguida, permanece no segundo Estado‑Membro depois de a referida decisão de transferência ter sido anulada, sem que, no entanto, as autoridades do primeiro Estado-Membro tenham decidido retomar a cargo as pessoas transferidas ou autorizá-las a residir[fn:51].

Alguns conceitos relevantes não são, contudo, definidos no Regulamento Bruxelas II /ter/. É o caso dos conceitos de matéria civil e casamento, que se abordaram /supra/ aquando da análise do âmbito de aplicação em razão da matéria e do conceito de residência habitual (da criança e dos cônjuges) que é primordial para determinar a competência internacional em matéria de ações matrimoniais e de responsabilidade parental. Há, atualmente, uma jurisprudência do TJ bastante extensa quanto ao conceito de residência habitual da criança[fn:53] e, muito recentemente, foi proferido um acórdão relevante em matéria de residência habitual dos cônjuges[fn:54]. Da jurisprudência do TJ resulta que o significado e âmbito de residência habitual é variável em função do contexto e dos objetivos prosseguidos pelo instrumento normativo comunitário em que está inserido, o que dificulta a sua transposição de uma matéria para outra. O Tribunal de Justiça expressamente declarou que as indagações efetuadas em matéria de segurança social não são transponíveis para a matéria da responsabilidade parental[fn:55]. O conceito de residência habitual, tal como entendido pelo TJ, é essencialmente uma questão de facto[fn:56]. O conceito exige presença física e uma nota de estabilidade ou regularidade. A residência habitual é, assim, o lugar onde o interessado fixou, com a vontade de lhe conferir um caráter estável, o centro permanente ou habitual dos seus interesses[fn:57]. Assim, pode concluir-se, em termos gerais, que as pistas recolhidas apontam para uma interpretação autónoma do conceito de residência habitual como o centro de interesses da pessoa (cônjuge ou criança), o qual deve ser determinado tendo em consideração a duração e continuidade da residência, as ligações pessoais, familiares e profissionais, bem como a integração social e económica do indivíduo na sociedade em que reside.

Por fim, no artigo 2.º, n.º 3, estabelece-se que para efeitos dos artigos 3.º, 6.º, 10.º, 12.º, 13.º, 51.º, 59.º, 75.º, 94.º e 102.º o conceito de «domicílio» substitui o conceito de «nacionalidade» para a Irlanda e o Reino Unido e tem o mesmo significado que nos respetivos ordenamentos jurídicos desses Estados-Membros. Trata-se de uma concessão efetuada a estes Estados-Membros que constava já da Convenção de Bruxelas II. No Regulamento Bruxelas II /ter/ verifica-se uma alteração de técnica legislativa: ao invés de prever a substituição em cada um dos artigos em que ela é necessária, efetua-se a mesma numa única disposição que indica os artigos em que a substituição deve ocorrer. Atualmente, a substituição releva apenas para a Irlanda, pois o Reino Unido deixou, por via do /Brexit/, de ser um Estado-Membro. Tal significa, desde logo, que a substituição deixa de ser necessária no artigo 102.º, uma vez que a Irlanda não é um ordenamento jurídico complexo. Não se vê, igualmente, que seja necessário efetuar qualquer substituição no artigo 94.º, uma vez que ele não se refere ao elemento de conexão nacionalidade, mas sim ao princípio da não discriminação em razão da nacionalidade. Os restantes artigos ou correspondem a anteriores preceitos que já previam a substituição em sede do Regulamento Bruxelas II /bis/[fn:58] ou a artigos novos que recorrem à nacionalidade[fn:59].

O conceito de “domicílio”[Sobre este conceito, cf., com maiores detalhes, @almeida2017, pp. 142 e ss. e bibliografia aí indicada.] da Irlanda é um conceito legal multifacetado, pois existem três modalidades de “domicílio”: o /domicile of origin/, o /domicile of dependence/ e o /domicile of choice/.

A todas as pessoas é conferido, nos termos da lei e no momento do nascimento, um /domicile of origin/ que, regra geral, corresponde ao /domicile/ do pai à data do nascimento e é imutável. A aplicabilidade do /domicile of origin/ pode ser suspensa apenas no caso de o indivíduo adquirir um /domicile of choice/ ou um /domicile of dependence/. O /domicile of dependence/ surge em relação a menores e incapazes por anomalia psíquica[fn:60]. A aquisição do /domicile of choice/ exige a verificação de dois pressupostos.
Um pressuposto factual, que consiste na verificação de um período de residência num determinado Estado. O segundo pressuposto é um pressuposto volitivo, que é definido como a intenção de permanecer nesse Estado de forma indefinida[fn:61]. Não é, por isso, fácil adquirir um /domicile of choice/.

Da perspetiva dos tribunais portugueses a questão pode parecer irrelevante, pois não vão, por exemplo, aferir a sua competência internacional através do recurso ao conceito de "domicílio". Todavia a apreensão deste conceito pelos tribunais portugueses é relevante para efeitos do artigo 6.º do Regulamento Bruxelas II /ter/: se dois cônjuges têm "domicílio" na Irlanda,  os tribunais portugueses não podem recorrer às normas atributivas de competência internacional de fonte interna, porque os tribunais de um outro Estado-Membro (Irlanda) são competentes segundo as regras do Regulamento[fn:62]; é igualmente vedado o recurso às normas atributivas de competência internacional de fonte interna nos casos em que o cônjuge requerido tenha "domicílio" na Irlanda[fn:63].

* IV. Relações com outros atos

O Capítulo VIII (artigos 94.º a 99.º) do Regulamento Bruxelas II /ter/ regula as relações deste com outros instrumentos de fonte supraestadual. Na análise que se segue, adota-se a perspetiva do ordenamento jurídico português, dando maior enfoque às normas deste Capítulo que são (mais) relevantes para os intérpretes e aplicadores do direito que atuam no ordenamento jurídico português. Assinala-se ainda que as normas do Capítulo VIII são, em termos substantivos e no geral, próximas das normas correspondentes nos instrumentos que o antecederam (Regulamento Bruxelas II /bis/, Regulamento Bruxelas II[fn:15] e Convenção de Bruxelas II[fn:16]).

No artigo 94.º, n.º 1, do Regulamento Bruxelas II /ter/ encontramos a norma geral: o Regulamento Bruxelas II /ter/ prevalece sobre e substitui as convenções (bilaterais e multilaterais) existentes entre Estados-Membros com âmbito de aplicação em razão da matéria (pelo menos parcialmente) coincidente. A génese desta norma encontra-se no artigo 38.º da Convenção de Bruxelas II e a sua redação é praticamente idêntica à do artigo 59.º, n.º 1, do Regulamento Bruxelas II /bis/[fn:17]. A norma assenta em três distinções, a saber: uma de cariz material, uma de cariz temporal e uma de cariz subjetivo.

A primeira distinção, de cariz material, delimita a aplicabilidade do preceito às convenções “relativas a matérias reguladas pelo presente regulamento”. Esta distinção é de fácil compreensão, uma vez que apenas havendo coincidência no âmbito de aplicação material dos dois instrumentos se coloca um problema de sobreposição de fontes normativas.

A segunda distinção, assente num critério temporal, delimita a aplicação da norma às “(...) convenções existentes à data da entrada em vigor do Regulamento (CE) n.º 2201/2003 (...)”, ou seja, 1 de março de 2005. Este critério temporal é compreensível pois considera-se que os Estados-Membros, a partir da data de entrada em vigor do Regulamento Bruxelas II /bis/, deixaram de ter competência para concluírem convenções internacionais com Estados que incidam sobre o âmbito de aplicação material do Regulamento, nos termos do n.º 2 do artigo 3.º do TFUE e da construção jurisprudencial do TJ[fn:18].

A terceira e última distinção assenta num critério subjetivo e delimita a aplicabilidade do preceito às convenções “celebradas entre dois ou mais Estados-Membros”. As normas das convenções são substituídas pelas normas do Regulamento Bruxelas II /ter/ quando /apenas/ Estados-Membros da União Europeia (vinculados ao Regulamento) sejam Estados Contratantes das convenções.

Os restantes números do artigo 94.º referem-se ao compromisso político gizado com os países nórdicos. O Regulamento Bruxelas II /bis/ concedeu à Finlândia e à Suécia a possibilidade de declarar que a Convenção de 6 de fevereiro de 1931 entre a Dinamarca, a Finlândia, a Islândia, a Noruega e a Suécia relativa às disposições de Direito Internacional Privado em matéria de casamento, adoção e guarda de menores e o respetivo protocolo final prevalecia sobre o Regulamento Bruxelas II /bis/, no todo ou em parte, nas relações entre esses Estados. A Finlândia e a Suécia fizeram tal declaração[fn:19]. Esse compromisso é mantido no Regulamento Bruxelas II /ter/.

O artigo 94.º, n.º 5, do Regulamento Bruxelas II /ter/ tem particular interesse para os intérpretes e órgãos de aplicação do Direito portugueses. Aí se estabelece que as decisões proferidas pelos tribunais da Finlândia e da Suécia /beneficiam/ do regime de reconhecimento e execução previsto no Regulamento Bruxelas II /ter/ desde que a decisão tenha sido proferida "(...) ao abrigo de um critério de competência que corresponda a um dos previstos no capítulo II". Introduz-se, assim, um controlo da competência do tribunal de origem, em regra proibido[fn:20]. Não é obrigatório que o tribunal indique expressamente, na decisão a reconhecer, o critério de competência em que se fundou[Cf., neste sentido, @magnus2012, p. 426 e, por analogia, o Acórdão do TJ de 15 de julho de 2010, /Bianca Purrucker contra Guillermo Vallés Pérez/, C-256/09, EU:C:2010:437]. Nem nos parece que seja necessário que o concreto critério de competência utilizado para proferir a decisão corresponda a um dos consagrados no Regulamento Bruxelas II /ter/, bastando que seja possível verificar - da análise da decisão - que um dos critérios consagrados no Regulamento Bruxelas II /ter/ se encontra preenchido[fn:21].

O artigo 95.º regula as relações entre o Regulamento Bruxelas II /ter/ e quatro convenções multilaterais, duas em matéria matrimonial[fn:22] e duas em matéria de responsabilidade parental[fn:23]. O Estado Português vinculou-se internacionalmente a três destas convenções, não sendo Estado Contratante da Convenção do Luxemburgo, de 8 de setembro de 1967, sobre o reconhecimento das decisões relativas ao vínculo conjugal.

O artigo 95.º estabelece que nas relações entre dois (ou mais) Estados-Membros da União Europeia que sejam igualmente Estados Contratantes de uma destas convenções multilaterais prevalecem as regras do Regulamento Bruxelas II /ter/. Ou seja: as regras destas convenções multilaterais só são aplicáveis nas relações entre Estados-Membros da União Europeia e Estados terceiros que sejam Estados Contratantes de uma destas quatro convenções[Cf., neste sentido, @corneloup2013, p. 462.] [fn:24]. Esta solução não suscita dificuldades de maior pois as convenções preveem que outros instrumentos possam prevalecer sobre elas[Cf., neste sentido, @magnus2012, p. 428; e, referindo-se apenas à Convenção da Haia de 1970 e à Convenção do Luxemburgo, de 8 de setembro de 1967, sobre o reconhecimento das decisões relativas ao vínculo conjugal, @corneloup2013, pp. 465-466] [fn:25].

A relação entre o Regulamento Bruxelas II /ter/ e a Convenção da Haia de 1980 é regulada no artigo 96.º do Regulamento[fn:26]. Esclarece-se, no primeiro período e na sequência da jurisprudência do TJ[fn:27], que as regras do Regulamento Bruxelas II /ter/ complementam as regras da Convenção da Haia de 1980 nos casos de deslocação ou retenção ilícitas que ocorram entre Estados-Membros da União Europeia[fn:28]. Mais interessante é o segundo período do artigo 96.º: aí se prevê que as decisões de regresso proferidas por um tribunal de um Estado-Membro /beneficiam/ do regime de reconhecimento e execução previsto no capítulo IV do Regulamento Bruxelas II /ter/, caso haja /nova/ deslocação ou retenção ilícita da criança num outro Estado-Membro. Tal significa que essas decisões beneficiam do regime de reconhecimento e execução do Regulamento Bruxelas II /ter/ mesmo que o Estado da residência habitual da criança imediatamente antes da (primeira) deslocação ou retenção ilícitas seja um Estado terceiro.

A articulação com a Convenção da Haia de 1996 encontra-se prevista no artigo 97.º do Regulamento Bruxelas II /ter/. Estabelece-se que as regras de reconhecimento e execução do Regulamento Bruxelas /ter/ prevalecem /sempre/ sobre as da Convenção da Haia de 1996, quando o Estado de origem e o Estado de reconhecimento sejam Estados-Membros da União Europeia vinculados ao Regulamento Bruxelas II /ter/[fn:29]. Esta solução - que parece visar uma mais fácil "circulação" das decisões no espaço europeu, assente no princípio da confiança mútua - acarreta, nos casos em que a criança tenha residência habitual num Estado terceiro que é um Estado contratante da Convenção da Haia de 1996, um risco de se reconhecerem decisões, ao abrigo do regime do Regulamento Bruxelas II /ter/, cujo reconhecimento poderia ser recusado ao abrigo do regime da Convenção da Haia de 1996[Cf., neste sentido, no contexto do Regulamento Bruxelas II /bis/, @magnus2012, p. 431. Assinala-se que o regime de reconhecimento e execução da Convenção da Haia de 1996 consagra a possibilidade de controlo da competência do tribunal de origem (art. 23.º, alínea /a)/), o qual é proibido no artigo 69.º do Regulamento Bruxelas II /ter/.]. Prevê-se também que as regras do Regulamento Bruxelas II /ter/ prevalecem sobre as da Convenção da Haia de 1996 quando a criança reside habitualmente num Estado-Membro da União Europeia vinculado ao Regulamento[fn:30]. O Regulamento Bruxelas II /ter/ esclarece, no novo n.º 2 do artigo 97.º, que essa prevalência /não prejudica/: /(i)/ a possibilidade de as partes, por acordo, conferirem competência a um tribunal de um Estado terceiro, nos termos do artigo 10.º da Convenção da Haia de 1996; /(ii)/ a possibilidade de transferência de competência para um tribunal de um Estado terceiro, que seja Estado Contratante da Convenção da Haia de 1996, nos termos dos seus artigos 8.º e 9.º; e /(iii)/ a aplicação da regra de litispendência da Convenção da Haia de 1996 (artigo 13.º) quando o tribunal primeiramente demandado seja o de um Estado Contratante terceiro.

O artigo 98.º do Regulamento Bruxelas II /ter/ parece ter um conteúdo meramente clarificador e pedagógico. O n.º 1 dispõe que, nas situações em que não há coincidência material, mantêm-se aplicáveis as regras dos instrumentos normativos de fonte supraestadual referidos nos artigos 94.º a 97.º do Regulamento Bruxelas II /ter/. Assim, e por exemplo, como o Regulamento Bruxelas II /ter/ não estabelece normas de direito de conflitos em matéria de responsabilidade parental, são aplicáveis os artigos 15.º a 22.º da Convenção da Haia de 1996[fn:31]. Trata-se, por isso, de uma formulação negativa do que já resulta dos artigos 94.º a 97.º: só é necessário definir a relação do Regulamento Bruxelas II /ter/ com outros atos quando há uma coincidência (total ou parcial) em razão da matéria. O n.º 2 parece desprovido de sentido útil, uma vez que nem a aprovação do Regulamento Bruxelas II /ter/ nem a entrada em aplicação das suas normas, em particular os artigos 95.º a 97, têm como efeito a cessação dos compromissos internacionais previamente assumidos pelos Estados-Membros. Atendendo à formulação do preceito correspondente no Regulamento Bruxelas II /bis/, que destacava apenas a Convenção da Haia de 1980, avançou-se que este visava reiterar que os Estados-Membros continuavam a ter de aplicar as regras desta Convenção, uma vez que as regras do Regulamento sobre rapto internacional de crianças apenas /complementam/ as regras da Convenção[Cf., neste sentido, @magnus2012, p. 432; e @corneloup2013, pp. 469-470.]. A inclusão da Convenção da Haia de 1996 dificulta esta interpretação, mas poder-se-á afirmar que, apesar de redundante, o preceito visa destacar a necessidade de articulação do Regulamento com as Convenções, em particular as Convenções da Haia de 1980 e de 1996.

Espanha, Itália, Malta e Portugal celebraram Tratados com a Santa Sé, nos quais se regula a matéria da anulação do casamento católico. O artigo 99.º do Regulamento Bruxelas II /ter/ rege a articulação com estes Tratados. Os n.ºs 1 e 2 regem a articulação do Regulamento com a Concordata celebrada entre a Santa Sé e Portugal; os n.º 3 e 4 regem a articulação do Regulamento com os Tratados celebrados entre a Santa Sé e Espanha, Itália e Malta; por fim, o n.º 5 estabelece obrigações de prestação de informações aos quatro Estados-Membros.

O tratamento autónomo da Concordata celebrada entre a Santa Sé e Portugal tem uma razão histórica: a Concordata de 1940 estabelecia, no seu artigo XXV, que "O conhecimento das causas concernentes à nulidade do casamento católico e à dispensa do casamento rato e não consumado, é reservado aos tribunais e repartições eclesiásticos competentes"; as Concordatas celebradas com Espanha, Itália e Malta não contêm idêntica disposição, admitindo uma competência concorrente dos tribunais civis e eclesiásticos. O Regulamento Bruxelas II /ter/[fn:32] colide assim com as obrigações internacionais assumidas por Portugal na Concordata de 1940, na medida em que prevê a competência internacional dos tribunais (civis) dos Estados-Membros, e o reconhecimento das decisões proferidas por esses tribunais, para as ações de anulação dos casamentos concordatários portugueses[fn:33]. Por esses motivos, o artigo 99.º, n.º 1, do Regulamento Bruxelas II /ter/[fn:34] concederia a Portugal a faculdade de não reconhecer a competência internacional nem as decisões de anulação de casamentos concordatários portugueses proferidas por tribunais (civis) de outros Estados-Membros[Cf., neste sentido,  @borras1998, p. 61, ponto 120; @magnus2012, p. 433.].

Sucede, porém, que foi celebrada a Concordata entre a República Portuguesa e a Santa Sé de 2004, que substitui a de 1940. A Concordata de 2004 /não/ atribui competência exclusiva aos tribunais eclesiásticos[fn:35]. Deixou, por isso, de existir o compromisso internacional previamente assumido que justificava a faculdade de não reconhecer decisões de anulação de casamento proferidas por tribunais (civis) de outros Estados-Membros[Cf., em sentido semelhante, @corneloup2013, pp. 473-474.].

O artigo 99.º, n.º 2, estabelece que as decisões em matéria de ações matrimoniais proferidas pelos tribunais eclesiásticos ao abrigo da Concordata de 2004 beneficiam do regime de reconhecimento do Regulamento Bruxelas II /ter/, depois de revistas e confirmadas em conformidade com o disposto no artigo 16.º da Concordata de 2004[Cf., no mesmo sentido, @borras1998, p. 61, ponto 120.]. O reconhecimento destas decisões em Espanha, Itália ou Malta pode ficar sujeito aos requisitos previstos nos respetivos Tratados celebrados com a Santa Sé[fn:36].

* Footnotes

[fn:76] Convenção da Haia de 1980, sobre os Aspetos Civis do Rapto Internacional de Crianças.

[fn:75] Regulamento (CE) n.º 2201/2003 do Conselho, de 27 de Novembro de 2003, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e que revoga o Regulamento (CE) n.º 1347/2000, publicado no JO L 338, de 23 de dezembro de 2003.

[fn:74] Regulamento (UE) 2019/1111 do Conselho, de 25 de junho de 2019, relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e em matéria de responsabilidade parental e ao rapto internacional de crianças (reformulação), publicado no Jornal Oficial (JO) L 178, de 2 de julho de 2019.

[fn:73] Com exceção da Dinamarca.

[fn:72] Chama-se, porém, a atenção para o facto de as medidas relativas aos bens da criança não relacionadas com a sua proteção continuarem a ser reguladas pelo Regulamento (UE) n.º 1215/2012 do Parlamento Europeu e do Conselho, de 12 de dezembro de 2012, relativo à competência judiciária, ao reconhecimento e à execução de decisões em matéria civil e comercialRegulamento Bruxelas I /bis/ (reformulação), publicado no JO L 351 de 20 de dezembro de 2012, doravante abreviadamente designado Regulamento Bruxelas I /bis/ (cf. considerando n.º 10 do Regulamento Bruxelas II /ter/).

[fn:71] Ver Acórdãos do Tribunal de Justiça de 21 de outubro de 2015, /Gogova/, C-215/15, EU:C:2015:710, considerando n.º 27, de 26 de abril de 2012, /Health Service Executive/, C-92/12 PPU, EU:C:2012:255, considerando n.º 63 e de 27 de novembro de 2007, /C/, C-435/06, EU:C:2007:714, considerando n.º 30.

[fn:70] Cf. considerando n.º 7 do Regulamento Bruxelas II /ter/.

[fn:69] Ver /infra/.

[fn:68] Cf. artigos 64.º e ss. do Regulamento Bruxelas II /ter/.

[fn:67] Cf. Anexo I do Regulamento Bruxelas II /bis/.

[fn:66] Cf. ponto 5.1 do Anexo II e ponto 6.1 do Anexo VII do Regulamento Bruxelas II /ter/.

[fn:65] Cf., neste sentido, o último período do considerando n.º 9 do Regulamento Bruxelas II /ter/.

[fn:64] No Acórdão de 27 de novembro de 2007, /C/, C-435/06, EU:C:2007:714, considerando n.º 53, o TJ concluíu que "uma decisão única que ordena a entrega imediata de um menor e a sua colocação fora da sua família, numa família de acolhimento, é abrangida pelo conceito de «matéria civil», na acepção dessa disposição, quando essa decisão tiver sido tomada no quadro das normas de direito público relativas à protecção de menores." No processo estava em causa uma medida que, segundo o Governo Sueco, implicava o exercício de poderes de autoridade.

[fn:63] Cf. artigo 2.º, n.º 3, e 6.º, n.º 2, do Regulamento Bruxelas II /ter/.

[fn:62] Os artigos 2.º, n.º 3, e 3.º, alínea /b)/, do Regulamento Bruxelas II /ter/ conferem competência internacional aos tribunais da Irlanda. O artigo 6.º, n.º 1, impede o recurso às normas de competência internacional de fonte interna.

[fn:61] Uma intenção de residir num determinado Estado por um período determinado (ainda que relativamente longo) ou até à verificação de uma determinada condição não é suficiente para preencher o pressuposto volitivo.

[fn:60] Historicamente, o /domicilie of dependence/ era atribuído também a mulheres casadas. Atualmente, a jurisprudência irlandesa afere o /domicile/ de todas as mulheres casadas de forma independente, de acordo com as regras do /domicile of origin/ ou /domicile of choice/.

[fn:59] Artigos 10.º, 12.º, 13.º, 51.º e 59.º.

[fn:58] Artigos 3.º, 6.º e 75.º.

[fn:57] Cf., por exemplo, Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerandos n.º 41 a 43. No caso das crianças, o TJ esclareceu que a vontade relevante é a das pessoas que efetivamente a guardam e cuidam dela (/v.g./ Acórdão de 22 de dezembro de 2010, /Mercredi/, C-497/10 PPU, EU:C:2010:829, considerandos n.ºs 54 e 56).

[fn:56] Cf. Acórdãos de 8 de junho de 2017, OL, C‑111/17 PPU, EU:C:2017:436, considerando n.º 51, e de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerando n.º 52.

[fn:55] Cf. Acórdão de 2 de abril de 2009, /A/, C-523/07, EU:C:2009:225, considerando n.º 36.

[fn:54] Acórdão de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerandos n.º 38 e ss..

[fn:53] Sem qualquer pretensão de exaustividade, cf. Acórdãos de 2 de abril de 2009, /A/, C-523/07, EU:C:2009:225, considerandos n.ºs 36 e 44, de 22 de dezembro de 2010, /Mercredi/, C-497/10 PPU, EU:C:2010:829, considerandos n.ºs 54 a 56, de 15 de fevereiro de 2017, /W e V contra X/, C-499/15, EU:C:2017:118, considerandos n.ºs 61 a 63, de 8 de junho de 2017, /OL contra PQ/, C-111/17 PPU, EU:C:2017:436, considerando n.º 70, de 28 de junho de 2018, /HR/, C-512/17, EU:C:2018:513, considerando n.º 64, e de 17 de outubro de 2018, /UD contra XB/, C-393/18 PPU, EU:C:2018:835, considerandos n.º 69 e 70.

[fn:52] Foi já questionado, junto do TJ, se seria contrário ao Regulamento Bruxelas II /bis/ e ao Direito da União Europeia o Direito de um Estado-Membro sujeitar a aquisição do direito de guarda por parte do pai de um menor, não casado com a mãe deste último, à obtenção por parte do pai de uma decisão do órgão jurisdicional nacional competente que lhe atribua tal direito. No Acórdão de 5 de outubro de 2010, C-400/10 PPU, /J. McB. contra L. E./, EU:C:2010:582, considerando n.º 64, o TJ concluiu que não, recordando que o mesmo entendimento foi perfilhado pelo Tribunal Europeu dos Direitos do Homem (considerando n.º 54) e que este Tribunal decidiu que uma legislação nacional que não conceda ao pai natural nenhuma possibilidade de obter o direito de guarda do seu filho caso não exista o acordo da mãe constitui uma discriminação injustificada contra o pai e viola, por conseguinte, o artigo 14.º, lido em conjugação com o artigo 8.º, da Convenção Europeia dos Direitos do Homem (considerando n.º 56).

[fn:51] Acórdão de 2 de agosto de 2021, /A contra B/, C-262/21 PPU, EU:C:2021:640, considerando n.º 53.

[fn:50] Cf., também, o Acórdão de 3 de outubro de 2019, /OF contra PG/, C-759/18, EU:C:2019:816, no qual o TJ afirmou "que o conceito de «responsabilidade parental», na aceção do artigo 2.º, ponto 7, do Regulamento n.º 2201/2003, abrange, nomeadamente, todas as decisões em matéria de direito de guarda e de residência do menor" (considerando n.º 52).

[fn:49] Acórdão de 31 de maio de 2018, /Valcheva/, C-335/17, EU:C:2018:359, considerando n.º 33.

[fn:48] Cf. Acórdãos do Tribunal de Justiça de 21 de outubro de 2015, /Gogova/, C-215/15, EU:C:2015:710, considerando n.º 27, de 26 de abril de 2012, /Health Service Executive/, C-92/12 PPU, EU:C:2012:255, considerando n.º 59 e de 27 de novembro de 2007, /C/, C-435/06, EU:C:2007:714, considerando n.º 49.

[fn:47] Cf. artigo 2.º, n.º 7, do Regulamento Bruxelas II /bis/.

[fn:46] Cf. considerando n.º 17 do Regulamento Bruxelas II /ter/ e o artigo 4.º da Convenção da Haia de 1980.

[fn:45] Apesar de a definição mencionar apenas a execução, como o fazia o Regulamento Bruxelas II /bis/, parece-nos mais correta a formulação adotada nos demais regulamentos (v.g. Regulamento Bruxelas I /bis/, Regulamento sobre Sucessões e Regulamento sobre regimes matrimoniais).

[fn:44] O Regulamento Bruxelas I /bis/ utiliza a expressão Estado-Membro requerido, que nos parece preferível.

[fn:43] Cf. artigos 64.º e ss. do Regulamento Bruxelas II /ter/.

[fn:42] Cf. Acórdão de 17 de junho de 1999, /Unibank/, C-260/97, EU:C:1999:312.

[fn:41] Cf. considerando n.º 15 do Regulamento Bruxelas II /ter/ e artigo 2.º, alínea /c)/, do Regulamento Bruxelas I /bis/, artigo 3.º, n.º 1, alínea /i)/ do Regulamento sobre sucessões, artigo 3.º, n.º 1, alínea /c)/, do Regulamento sobre regimes matrimoniais e o artigo 3.º, n.º 1, alínea /d)/, do Regulamento sobre efeitos patrimoniais das parcerias registadas.

[fn:40] Cf. artigo 15.º do Regulamento Bruxelas II /ter/.

[fn:39] Isso mesmo resulta da diferente redação do preceito, que utiliza a expressão decisão "relativa à responsabilidade parental".

[fn:38] As versões inglesa ("including a decree, order or judgment, /granting/ divorce, legal separation, or annulment of a marriage,"), francesa ("y compris un arrêt, un jugement ou une ordonnance, /accordant/ le divorce, la séparation de corps ou l’annulation d’un mariage"), espanhola ("en particular un fallo, una orden o una resolución que conceda el divorcio, la separación legal, la nulidad matrimonial"), italiana ("inclusi un decreto, un’ordinanza o una sentenza, /che sancisca/ il divorzio, la separazione personale dei coniugi, l’annullamento del matrimonio") e alemã ("einschließlich einer Verfügung, eines Beschlusses oder eines Urteils, mit der die Ehescheidung, die Trennung ohne Auflösung des Ehebandes oder die Ungültigerklärung einer Ehe /ausgesprochen wird/") apontam no mesmo sentido. Itálicos aditados.

[fn:37] A questão surgiu, inicialmente, com a interpretação dos conceitos da Convenção de Bruxelas de 1968 relativa à Competência Jurisdicional e à Execução de Decisões em Matéria Civil e Comercial, com maior acuidade no Acórdão de 14 de outubro de 1976, /Eurocontrol/, 29/76, EU:C:1976:137, considerando n.º 3. No âmbito do Regulamento Bruxelas II /bis/, veja-se, por exemplo, o Acórdão de 2 de abril de 2009, /A./, C-523/07, EU:C:2009:225, considerando n.º 34, e os recentíssimos Acórdãos de 2 de agosto de 2021, /A. contra B./, proc. C-262/21 PPU, EU:C:2021:640, considerando n.º 40 e de 25 de novembro de 2021, /IB contra FA/, C-289/20, EU:C:2021:955, considerandos n.º 38 e ss..

[fn:36] Cf. artigo 99.º, n.º 4, do Regulamento Bruxelas II /ter/.

[fn:35] Estabelece o artigo 16.º, n.º 1, da Concordata de 2004 que "As decisões relativas à nulidade e à dispensa pontifícia do casamento rato e não consumado pelas autoridades eclesiásticas competentes, verificadas pelo órgão eclesiástico de controlo superior, produzem efeitos civis, a requerimento de qualquer das partes, após revisão e confirmação, nos termos do direito português, pelo competente tribunal do Estado".

[fn:34] Este preceito é substancialmente idêntico ao artigo 62.º do Regulamento Bruxelas II /bis/, ao artigo 40.º do Regulamento Bruxelas II e ao artigo 42.º da Convenção de Bruxelas II, atualizando apenas a menção à Concordata celebrada entre a Santa Sé e Portugal em 2004.

[fn:33] Veja-se o seguinte exemplo: A., português, e B., espanhola, celebram casamento católico entre si em Portugal. Após o casamento passam a residir habitualmente na Itália. Caso um deles pretenda intentar ação de anulação do casamento, os tribunais internacionalmente competentes são os italianos, por força do artigo 3.º, alínea /a)/, subalínea /i)/, do Regulamento Bruxelas II /ter/. Caso o tribunal italiano profira uma decisão de anulação do casamento, esta decisão seria automaticamente reconhecida em Portugal, por força do artigo 30.º do Regulamento Bruxelas II /ter/.

[fn:32] E o Regulamento Bruxelas II /bis/, o Regulamento Bruxelas II e a Convenção de Bruxelas II.

[fn:31] O que foi expressamente referido pelo legislador no considerando n.º 92 do Regulamento Bruxelas II /ter/.

[fn:30] Cf. artigo 97.º, n.º 1, alínea /a)/, do Regulamento Bruxelas II /ter/.

[fn:29] Cf. artigo 97.º, n.º 1, alínea /b)/, do Regulamento Bruxelas II /ter/.

[fn:28] Excluindo a Dinamarca que não participa no Regulamento Bruxelas II /ter/ e não fica a ele vinculada nem sujeita à sua aplicação.

[fn:27] Cf. Parecer do TJ de 14 de outubro de 2014, Parecer 1/13, EU:C:2014:2303, considerandos n.ºs 77 e 78. No mesmo sentido, cf. o considerando 40 do Regulamento Bruxelas II /ter/.

[fn:26] Trata-se de um artigo /novo/, pois no Regulamento Bruxelas II /bis/ a Convenção da Haia de 1980 era uma das cinco convenções multilaterais referidas no artigo 60.º. Esta autonomização parece justificar-se sobretudo em face do novo capítulo III, relativo ao rapto internacional de crianças.

[fn:25] Cf. o artigo 13.º da  Convenção do Luxemburgo, de 8 de setembro de 1967, sobre o reconhecimento das decisões relativas ao vínculo conjugal, o artigo 18.º da Convenção da Haia de 1970 e os artigos 19.º e 20 da Convenção Europeia, de 20 de maio de 1980, sobre o reconhecimento e a execução das decisões relativas à custódia de menores e sobre o restabelecimento da custódia de menores. A questão poderia revestir maior complexidade no que se refere à Convenção da Haia de 1961, atendendo a que o seu artigo 18.º apenas salvaguarda outras convenções /anteriores/. Porém, atualmente, todos os Estados Contratantes desta Convenção são igualmente Estados Contratantes da Convenção da Haia de 1996  pelo que, nos termos do artigo 51.º desta Convenção, a Convenção da Haia de 1961 não tem hoje aplicação.

[fn:24] Veja-se, como exemplo, a Convenção da Haia de 1970. Dos vinte Estados contratantes, doze são Estados-Membros da União Europeia. Assim, em Portugal, as regras desta Convenção só devem ser aplicadas pelos órgãos aplicadores do direito portugueses quando a decisão estrangeira a reconhecer tenha sido proferida num de 8 Estados Contratantes, a saber, Albânia, Austrália, China (mas apenas as decisões proferidas na região administrativa especial de Hong Kong), Dinamarca, Egito, Moldávia, Noruega e Suíça.

[fn:23] A Convenção da Haia, de 5 de outubro de 1961, relativa à competência das autoridades e à lei aplicável em matéria de proteção de menores (doravante Convenção da Haia de 1961) e a Convenção Europeia, de 20 de maio de 1980, sobre o reconhecimento e a execução das decisões relativas à custódia de menores e sobre o restabelecimento da custódia de menores.

[fn:22] A Convenção do Luxemburgo, de 8 de setembro de 1967, sobre o reconhecimento das decisões relativas ao vínculo conjugal e a Convenção da Haia de 1970.

[fn:21] A questão não é muito relevante pois os critérios atributivos de competência internacional previstos na Convenção são bastante similares aos previsto no Regulamento Bruxelas II /ter/.

[fn:20] Cf. artigo 69.º do Regulamento Bruxelas II /ter/.

[fn:19] As declarações foram publicadas como Anexo IV do Regulamento Bruxelas II /bis/.

[fn:18] Cf. o Acórdão do TJ de 31 de março de 1971, proc. 22/70, /Comissão das Comunidades Europeias contra Conselho das Comunidades Europeias (AETR)/, EU:C:1971:32, considerandos n.ºs 17 e 18, o Parecer do TJ de 7 de fevereiro de 2006, Parecer 1/03, EU:C:2006:81, considerando n.º 116, e o Parecer do TJ de 14 de outubro de 2014, Parecer 1/13, EU:C:2014:2303, no qual este Tribunal voltou a afirmar, desta feita em sede do Regulamento Bruxelas II bis, que a “competência da União para celebrar acordos internacionais pode resultar não só de uma atribuição expressa conferida pelos Tratados mas também, implicitamente, de outras disposições dos Tratados e de atos adotados, no âmbito dessas disposições, pelas instituições da União. Em particular, sempre que o Direito da União confira às referidas instituições competências a nível interno, com vista a realizar um determinado objetivo, a União é investida da competência para assumir os compromissos internacionais necessários à realização desse objetivo, mesmo na falta de uma disposição expressa nesse sentido (parecer 1/03, EU:C:2006:81, n.º 114 e jurisprudência referida). Esta última hipótese está, de resto, prevista no artigo 216.º, n.º 1, TFUE” (cf. considerando n.º 67), tendo emitido parecer no sentido de que a “aceitação da adesão de um Estado terceiro à Convenção sobre os Aspetos Civis do Rapto Internacional de Crianças, celebrada em Haia, em 25 de outubro de 1980, é da competência exclusiva da União Europeia” (cf. conclusão do Parecer).

[fn:17] A única diferença de redação diz respeito ao modo como é fixado o momento relevante para apurar se uma determinada convenção é ou não existente. Ambos os Regulamentos fixam como momento relevante a data de entrada em vigor do Regulamento Bruxelas II /bis/ (1 de março de 2005). No artigo 59.º, n.º 1, do Regulamento Bruxelas II /bis/ é utilizada a expressão "(...) as convenções existentes à data da sua entrada em vigor (...)", enquanto no Regulamento Bruxelas II /ter/ é usada a expressão "(...) as convenções existentes à data da entrada em vigor do Regulamento (CE) n.º 2201/2003 (...)".

[fn:16] Convenção relativa à competência, ao reconhecimento e à execução de decisões em matéria matrimonial, publicada no JO C 221/1, de 16 de julho de 1998.

[fn:15] Regulamento (CE) n.º 1347/2000 do Conselho de 29 de Maio de 2000
relativo à competência, ao reconhecimento e à execução de decisões em matéria matrimonial e de regulação do poder paternal em relação a filhos comuns do casal, publicado no JO L 160/19, de 30 de junho de 2000.

[fn:14] Sem qualquer pretensão de exaustividade, e limitando-nos aos instrumentos normativos de Direito da União Europeia, encontram-se remissões para as normas do Regulamento Bruxelas II /bis/: /(i)/ no artigo 20.º, n.º 1, da Directiva 2011/99/UE do Parlamento Europeu e do Conselho, de 13 de Dezembro de 2011, relativa à decisão europeia de proteção, publicada no Jornal Oficial da União Europeia (doravante JO) L 338, de 21 de dezembro de 2011, /(ii)/ no artigo 73.º, n.º 1, do Regulamento (CE) n.º 4/2009 do Conselho, de 18 de Dezembro de 2008, relativo à competência, à lei aplicável, ao reconhecimento e à execução das decisões e à cooperação em matéria de obrigações alimentares, publicado no JO L 7, de 10 de janeiro de 2009 (doravante Regulamento sobre obrigações alimentares), /(iii)/ nos artigos 1.º, n.º 2, e 2.º, n.º 1, alínea /b)/, do Regulamento (CE) n.º 664/2009 do Conselho, de 7 de Julho de 2009, que estabelece um procedimento para a negociação e a celebração de acordos entre Estados-Membros e países terceiros relativamente à competência, ao reconhecimento e à execução de sentenças e decisões em matéria matrimonial, de responsabilidade parental e de obrigações de alimentos, bem como à lei aplicável em matéria de obrigações de alimentos, publicado no JO L 200, de 31 de julho de 2009, /(iv)/ no artigo 2.º do Regulamento (UE) n.º 1259/2010 do Conselho, de 20 de Dezembro de 2010, que cria uma cooperação reforçada no domínio da lei aplicável em matéria de divórcio e separação judicial, publicado no JO L 343 de 29 de dezembro de 2010, /(v)/ no artigo 2.º, n.º 3, do Regulamento (UE) n.º 606/2013 do Parlamento Europeu e do Conselho, de 12 de junho de 2013, relativo ao reconhecimento mútuo de medidas de proteção em matéria civil, publicado no JO L 181, de 29 de junho de 2013, e /(vi)/ no artigo 5.º do Regulamento (UE) 2016/1103 do Conselho, de 24 de junho de 2016, que implementa a cooperação reforçada no domínio da competência, da lei aplicável, do reconhecimento e da execução de decisões em matéria de regimes matrimoniais, publicado no JO L 183, de 8 de julho de 2016 (doravante Regulamento sobre regimes matrimoniais).

[fn:13] Norma substancialmente idêntica ao artigo 71.º do Regulamento Bruxelas II /bis/.

[fn:12] O que resulta do artigo 100.º, n.º 2, do Regulamento Bruxelas II /ter/ já analisado e é reforçado pela expressão "Sob reserva do artigo 100.º, n.º 2, do presente regulamento (...)" constante do início do artigo 104.º, n.º 1.

[fn:11] Cf. artigo 104.º, n.º 1, do Regulamento Bruxelas II /ter/.

[fn:10] A data de produção de efeitos destes três artigos coincide com a data de entrada em vigor. Tal justifica-se por razões diversas: os artigos 92.º e 93.º atribuem à Comissão Europeia o poder de adotar atos delegados no que respeita aos anexos do Regulamento, podendo haver interesse em que a Comissão Europeia possa exercer este poder ainda antes da data de aplicação do Regulamento; o artigo 103.º estabelece obrigações de informação aos Estados-Membros, relacionadas com a operacionalização do Regulamento, que deveriam ser comunicadas à Comissão Europeia até 23 de abril de 2021.

[fn:9] Cf. considerando n.º 24. O Advogado-Geral Paolo Mengozzi, nas suas conclusões apresentadas em 6 de setembro de 2011, neste processo, conclui no mesmo sentido, ao afirmar que o “legislador distingue a data de entrada em vigor da de aplicação nos regulamentos subsequentes no mesmo domínio, com prazos mais ou menos longos entre estas duas datas, que permitem que os Estados-Membros adoptem eventuais modificações do seu direito nacional antes de transmitirem à Comissão as informações requeridas especificadas no instrumento em questão. Estas informações são depois colocadas à disposição do público, geralmente através de publicação no Jornal Oficial da União Europeia” (cf. considerando n.º 22).

[fn:8] Doravante TJ.

[fn:7] A relevância desta análise mais profunda pode ilustrar-se com o Acórdão do Tribunal da Relação de Lisboa de 10 de maio de 2011, proc. 1105/10.5TYRLSB-1. Foi intentada junto deste Tribunal ação de revisão de sentença estrangeira, pedindo que fosse revista e confirmada a sentença proferida em 11 de março de 2010 pelo Tribunal Real de Guernsey, transitada em julgada, que decretou a dissolução do casamento civil celebrado em 19/5/2006 entre  requerente e requerida. A ação foi intentada de acordo com o Direito de Reconhecimento de fonte interna. O Tribunal da Relação de Lisboa considerou-se hierarquicamente incompetente e absolveu a requerida da instância. Fundamentou esta decisão no facto de a decisão cujo reconhecimento se pedia ter sido proferida por um tribunal de um Estado-Membro após a data de entrada em vigor do Regulamento Bruxelas II /bis/, razão pela qual se aplicaria o regime de reconhecimento consagrado neste Regulamento. De acordo com esse regime, os tribunais competentes para os processos de reconhecimento autónomos são os tribunais de 1.ª instância e não os tribunais da relação, verificando-se assim, no entender do Tribunal da Relação de Lisboa uma incompetência em razão da hierarquia. Sucede porém que, por força do artigo 355.º, n.º 5, alínea /c)/, do TFUE, o Regulamento Bruxelas II /bis/ não é aplicável nas Ilhas Anglo-Normandas e a decisão cujo reconhecimento se pedia foi proferida por um tribunal de uma dessas Ilhas (Guernsey). Como tal, não era aplicável o regime de reconhecimento do Regulamento Bruxelas II /bis/, mas sim o regime da Convenção da Haia de 1970 sobre o Reconhecimento dos Divórcios e Separações de Pessoas (doravante Convenção da Haia de 1970).

[fn:6] Enunciados no Anexo II ao TFUE.

[fn:5] Cf. considerando n.º 96.

[fn:4] Recorda-se, porém, que o Reino Unido, por via do /brexit/, deixou de ser Estado-Membro da União Europeia no dia 1 de janeiro de 2021. Como tal, o Regulamento Bruxelas II /ter/ não será aplicável ao Reino Unido.

[fn:3] Cf. considerando n.º 95.

[fn:2] Estabelece o artigo 81.º, n.º 3, do Tratado sobre o Funcionamento da União Europeia (doravante TFUE) que: "Em derrogação do n.º 2, as medidas relativas ao direito da família /que tenham incidência transfronteiriça/ são estabelecidas pelo Conselho, deliberando de acordo com um processo legislativo especial. O Conselho delibera por unanimidade, após consulta ao Parlamento Europeu." (itálicos aditados).

[fn:1] Considerando n.º 2: "O presente regulamento estabelece normas de competência uniformes em matéria de divórcio, separação ou anulação do casamento, bem como regras para dirimir litígios em matéria de responsabilidade parental /que impliquem um elemento internacional/. (...)"; considerando n.º 3: "(...) A fim de alcançar esse objetivo, deverão ser reforçados os direitos das pessoas, em especial das crianças, no âmbito dos processos judiciais, de modo a facilitar a cooperação entre as autoridades judiciais e administrativas, assim como a execução das decisões judiciais em matéria de direito da família /que tenham implicações transfronteiriças/. (...)"; e considerando n.º 4: "Para o efeito, a União deve adotar, nomeadamente, medidas no domínio da cooperação judiciária em matéria civil /com implicações transfronteiriças/ em especial quando tal for necessário para o bom funcionamento do mercado interno." (itálicos aditados).
